Feature/api/update contacts handle
ya-pomogau/backend pull request #100
Opened 2024-06-12 16:44 UTC by IvannaBalanyuk

Создала ручку для редактирования (изменения) контактов в SystemApiController: PATCH system/contacts + создала соответствующий dto в src/common/dto:

- [x]  updateContacts() method
- [x] UpdateContactsRequestDto

2024-06-12 17:01 UTC, kspshnik requested changes
И ещё мой косяк в том, что это надо не в `SystemApi`, а всё-таки в `AdminApi`. 
Перенеси, пожалуйста.

2024-06-12 17:01 UTC, kspshnik commented on src/api/system-api/system-api.controller.ts
> +  public async updateContacts(@Req() req: Express.Request, @Body() dto: UpdateContactsRequestDto) {
А разве мы используем `req` хоть как-то? :) Нам тут не нужен юзверь.

2024-06-12 20:13 UTC, IvannaBalanyuk commented on src/api/system-api/system-api.controller.ts
> +  public async updateContacts(@Req() req: Express.Request, @Body() dto: UpdateContactsRequestDto) {
Артефакт копирования) Спасибо! Убрала)

2024-06-12 20:24 UTC, kspshnik submitted a review, later dismissed
Вот теперь всё супер!

Теперь дождёмся @INextYP %)

2024-06-13 06:00 UTC, INextYP requested changes
Привет! Молодец)
Есть моменты, которые я обнаружил при тестировании:
1. Нет валидации `dto` через класс-валидатор. Хочу напомнить, что dto - это класс, а не тип или интерфейс. Сейчас монга выкидывает ошибку, если что-то не так, но в действительности БД должна быть последним рубежом защиты.
2. Можно сколько угодно насоздавать контактов, но есть одно НО - нам всегда нужны будут только последние созданные контакты, а остальные будут тихо пылиться в БД...
3. Метод обновления не обновляет, а создает новую сущность в БД. При этом, если мы попытаемся передать id контактов, которые нужно обновить, получим - 500-ю ошибку с текстом
`E11000 duplicate key error collection: ya-pomogau-db.contacts index: _id_ dup key: { _id: ObjectId('666a8720e277fca0eadcfa7c') }`

@kspshnik подскажи тут.


Как я вижу всё это дело:
- при первой инициализации БД мы заполняем socialNetwork и email текстовыми данными (если в бд пусто), чтобы на фронт не приходила пустота)
- на фронте мы получим тестовые контакты, там уже есть айдишник, по этому айдишнику мы всегда будем обновлять только одну сущность контактов в БД и не будем создавать новые
- у нас должно быть 3 уровня защиты (валидации): 
   - валидация на фронте (чтобы мы не отправили некорректные данные на бекенд)
   - валидация на бекенде через классВалидатор - на случай, если кто-то через постман или ещё через что-то будет слать запросы (или если на фронте забыли валидацию сделать)
   - валидация перед записью в БД - тут вообще лучше не тревожить БД, но в качестве последнего рубежа безопасности записываемых данных лучше добавить валидацию...

2024-06-13 07:44 UTC, IvannaBalanyuk commented
- изменила метод `update `в `ContactsService`, чтобы он обновлял данные в имеющейся записи, а не плодил новые (использовала метод `findByIdAndUpdate`);
- скорректировала метод `updateContacts` в `AdminApiController `(теперь получаем id из params и передаем его методу сервиса);
- добавила в `UpdateContactsRequestDto` валидацию через class-validator;
- внесла правки на фронте (в части обеспечения возможности дёрнуть ручку, **валидацию на фронте пока не делала**).

Если что-то упустила - прошу пнуть в нужном направлении)

2024-06-13 09:00 UTC, INextYP commented
> * изменила метод `update `в `ContactsService`, чтобы он обновлял данные в имеющейся записи, а не плодил новые (использовала метод `findByIdAndUpdate`);
> * скорректировала метод `updateContacts` в `AdminApiController `(теперь получаем id из params и передаем его методу сервиса);
> * добавила в `UpdateContactsRequestDto` валидацию через class-validator;
> * внесла правки на фронте (в части обеспечения возможности дёрнуть ручку, **валидацию на фронте пока не делала**).
> 
> Если что-то упустила - прошу пнуть в нужном направлении)

А что сейчас произойдет, если мы передали невалидный или несуществующий в БД id контакта?

2024-06-13 09:10 UTC, kspshnik commented
> 2. Можно сколько угодно насоздавать контактов, но есть одно НО - нам всегда нужны будут только последние созданные контакты, а остальные будут тихо пылиться в БД...

Это не бага, а фича :)
Если ты обратишь внимание, в сервисе есть метод `getActual()`, который возвращает _последнюю_ запись. Именно он будет отдан по запросу на ручку `/system/contacts`. 
Аналогично построен и репозиторий СОК, кстати.

> 3. Метод обновления не обновляет, а создает новую сущность в БД. При этом, если мы попытаемся передать id контактов, которые нужно обновить, получим - 500-ю ошибку с текстом
>    `E11000 duplicate key error collection: ya-pomogau-db.contacts index: _id_ dup key: { _id: ObjectId('666a8720e277fca0eadcfa7c') }`
> 
> @kspshnik подскажи тут.

Мы **не передаём** никакого `_id` при изменении контактов, *только* данные.

> Как я вижу всё это дело:
> 
> * при первой инициализации БД мы заполняем socialNetwork и email текстовыми данными (если в бд пусто), чтобы на фронт не приходила пустота)
> * на фронте мы получим тестовые контакты, там уже есть айдишник, по этому айдишнику мы всегда будем обновлять только одну сущность контактов в БД и не будем создавать новые

Нет, так мы теряем информацию. Я бы к слову может добавил бы к модели поле `updatedBy: Mongo.ObjectId` для журналирования полного.

2024-06-13 09:13 UTC, kspshnik requested changes

2024-06-13 09:13 UTC, kspshnik commented on src/core/contacts/contacts.service.ts
> +  public async update(id: string, dto: UpdateContactsRequestDto): Promise<ContactsInterface> {
Нет. Возвращаем назад.

2024-06-13 09:13 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +  public async updateContacts(@Param('id') id: string, @Body() dto: UpdateContactsRequestDto) {
Нинада никаких `id`.

2024-06-13 09:13 UTC, kspshnik commented on src/core/contacts/contacts.service.ts
> +  public async update(id: string, dto: UpdateContactsRequestDto): Promise<ContactsInterface> {
А вот dto-шка отличная, её оставляем :)

2024-06-13 11:09 UTC, kspshnik commented
> > Нет, так мы теряем информацию
> 
> Позволю себе поучаствовать в дискуссии) Нам действительно НУЖНО хранить данные обо всех прошлых редакциях? Это же не данные волонтера/реципиента, утрата которых критична. Это данные собственника продукта, которые к тому же не будут часто меняться. Меня первоначальная реализация (когда на каждое изменение создается новая запись) несколько удивила при первом знакомстве.

Это называется журналирование: сохраняем все изменения, в идеале ещё и с автором. Если возникнет вопрос: а когда это почта поменялась, - на него будет прямой ответ. Здесь можно не сохранять автора изменений, так как это исключительная компетенция рута, а он по определению только один: сервер просто не позволит создать рута, его руками надо делать.
А вот если бы это была роль/полномочие (как с блогом, например) - то надо было бы сохранять ещё и автора в запись.

Второй момент: коллекцию создавать ради одной записи вообще смысла мало, иначе надо будет менять всю модель и создавать новую дискриминированную коллекцию для всех подобных данных. Так сложнее и непонятнее получится :)

> 
> > Нет. Возвращаем назад.
> 
> Это итоговое коллегиальное решение или мне пока подождать ответа @INextYP ?=)

В принципе я с Сашей обсуждал, но давай попросим @INextYP подтвердить :)

2024-06-13 11:26 UTC, IvannaBalanyuk commented
> Это называется журналирование: сохраняем все изменения, в идеале ещё и с автором. Если возникнет вопрос: а когда это почта поменялась, - на него будет прямой ответ. Здесь можно не сохранять автора изменений, так как это исключительная компетенция рута, а он по определению только один: сервер просто не позволит создать рута, его руками надо делать.
А вот если бы это была роль/полномочие (как с блогом, например) - то надо было бы сохранять ещё и автора в запись.
Второй момент: коллекцию создавать ради одной записи вообще смысла мало, иначе надо будет менять всю модель и создавать новую дискриминированную коллекцию для всех подобных данных. Так сложнее и непонятнее получится :)

@kspshnik,  спасибо за подробное объяснение=) логика и цель теперь понятны

> В принципе я с Сашей обсуждал, но давай попросим @INextYP подтвердить :)

Да не, я уточнила просто чтобы не сделать снова раньше времени. Пошла возвращать как было)))

2024-06-13 13:23 UTC, INextYP commented
> > > Нет, так мы теряем информацию
> > 
> > 
> > Позволю себе поучаствовать в дискуссии) Нам действительно НУЖНО хранить данные обо всех прошлых редакциях? Это же не данные волонтера/реципиента, утрата которых критична. Это данные собственника продукта, которые к тому же не будут часто меняться. Меня первоначальная реализация (когда на каждое изменение создается новая запись) несколько удивила при первом знакомстве.
> 
> Это называется журналирование: сохраняем все изменения, в идеале ещё и с автором. Если возникнет вопрос: а когда это почта поменялась, - на него будет прямой ответ. Здесь можно не сохранять автора изменений, так как это исключительная компетенция рута, а он по определению только один: сервер просто не позволит создать рута, его руками надо делать. А вот если бы это была роль/полномочие (как с блогом, например) - то надо было бы сохранять ещё и автора в запись.
> 
> Второй момент: коллекцию создавать ради одной записи вообще смысла мало, иначе надо будет менять всю модель и создавать новую дискриминированную коллекцию для всех подобных данных. Так сложнее и непонятнее получится :)
> 
> > > Нет. Возвращаем назад.
> > 
> > 
> > Это итоговое коллегиальное решение или мне пока подождать ответа @INextYP ?=)
> 
> В принципе я с Сашей обсуждал, но давай попросим @INextYP подтвердить :)

Пусть будет так

2024-06-13 13:23 UTC, INextYP approved these changes

2024-06-13 14:17 UTC, kspshnik approved these changes
Супер.
Вмёрживаем в `develop`

2024-06-13 14:19 UTC, merged