feature:
ya-pomogau/backend pull request #101
Opened 2024-06-12 17:35 UTC by LatyshevDD

- сформирован репозиторий Chats
- добавлен необходимый интерфейс, схема и модуль

2024-06-12 17:53 UTC, kspshnik requested changes
Прекрасный вариант. Осталось поправить по мелочи и правильно назвать - и репозиторий готов :)

2024-06-12 17:53 UTC, kspshnik commented on src/common/types/chats.types.ts
> +export interface ChatsInterface {
Это `MessageInerface`, не? :)

2024-06-12 17:53 UTC, kspshnik commented on src/common/types/chats.types.ts
>  export interface MessageInterface {
Это старый вариант `MessageInterface`, его удаляем. А старый `ChatInterface` закомментируй, пожалуйста - его удалит уже @AlexeyKrutyakov когда закроет #97 %)

2024-06-12 17:53 UTC, kspshnik commented on src/datalake/chats/schemas/chats.schema.ts
> +  @Prop({ required: false, default: [], type: [String] })
Здесь лучше тоже `SchemaTypes.String` использовать, кмк: этот декоратор фактически подаёт информацию Мангусту для базы, типы берём от Mongo.

2024-06-12 17:53 UTC, kspshnik commented on src/datalake/chats/schemas/chats.schema.ts
> +  @Prop({ required: true })
Здесь типизация будет `raw(rawUserProfile)`, сам `rawUserProfile` импортируем из `src/common/constants/mongoose-fields-raw-definition.ts`. Аналогию можно посмотреть в `BlogPost` (схема для `BlogPostRepository`).

2024-06-12 17:53 UTC, kspshnik commented on src/datalake/chats/schemas/chats.schema.ts
> +@Schema({ timestamps: true })
В опции схемы хорошо бы добавить
```ts
  toObject: {
    versionKey: false,
    virtuals: true,
  },
```
, посмотри как в других репозиториях сделано :)

2024-06-12 17:53 UTC, kspshnik commented on src/datalake/chats/chats.module.ts
Это `messages.module.ts`, у нас репозиторий _сообщений_, **не** чатов.

2024-06-12 17:53 UTC, kspshnik commented on src/datalake/chats/chats.repository.ts
Аналогично тут у нас `messages.repository.ts` ;o)

2024-06-12 18:41 UTC, LatyshevDD commented on src/common/types/chats.types.ts
> +export interface ChatsInterface {
Они отличаются, например в ChatsInterface нет поля timestamp, а у поля author другая типизация. Поэтому я решил добавить новый интерфейс

2024-06-12 19:10 UTC, kspshnik commented on src/common/types/chats.types.ts
> +export interface ChatsInterface {
Этот интерфейс я писал, ещё в прошлом году :)))

Он тупо устарел малость. `Mongo.ObjectId` - ссылка была на юзвверя, а по уму надо просто сразу скопировать данные, чтобы было меньше `.populate()` в ходе работы :)

2024-06-13 13:31 UTC, LatyshevDD commented
Внес корректировки

2024-06-13 14:23 UTC, kspshnik commented
> * сформирован репозиторий Chats
И да, это - репозиторий `Messages`

2024-06-13 15:21 UTC, kspshnik submitted a review, later dismissed
Супер! Теперь всё по своим местам :)
Ждём одобрения @INextYP и вмёрживаем.

2024-06-13 16:26 UTC, INextYP commented on src/datalake/messages/messages.repository.ts
> +  constructor(@InjectModel(Message.name) private chatsModel: Model<Message>) {
@kspshnik `messageModel` же тут?

2024-06-13 17:53 UTC, kspshnik commented on src/datalake/messages/messages.repository.ts
> +  constructor(@InjectModel(Message.name) private chatsModel: Model<Message>) {
Да. Просмотрел :( Спасибо!

@LatyshevDD поправь, пожалуйста, и перезапроси оба ревью?

2024-06-14 03:42 UTC, LatyshevDD commented
Поправил

2024-06-14 05:47 UTC, INextYP approved these changes
Всё хорошо! У меня нет замечаний)
@kspshnik %)

2024-06-14 07:29 UTC, kspshnik approved these changes
Вот теперь всё супер. Вмёрживаем :)

2024-06-14 07:30 UTC, merged