Add chats repository to datalake
ya-pomogau/backend pull request #102
Opened 2024-06-16 19:47 UTC by AlexeyKrutyakov

- Create interfaces for the collection according to the data model in src/common/types/chats.ts
- Create a repository module for a collection of chats in the data layer (/src/datalake) similar to UsersRepositoryModule
- Create a repository service for a collection of chats using BaseRepositoryService, similar to UsersRepository.

2024-06-18 07:52 UTC, kspshnik requested changes
Отлично сделана дискриминация :), но надо править типизацию, и TS-ную, и в декораторах Мангуста.

2024-06-18 07:52 UTC, kspshnik commented on src/common/constants/chats.ts
> +export const chats = {
Это надо создавать в `src/common/types/chats.types`.
Назвать `ChatTypes`, и  **рядом** cоздать `export type ChatTypes = keyof typeof ChatTypes`. Это работает **только вместе**. 
Вот образец:
```ts
export const EnumLike = {
  prop: 'prop',
  numProp: 22,
// ну и так далее :)
} as const;

export type EnumLike = keyof typeof EnumLike;
```

2024-06-18 07:52 UTC, kspshnik commented on src/common/types/chats.types.ts
> +export type ChatType = keyof typeof chats;
Так не надо, см. предыдущее замечание.

2024-06-18 07:52 UTC, kspshnik commented on src/common/types/chats.types.ts
> +export interface TaskChatModelInterface {
Отсутствует обязательное поле `taskId`

2024-06-18 07:52 UTC, kspshnik commented on src/common/types/chats.types.ts
> +  recipient: RecipientInterface;
В этом чате **нет** реципиента.

2024-06-18 07:52 UTC, kspshnik commented on src/common/types/chats.types.ts
> +export interface ConflictWithVolunteerChatModelInterface {
Отсутствует ссылка на чат с реципиентом.

2024-06-18 07:52 UTC, kspshnik commented on src/common/types/chats.types.ts
`_id`, `createdAt` и `updatedAt` надо удалить из интерфейсов моделей - они придут туда из `extends Document` в схеме. 
А в `TaskChatInterface` и т.д. - добавить в `extends` ещё и `MongooseIdAndTimestampsInterface`, который содержит все эти нужные поля и импортируется из `src/common/types/system.types.ts`, например:
```ts
export interface TaskChatInterface extends ChatModelInterface, TaskChatModelInterface, MongooseIdAndTimestampsInterface
{}
```

2024-06-18 07:52 UTC, kspshnik commented on src/datalake/chats/schemas/conflict-volunteer-chat.schema.ts
> +  @Prop({
Должен быть не реципиент, а чат с реципиентом типа `ObjectId`

2024-06-18 07:52 UTC, kspshnik commented on src/datalake/chats/schemas/task-chat.schema.ts
> +    type: SchemaTypes.ObjectId,
Типизация должна быть через `raw`

2024-06-18 07:52 UTC, kspshnik commented on src/datalake/chats/schemas/task-chat.schema.ts
> +    type: SchemaTypes.ObjectId,
Типизация должна быть через `raw`

2024-06-18 07:52 UTC, kspshnik commented on src/datalake/chats/schemas/task-chat.schema.ts
> +export class TaskChat extends Document implements TaskChatModelInterface {
Отсутствует ссылка на задачу

2024-06-20 20:05 UTC, AlexeyKrutyakov commented on src/datalake/chats/schemas/task-chat.schema.ts
> +    type: SchemaTypes.ObjectId,
@kspshnik где почитать про это вообще? я не очень понял концепцию

2024-06-22 08:46 UTC, AlexeyKrutyakov commented
@kspshnik привет
я всё поправил
посмотри пожалуйста

2024-06-22 11:15 UTC, kspshnik requested changes
Почти всё :) Осталось только решить несоответствие с дискриминаторами :)

2024-06-22 11:15 UTC, kspshnik commented on src/datalake/chats/chats-repository.module.ts
> +          { name: TaskChat.name, schema: TaskChatSchema },
Так не сработает. Имена схем не соответствуют значениям в типе (перечислении). Надо изменять ключи и значения в `ChatType` до полного соответствия.

2024-06-22 11:17 UTC, kspshnik commented on src/datalake/chats/schemas/task-chat.schema.ts
> +    type: SchemaTypes.ObjectId,
Типизацию допоправь :)

2024-06-22 11:18 UTC, kspshnik commented
И интерфейсы тоже поправь :)

2024-06-24 18:37 UTC, AlexeyKrutyakov commented on src/datalake/chats/chats-repository.module.ts
> +          { name: TaskChat.name, schema: TaskChatSchema },
не пойму, зачем менять ключи?
```
export const ChatTypes = {
  TASK_CHAT: 'TaskChat',
  SYSTEM_CHAT: 'SystemChat',
  CONFLICT_CHAT_WITH_VOLUNTEER: 'ConflictChatWithVolunteer',
  CONFLICT_CHAT_WITH_RECIPIENT: 'ConflictChatWithRecipient',
} as const;

export type ChatType = keyof typeof ChatTypes;
```
так не сработает?

2024-06-24 18:38 UTC, AlexeyKrutyakov commented
> И интерфейсы тоже поправь :)

про интерфейсы вообще не понял

2024-06-24 19:07 UTC, AlexeyKrutyakov commented
@kspshnik  если правильно понял замечания, то всё поправил, посмотри пожалуйста

2024-06-25 10:49 UTC, kspshnik commented on src/datalake/chats/chats-repository.module.ts
> +          { name: TaskChat.name, schema: TaskChatSchema },
Должно :) Но лучше добиться 100% соответствия значений в `as const` и  `...Chat.name` - иначе тупо записываться не будет в коллекцию, в лучшем случае Мангуст оборётся, в худшем - тупо дропнет.
Я бы сделал `TaskChat: 'TaskChat'` и т.д.

2024-06-25 11:30 UTC, kspshnik requested changes
Да, про интерфейсы ты правильно понял :)
И буквально последнее. Про админа в системном чате - это mea culpa, сорри. Просмотрел :(

2024-06-25 11:30 UTC, kspshnik commented on src/common/types/chats.types.ts
> +export interface SystemChatModelInterface {
Наверное, тут ещё нужен `admin: AdminInterface`.

2024-06-25 11:30 UTC, kspshnik commented on src/common/types/chats.types.ts
> +export interface ChatModelInterface {
А точно не забыли `isActive: boolean` ?

2024-06-25 11:30 UTC, kspshnik commented on src/common/types/chats.types.ts
И ещё можно добавить `ConflictChatInterface` как объединение интерфейсов двух конфликтных чатов :)

2024-06-25 17:37 UTC, AlexeyKrutyakov commented on src/common/types/chats.types.ts
@kspshnik а в конфликтных чатах админ не нужен?

2024-06-25 20:44 UTC, AlexeyKrutyakov commented
@kspshnik всё поправил

2024-06-27 16:23 UTC, AlexeyKrutyakov commented
поправил

2024-06-27 17:21 UTC, kspshnik commented on src/datalake/chats/schemas/system-chat.schema.ts
> +    type: SchemaTypes.ObjectId,
Типизация не соответствует интерфейсу

2024-06-27 17:23 UTC, kspshnik commented on src/datalake/chats/schemas/task-chat.schema.ts
> +    immutable: true,
Это изменяемое и необязательное. При создании задачи волонтёр ещё её точно не выбрал 5)

2024-06-27 17:24 UTC, kspshnik commented on src/common/types/chats.types.ts
Всё, что в схеме необязательно и типизировано как `... | null`, тут надо типизировать так же :)

2024-06-27 17:38 UTC, kspshnik commented on src/datalake/chats/schemas/task-chat.schema.ts
> +    immutable: true,
Сорри, это неверно. А в коде верно.

2024-06-27 18:39 UTC, kspshnik approved these changes
Всё! 
Отлично сделано.

2024-06-28 14:19 UTC, INextYP approved these changes
Отлично!

2024-06-28 14:40 UTC, merged