Refactor/tasks/account points and tasks for volunteer
ya-pomogau/backend pull request #108
Opened 2024-06-27 19:08 UTC by IvannaBalanyuk

Привет!
- [ ] Ввела в схему волонтёра поле `tasksCompleted` типа `number` со значением по умолчанию `0`;
- [ ] В сервисе задач создала **приватный** метод завершения заявки как выполненной, который должен:
   - закрывать саму заявку как _успешно_ _выполненную_ ;
   - начислять (прибавлять к имеющимся) волонтёру баллы (количество баллов определяется категорией выполненной задачи);
   - увеличивать счётчик успешных задач у волонтёра на единицу.
   
   _По последним двум пунктам - не могу понять почему, но не отрабатывает обновление информации о волонтере. Возвращает объект, всё ок, БД никакой ошибки не выдает, но значения в score и tasksCompleted не меняются. Может упускаю что-то очевидное и сможете мне подсказать)_

- [ ] В сервисе  задач создала **приватный** метод  завершения заявки как *не выполненной*, **без начисления баллов и увеличения счётчика** .
- [ ] Перевела имеющиеся публичные методы (reportTask и resolveConflict) на использование выше созданных приватных методов вместо прямого обращения к репозиториям.
- [ ] Проверила правильность работы функционала.

2024-07-02 05:53 UTC, IvannaBalanyuk commented on src/core/tasks/tasks.service.ts
> +    const updatedVolonteer = (await this.usersRepo.findByIdAndUpdate(
Не помогло(
В `updatedVolonteer`, по-прежнему, возвращается объект без изменений. И в базе тоже не меняется.

2024-07-07 12:14 UTC, INextYP commented on src/core/tasks/tasks.service.ts
> +    const updatedVolonteer = (await this.usersRepo.findByIdAndUpdate(
@IvannaBalanyuk Привет! Попробуй вот так (добавляем `overwriteDiscriminatorKey`):

```js
const updatedVolonteer = (await this.usersRepo.findByIdAndUpdate(
      volunteerId,
      {
        score: newScore,
        tasksCompleted: newTasksComleted,
      },
      { new: true, overwriteDiscriminatorKey: true }
    )) as User & Volunteer;
```

2024-07-08 07:34 UTC, IvannaBalanyuk commented on src/core/tasks/tasks.service.ts
> +    const updatedVolonteer = (await this.usersRepo.findByIdAndUpdate(
@INextYP Привет! К сожалению, это тоже не помогло.
Но я порылась в направлении работы методов Mongoose при использовании дискриминатора и нашла следующее:
![image](https://github.com/ya-pomogau/backend/assets/124444858/528c58b6-81c5-4d42-bc81-39ea37b336b2)
![image](https://github.com/ya-pomogau/backend/assets/124444858/12e129d3-bbd2-4dfd-9ee4-f2a4ac063ffb)
![image](https://github.com/ya-pomogau/backend/assets/124444858/61cde76d-1508-48d3-8296-0a7e138c8b87)
![image](https://github.com/ya-pomogau/backend/assets/124444858/e7a0212c-b9fa-4ad3-9335-7d9202b1df75)
![image](https://github.com/ya-pomogau/backend/assets/124444858/087576b7-3fbc-44f9-bda2-87415d145096)

Т.е. для корректной работы метода при обновлении специфичных полей дискриминатора нужно использовать именно ту схему, в которой эти поля содержатся.

Может наша проблема аналогична той, которую решают в примере?

Я, правда, пока не представляю как именно мы можем обратиться к нужной схеме в нашем случае.

Ссылка на источник: [https://stackforgeeks.com/blog/document-not-updated-in-findoneandupdate#troubleshooting-mongoose-findoneandupdate-with-discriminators-updating-discriminator-specific-fields-in-mongodb](https://stackforgeeks.com/blog/document-not-updated-in-findoneandupdate#troubleshooting-mongoose-findoneandupdate-with-discriminators-updating-discriminator-specific-fields-in-mongodb)

2024-07-08 08:01 UTC, IvannaBalanyuk commented
@kspshnik @INextYP Нашла как заставить `findOneAndUpdate()` работать - добавила discriminatorKey (role) в фильтр: `{ _id: volunteerId, role: volunteer.role }`.

Нашла тут: [https://github.com/Automattic/mongoose/issues/6794](https://github.com/Automattic/mongoose/issues/6794) (см. третий сверху коммент)

2024-07-08 15:45 UTC, INextYP commented
> @kspshnik @INextYP Нашла как заставить `findOneAndUpdate()` работать - добавила discriminatorKey (role) в фильтр: `{ _id: volunteerId, role: volunteer.role }`.
> 
> Нашла тут: [Automattic/mongoose#6794](https://github.com/Automattic/mongoose/issues/6794) (см. третий сверху коммент)

Умничка, что нашла решение) Кстати, вот это решение тоже работает (проверено), просто в предыдущем комменде забыл про `role` ^)
```js
const updatedVolonteer = (await this.usersRepo.findByIdAndUpdate(
      volunteerId,
      {
        score: newScore,
        role, // сюда пишем роль пользователя
        tasksCompleted: newTasksComleted,
      },
      { new: true, overwriteDiscriminatorKey: true }
    )) as User & Volunteer;
```

2024-07-09 19:56 UTC, kspshnik requested changes
Супер! Отдельно молодец, что нашла решение с дискриминантами.

Осталось добавить в одном месте `Promise.all()`, поправить по мелочи схему, и одно в целом необязательное пожелание: перетипизировать dto-шки от приватных методов. Кстати, их лучше вынести в интерфейс, чем городить инлайновые типизации - так читабельнее и красивее код.

2024-07-09 19:56 UTC, kspshnik commented on src/core/tasks/tasks.service.ts
> +    const updatedVolonteer = (await this.usersRepo.findOneAndUpdate(
Надо вынести эту штуку в приватный метод, а дальше в `if (!userIndex)`/`if (userIndex)` использовать его вместе с обновлением таски через `Promise.all()`, чтобы гарантировать одновременность обоих изменений.

2024-07-09 19:56 UTC, kspshnik commented on src/core/tasks/tasks.service.ts
> +    adminResolveResult?: ResolveResult;
Смотри, может быть _либо_ `adminResolveResult` _либо_ `userIndex`, да? 
Можно типизировать так, чтобы было невозможно передать оба.
Чёт-гопота предлагает такую тему:
 ```ts
type OneOf<T, K extends keyof T> = { [P in K]: (Record<P, T[P]> & Partial<Record<Exclude<K, P>, never>>) }[K];

type OneOrTheOther<T, K extends keyof T> = (OneOf<T, K>) & Omit<T, K>;

// Пример использования:
type Example = { 
  prop1?: string;
  prop2?: string;
  otherProp1?: number;
  otherProp2?: boolean;
};

type ExampleOneOrTheOther = OneOrTheOther<Example, 'prop1' | 'prop2'>;

const valid1: ExampleOneOrTheOther = { prop1: "value1", otherProp1: 42 }; // корректно
const valid2: ExampleOneOrTheOther = { prop2: "value2", otherProp2: true }; // корректно
const valid3: ExampleOneOrTheOther = { prop2: "value2", otherProp1: 42, otherProp2: true }; // корректно
const invalid1: ExampleOneOrTheOther = { prop1: "value1", prop2: "value2", otherProp1: 42 }; // некорректно, ошибка
const invalid2: ExampleOneOrTheOther = { otherProp1: 42 }; // некорректно, ошибка
```
Проверь и попробуй адаптировать, пожалуйста?
Если не получится плюс-минус быстро - пёс с ним, это "Можно лучше" в чистом виде :)

2024-07-09 19:56 UTC, kspshnik commented on src/datalake/users/schemas/volunteer.schema.ts
> +  @Prop({ type: SchemaTypes.Number, required: true, default: 0 })
А зачем и `required` и `default`? %) Обычно либо требуем передать при создании либо задаём стартовое (по умолчанию) значение.
Нам тут интереснее получить ноль в любом раскладе, чтобы не рефакторить создание юзверя :)

2024-07-11 16:52 UTC, IvannaBalanyuk commented on src/datalake/users/schemas/volunteer.schema.ts
> +  @Prop({ type: SchemaTypes.Number, required: true, default: 0 })
@kspshnik, готово)

- [x] подкорректировала схему волонтера (убрала `required`);
- [x] вынесла обновление данных волонтера в приватный метод `updateVolunteerScore()`;
- [x] применила `Promise.allSettled()`, чтобы гарантировать одновременность изменений;
- [x] вынесла в интерфейсы типизацию пропсов для методов `closeTaskAsFulfilled()` и `closeTaskAsRejected()`;
- [x] реализовала типизацию OneOrTheOther для пропсов adminResolveResult и userIndex. Не въехала сходу в тот вариант, что ты предложил протестировать, поэтому не стала пока тратить время. Нашла альтернативный путь ([https://dev.to/maissenayed/conditional-react-props-with-typescript-43lg](https://dev.to/maissenayed/conditional-react-props-with-typescript-43lg):
![image](https://github.com/ya-pomogau/backend/assets/124444858/c1f7556f-3643-4ca0-acb7-ee9eae26675a)

2024-07-11 16:53 UTC, IvannaBalanyuk commented
@kspshnik, готово)

- [x] подкорректировала схему волонтера (убрала `required`);
- [x] вынесла обновление данных волонтера в приватный метод `updateVolunteerScore()`;
- [x] применила `Promise.allSettled()`, чтобы гарантировать одновременность изменений;
- [x] вынесла в интерфейсы типизацию пропсов для методов `closeTaskAsFulfilled()` и `closeTaskAsRejected()`;
- [x] реализовала типизацию OneOrTheOther для пропсов adminResolveResult и userIndex. Не въехала сходу в тот вариант, что ты предложил протестировать, поэтому не стала пока тратить время. Нашла альтернативный путь ([https://dev.to/maissenayed/conditional-react-props-with-typescript-43lg](https://dev.to/maissenayed/conditional-react-props-with-typescript-43lg):
![image](https://github.com/ya-pomogau/backend/assets/124444858/c1f7556f-3643-4ca0-acb7-ee9eae26675a)

2024-07-12 07:46 UTC, kspshnik requested changes
Типы и перенос куда следует остались :)

2024-07-12 07:46 UTC, kspshnik commented on src/core/tasks/tasks.service.ts
> +    let volunteerUpdateResult;
Тут бы типизировать...

2024-07-12 07:46 UTC, kspshnik commented on src/core/tasks/tasks.service.ts
> +    let taskUpdateResult;
И тут тож :)

2024-07-12 07:46 UTC, kspshnik commented on src/core/tasks/tasks.service.ts
> +  private updateVolunteerScore(
Это в `UsersService` должно быть :)

2024-07-12 07:46 UTC, kspshnik commented on src/core/tasks/tasks.service.ts
> +    return this.usersRepo.findOneAndUpdate(
Мы **НЕ РАБОТАЕМ С ЧУЖИМ РЕПОЗИТОРИЕМ**, в `TasksSevice` обращение должно быть _только_ к `TasksRepository`

2024-07-12 07:47 UTC, kspshnik commented
и кстати актуализуй чекбоксики в описании ПР?

2024-07-12 12:37 UTC, IvannaBalanyuk commented on src/core/tasks/tasks.service.ts
> +    let volunteerUpdateResult;
- [x] Протипизировала

2024-07-12 12:38 UTC, IvannaBalanyuk commented on src/core/tasks/tasks.service.ts
> +    let taskUpdateResult;
- [x] и тут тоже протипизировала=)

2024-07-12 12:39 UTC, IvannaBalanyuk commented on src/core/tasks/tasks.service.ts
> +  private updateVolunteerScore(
- [x] перенесла)

2024-07-12 12:46 UTC, IvannaBalanyuk commented on src/core/tasks/tasks.service.ts
> +    return this.usersRepo.findOneAndUpdate(
- [x] Была неправа, исправила) Сбило с толку, что `UsersRepository` уже присутствует в `TasksService` - не учла, что обращаться к нему можно только для получения данных.

2024-07-12 13:19 UTC, kspshnik approved these changes
Ура, победа!!!

Теперь слово за @INextYP %)

2024-07-12 13:19 UTC, kspshnik commented on src/core/tasks/tasks.service.ts
> +    return this.usersRepo.findOneAndUpdate(
Это тяжёлое наследие, и от этого избавимся постепенно.

2024-07-13 13:13 UTC, INextYP approved these changes
Отлично! Можно мержить.

2024-07-13 13:58 UTC, merged