Refactor/categories bulk edit
ya-pomogau/backend pull request #109
Opened 2024-06-28 17:11 UTC by IvannaBalanyuk

Привет!)

- [x] Создала интерфейс `BulkUpdateCategoryInterface `для dto.
- [x] Создала dto `ApiBulkUpdateCategoryDto`, подготовила для работы `class-validator`.
- [x] Написала ручку `updateCategoriesByIds `в `AdminApiController` для редактирования одновременно нескольких категорий.
- [x] Создала соответствующий метод `updateCategoriesByIds `в `CategoriesService`.
- [x] Протестировала работу ручки и метода.

2024-07-01 17:22 UTC, kspshnik requested changes
Очень хорошо, но dto лучше типизировать наоборот: поле класса массив, а не массив классов :)

Ручка должна получать dto в виде _объекта_, **не** массива.

2024-07-01 17:22 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +  async updateCategoriesByIds(updateData: ApiBulkUpdateCategoryDto[], user: AdminInterface) {
А зачем тут массив?

2024-07-01 17:22 UTC, kspshnik commented on src/common/types/category.types.ts
> +  id: string;
Наверное, тут всё-таки `Array<string>` ?

2024-07-02 05:20 UTC, IvannaBalanyuk commented on src/common/types/category.types.ts
> +  id: string;
Привет!

Если тут будет массив идентификаторов, то как реализовать метод, чтобы можно было массово поменять, к примеру, баллы? Администратор может отредактировать несколько категорий и поменять в каждой из них баллы **на разные** значения. Поэтому я посчитала, что нам нужен массив объектов, в каждом из которых содержится id для идентификации + те свойства, которые подлежат изменению.

Если сделать поле id в виде массива, а остальное оставить в текущем виде, то мы сможем поменять категории массово, но только на одинаковое новое значение. Или я не до конца понимаю и нужно ещё что-то в коде менять? Подскажи, пожалуйста)

2024-07-02 06:19 UTC, kspshnik commented on src/common/types/category.types.ts
> +  id: string;
Смотри, главный фокус в том, что сама `dto` не должна быть массивом.
`updateData: ApiBulkUpdateCategoryDto[]` - вот это не ОК.
Может быть свойство  `data: Array<Record<string, number>>` у `dto`, например.

2024-07-02 06:49 UTC, IvannaBalanyuk commented on src/common/types/category.types.ts
> +  id: string;
Аха, поняла, спасибо) Сама уже начала в этом направлении исправлять. В течение часа запушу правки

2024-07-02 07:33 UTC, IvannaBalanyuk commented on src/common/types/category.types.ts
> +  id: string;
@kspshnik, исправила. Теперь используется `ApiBulkUpdateCategor**ies**Dto`.
Мне не очень нравится "лишняя" dto-шка ApiBulkUpdateCategoryDto - она вроде как нужна, чтобы обеспечить валидацию, но в роли dto не используется. Что можно/нужно с этим сделать?

2024-07-02 07:38 UTC, kspshnik commented on src/common/types/category.types.ts
> +  id: string;
Настроить валидацию :) Покопайся, там есть декораторы, которые дают провалидировать массив или описать его элементы.

2024-07-02 09:26 UTC, IvannaBalanyuk commented on src/common/types/category.types.ts
> +  id: string;
@kspshnik, использовала `@ValidateNested({ each: true })` и декоратор `@Type(() => TypeOfEachObject)` (class-transformer)

2024-07-09 20:02 UTC, kspshnik requested changes
Отлично!
Остался последний штрих - в отбросе админа без категории убедиться, что он не рут, руту нинада категорий - он может всё :)

2024-07-09 20:02 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +      user.role !== UserRole.ADMIN ||
Надо ещё на рута проверить, ему пофиг на массив разрешений :)

2024-07-11 08:43 UTC, IvannaBalanyuk commented
@kspshnik Привет!

> Остался последний штрих - в отбросе админа без категории убедиться, что он не рут

Добавила проверку на рута в `updateCategoriesByIds `и в `updateCategoryById `(ибо там аналогичная логика допуска).
Хотела было сделать приватный метод и вынести туда проверку, но это полумера. По-хорошему, создать бы на бэке аналог `usePermission`?)

2024-07-11 09:16 UTC, kspshnik commented
Хотела было сделать приватный метод и вынести туда проверку, но это полумера. По-хорошему, создать бы на бэке аналог `usePermission`?)

А посмотри на `RolesGuard()` ;o), им закрыт контроллер.

2024-07-11 09:17 UTC, kspshnik commented
> 

А посмотри на `RolesGuard()`, которым закрыты ручки :)

Кстати, вынести одинаковый код в приватные методы - не самая плохая тема.

2024-07-12 07:51 UTC, kspshnik requested changes
Перепутала импорты :)
Лучше вообще удали `obsolete/`, чтобы не путаться.

2024-07-12 07:51 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +import { User } from 'obsolete/users/entities/user.entity';
Это **НЕВЕРНЫЙ** импорт. Исправь, пожалуйста. Из `obsolete/` **НИЧЕГО НЕ БЕРЁМ**

2024-07-12 13:02 UTC, IvannaBalanyuk commented on src/core/categories/categories.service.ts
> +import { User } from 'obsolete/users/entities/user.entity';
оу! ничего себе... спасибо) буду перепроверять тщательнее

2024-07-13 14:11 UTC, IvannaBalanyuk commented
- [x] удалила неверный импорт;
- [x] вынесла повторяющийся код проверки прав админа в отдельный приватный метод (реализация мне что-то не очень нравится);
- [x] заменила код проверки прав админа в методах сервиса на использование приватного метода.

2024-07-13 14:33 UTC, kspshnik requested changes
В общем, да, можно чуть поменять логику проверки:
0. Кидаем ошибку не из проверятеля, а по месту его вызова:
```ts
if (!this.checkIsEnoughRights) {
   throw new ForbiddenException(exceptions.category.notEnoughRights);
}
```
1. Админ или нет? Если нет - сразу возвращаем `false`.
2. Требуется root или нет? Проверяем типа `onlyRoot && !user.isRoot` - так даст `true` только когда `onlyRoot === true` и `user.isRoot === false`, и при `true` возвращаем `false`.
3. Проверяем массив разрешений, как у тебя и есть.
4. Возвращаем `hasPermission || user.isRoot`. Ну или это можно после первого пункта сразу проверить, тогда в п.3 сразу возвращаем результат проверки массива разрешений - остальные кейсы уже отработаны.

А ещё эту функцию можно вынести в `src/common/helpers` для переиспользования везде - она чистая получается, и не завязана на месте использования от слова никак :)

2024-07-13 14:33 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +  ): boolean {
Я бы здесь сразу проверил на "не админа" и вернул `false`, чтобы больше это не проверять :)

2024-07-14 18:52 UTC, IvannaBalanyuk commented
> В общем, да, можно чуть поменять логику проверки:

Вот я изначально так и сделала (только в helpers не вынесла), а потом решила "улучшить")

- [x] метод `checkIsEnoughRights(...)` вынесла в функцию в `src/common/helpers`;
- [x] из функции убрала выброс ошибки, добавила его в местах её вызова;
- [x] функцию откорректировала в соответствии с тем, что она не выбрасывает ошибку, а только возвращает true/false.

2024-07-14 23:25 UTC, kspshnik approved these changes
Супер! Вот теперь отлично :)

2024-07-18 05:33 UTC, INextYP approved these changes

2024-07-18 07:33 UTC, merged