[Refactor] change points in active tasks on category edit
ya-pomogau/backend pull request #111
Opened 2024-07-10 23:08 UTC by PheRum

При изменении баллов за категорию (редактирование категории), необходимо изменить баллы во всех активных задачах из этой категории.

2024-07-11 04:24 UTC, kspshnik requested changes
Отлично!
Только расширь на все статусы, кроме завершённого :)
Ну и `await` там надо снять, иначе промиса не будет :)
И нейминг до кучи.

И проверь через Postman/Insomnia на локальной базе.

2024-07-11 04:24 UTC, kspshnik commented on src/core/tasks/tasks.service.ts
> +        { category: categoryId, status: TaskStatus.CREATED },
Смотри, это только неразобранные задачи. Статус должен быть **не** `TaskStatus.COMPLETED`, все остальные подойдут :)

2024-07-11 04:24 UTC, kspshnik commented on src/core/categories/categories.service.ts
>        res = await this.categoriesRepo.findOneAndUpdate({ _id: id }, updateData, { new: true });
Тогда тут без `await` надо, ну и переименовать в `tasksUpdatePromise` :)

2024-07-11 04:24 UTC, kspshnik commented on src/core/tasks/tasks.service.ts
> +        { $set: { points } }
А ещё надо в объект опций добавить `{ new: true }`, иначе Мангуст вернёт _старый_ объект.

2024-07-11 04:24 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +      await Promise.all([res, pointsUpdate]);
Результат тоже лучше сохранить в переменную примерно так:
```ts
const [res, tasks] = await Promise.all([res, pointsUpdate]);
```
,ведь `Promise.all()` вернёт массив, его сразу деструктуризуем :)

2024-07-11 04:24 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +      const pointsUpdate = this.tasksService.updatePointsByCategory(id, updateData.points);
Лучше назвать типа `pointsUpdatePromise`

2024-07-11 09:58 UTC, PheRum commented on src/core/tasks/tasks.service.ts
> +        { category: categoryId, status: TaskStatus.CREATED },
поправил

2024-07-11 09:59 UTC, PheRum commented on src/core/categories/categories.service.ts
>        res = await this.categoriesRepo.findOneAndUpdate({ _id: id }, updateData, { new: true });
сделал

2024-07-11 09:59 UTC, PheRum commented on src/core/tasks/tasks.service.ts
> +        { $set: { points } }
изменил

2024-07-11 10:00 UTC, PheRum commented on src/core/categories/categories.service.ts
> +      await Promise.all([res, pointsUpdate]);
немного по-другому сделал.

при твоем варианте выходит так, что константа tasks не использована

2024-07-11 10:00 UTC, PheRum commented on src/core/categories/categories.service.ts
> +      const pointsUpdate = this.tasksService.updatePointsByCategory(id, updateData.points);
изменил

2024-07-11 11:51 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +      await Promise.all([res, pointsUpdate]);
Но фронтенд ничего другого не ожидает :)

@INextYP, что скажешь?

2024-07-11 11:53 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +      const [category] = await Promise.all([categoryUpdatePromise, pointsUpdatePromise]);
ОК, но лучше указать явно `const [category,] = ...`, так потом читающему код будет очевидно, что ты сознательно отбросил второй возврат :)

Если других правок не будет - не меняй, это явное "Можно лучше". А если будут - сделай :)

2024-07-11 11:54 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +      await Promise.all([res, pointsUpdate]);
А, ты просто отбросил. ОК всё :)

2024-07-11 11:59 UTC, kspshnik requested changes
Супер! Осталось победить зависимости :)
Это делается в модуле. Посмотри на примере `src/core/auth.module.ts`, как там подключён `UsersService`.

2024-07-11 18:19 UTC, PheRum commented
> Супер! Осталось победить зависимости :) Это делается в модуле. Посмотри на примере `src/core/auth.module.ts`, как там подключён `UsersService`.

добавил

2024-07-12 07:52 UTC, kspshnik commented
> добавил

Получилось оттестировать в Postman/Insomnia?

2024-07-12 08:05 UTC, PheRum commented
> > добавил
> 
> Получилось оттестировать в Postman/Insomnia?

Не подымается докер, падает с ошибкой, поэтому не протектисровать не удается.

Докер подымаю командой docker-compose up

![2024-07-12_11-04-52](https://github.com/user-attachments/assets/7985a2cd-8a2c-421c-ba61-4bb283547799)

2024-07-18 07:32 UTC, kspshnik commented
> 
> Не подымается докер, падает с ошибкой, поэтому не протестировать не удается.

Получилось поднять теперь? Или ещё проблема?

2024-07-18 07:37 UTC, PheRum commented
> > Не подымается докер, падает с ошибкой, поэтому не протестировать не удается.
> 
> Получилось поднять теперь? Или ещё проблема?

Да, получилось.  Докер подымается, но с проверкой задачи все равно сложности есть.
БД пустая, нужен токен для того, чтобы сделать запрос в админку и т.д

2024-08-01 10:36 UTC, kspshnik commented
Передача в связи с выходом участника из проекта.

2024-08-01 10:36 UTC, closed without merging