Создание Websockets gateway для системных сообщений
ya-pomogau/backend pull request #117
Opened 2024-07-16 16:37 UTC by IvannaBalanyuk

1. Создала файл `system-api.gateway.ts`, а в нём - класс `SystemApiGateway`.
2. Добавила `SystemApiGateway` в `providers` модуля `SystemApiModule`.
3. Реализовала методы жизненного цикла OnGatewayInit, OnGatewayConnection, OnGatewayDisconnect (методы `afterInit(...)`, `handleConnection(...)` и `handleDisconnect(...)` соответственно).

Реализация методов:

- [ ] `afterInit(...)` - пока в формате наброска, так как не разобралась что именно он должен делать;
- [ ] `handleConnection(...)` - отправляет дифференцированные сообщения текущему пользователю и всем пользователям, кроме текущего, но формат сообщений не соответствует задаче, так как я не смогла вытащить данные из @MessageBody(). Пробовала и протипизированный объект user типа `{ id: string; name: string }` с сохранением данных в Map и просто строку - упорно получаю undefined. С id из параметров тоже не справилась - в Postman отправляю запрос с параметром id - на сервере получить его не могу. Поэтому пока просто сохраняю в массив `client.id` и его же использую в сообщениях вместо `user.name`.
- [ ] `handleDisconnect(...)` - отправляет сообщение всем пользователям, кроме текущего, но формат сообщения не соответствует задаче, так как сохранить данные юзера в Map не удалось и потому неоткуда взять имя.

Внимание!
При запуске проекта с помощью `npm run start` возникает следующая ошибка (не относится к задаче): 
![image](https://github.com/user-attachments/assets/e4c932a5-f291-449c-9b6c-c07987eab910)

2024-07-18 07:31 UTC, kspshnik requested changes
Для получения тела сообщения надо использовать соответствующий декоратор (`@MessageBody()`) как мы делаем для получения тела HTTP-запроса :), посмотри в документации [Nest](https://docs.nestjs.com/websockets/gateways): 
```ts
@SubscribeMessage('events')
handleEvent(@MessageBody() data: string): string {
  return data;
}
```
Нам просто надо получать оба параметра: и сокет, и тело.

А при соединении query-параметры можно вытащить из [сокета](https://socket.io/docs/v4/server-socket-instance/#sockethandshake)

2024-07-19 06:49 UTC, INextYP approved these changes
На текущий момент всё отлично. Для базы хватит. Можно мёржить :)

2024-07-19 08:19 UTC, kspshnik commented on src/api/system-api/system-api.gateway.ts
> +    const {id, name} = client.handshake.query as unknown as WSConnectUserDto;
В будущем надо разобраться, как это затипизировать через дженерики.

2024-07-19 08:21 UTC, kspshnik approved these changes
Отличный starterkit!!!!

2024-07-19 08:21 UTC, kspshnik commented on src/core/create-user.handler.ts
> +  async execute({ dto }: CreateUserCommand) {
Супер, спасибо!

2024-07-19 08:23 UTC, merged