feat: add socket auth guard, check token at SystemApiGateway
ya-pomogau/backend pull request #129
Opened 2024-07-24 17:11 UTC by IvannaBalanyuk

Добавила дополнительный `Guard` по пути `src/common/guards`.
- [ ] Назвала файл - `socket-auth.guard.ts`

Гвард:
- [ ] Наследуется от `CanActivate` (`implements CanActivate`)
- [ ] Внедряет в конструкторе `JwtService`
- [ ] В методе `canActivate` проверяет наличие токена, а также верифицирует его с помощью
`jwtService.verify` метода
- [ ] Токен при подключении нужно указывать в `headers.authorization`
- [ ] Если токен невалиден, то выбрасывается `WsException`

`handleConnection` метод видоизменила:
- [ ] Теперь мы не передаём query при подключении, а проверяем токен пользователя и забираем объект пользователя из токена (пока просто выводим в консоль верифицированного пользователя), т.е.:
```
// 1. Проверяем токен (в случае, если он невалиден, то выбрасываем WsException)
// 2. Из полученного выше `payload` получаем объект пользователя
// 3. Выводим в консоль пользователя
```
- [ ] в handleConnection поменяла данные пользователя из query на те, что у нас приходит из объекта пользователя

2024-07-26 18:38 UTC, INextYP commented on src/common/guards/socket-auth.guard.ts
> +    console.log('canActivate');
а давай не будем плодить население консолей?)))

2024-07-26 18:38 UTC, INextYP commented on src/common/guards/socket-auth.guard.ts
> +    const token = context.getArgs()[0].handshake.headers.authorization;
Тут всё же лучше работать через `context.switchToWs()`

2024-07-26 18:38 UTC, INextYP commented on src/api/system-api/system-api.gateway.ts
> +  @UseGuards(SocketAuthGuard)
Гарду лучше на верхний уровень поставить, чтобы покрыть все ручки сокета 
```js
@UseGuards(SocketAuthGuard)
@WebSocketGateway({ ... })
```

2024-07-26 19:50 UTC, IvannaBalanyuk commented on src/common/guards/socket-auth.guard.ts
> +    console.log('canActivate');
My bad:-$

2024-07-27 06:46 UTC, IvannaBalanyuk commented on src/common/guards/socket-auth.guard.ts
> +    console.log('canActivate');
Удалила лишний console.log(...)

2024-07-27 06:47 UTC, IvannaBalanyuk commented on src/common/guards/socket-auth.guard.ts
> +    const token = context.getArgs()[0].handshake.headers.authorization;
Исправила)

2024-07-27 06:47 UTC, IvannaBalanyuk commented on src/api/system-api/system-api.gateway.ts
> +  @UseGuards(SocketAuthGuard)
Перенесла на верхний уровень

2024-07-29 07:19 UTC, INextYP requested changes
Остался последний момент :)

2024-07-29 07:19 UTC, INextYP commented on src/common/guards/socket-auth.guard.ts
> +      throw new UnauthorizedException(exceptions.auth.unauthorized);
А у нас вебсокет может вернуть http error?)

2024-07-29 07:44 UTC, IvannaBalanyuk commented on src/common/guards/socket-auth.guard.ts
> +      throw new UnauthorizedException(exceptions.auth.unauthorized);
Ой-ёй... Прошу прощения, исправила :)

2024-07-29 10:32 UTC, INextYP approved these changes
Всё хорошо. Дальнейшие улучшения будут дальше :)

2024-07-29 11:40 UTC, kspshnik commented on src/api/system-api/system-api.gateway.ts
>        for (const user of this.connectedUsers.values()) {
А чего не `Object.values(connectedUssers).map((user) => user._id)` ? %)

2024-07-29 11:51 UTC, kspshnik approved these changes
Поехали :)

2024-07-29 11:55 UTC, merged