Изменение permissions у админа (задача #131)
ya-pomogau/backend pull request #134
Opened 2024-07-27 07:08 UTC by IvannaBalanyuk

Добрый день! В рамках задачи выполнено:

- [x] Создание ручки в `AdminApiController`:
// ручка по url `':id/privileges'` обрабатывает PATCH-запрос;
// за основу взята сигнатура ручек PUT и DELETE по тому же url (были в контроллере), но дополнена параметром `@Req() req: Express.Request` для проверки на root;
// декорируется `AccessControlList` аналогично имеющимся ручкам;
// dto использована та же, что применялась в методах ручек PUT и DELETE.

- [x] Создание метода в `UsersService`:
// публичный метод вызывается из контроллера (`AdminApiController`), обращается к репозиторию пользователей;
// заменяет массив привилегий у администратора.

2024-07-27 07:56 UTC, kspshnik requested changes
Всё хорошо, кроме одного: не заменить, а **дополнить** и контроллер, и сервис.

Верни и обе старых ручки в строй, пожалуйста :)

2024-07-27 15:13 UTC, IvannaBalanyuk commented
> Верни и обе старых ручки в строй, пожалуйста :)

Верну, погорячилась) Добавить в старые ручки проверку на root или не надо?

2024-07-27 18:51 UTC, kspshnik commented
> > Верни и обе старых ручки в строй, пожалуйста :)
> 
> 
> 
> Верну, погорячилась) Добавить в старые ручки проверку на root или не надо?


В принципе, можно.

2024-07-28 07:45 UTC, IvannaBalanyuk commented
Вернула в строй ручки PUT и DELETE, дополнила их проверкой на root

2024-07-28 10:30 UTC, kspshnik requested changes
И финальным штрихом - добавим `{ new: true }` к восстановленному :)

2024-07-28 10:30 UTC, kspshnik commented on src/core/users/users.service.ts
>        {}
А как же `{ new: true }`? Мангуст же старую запись так отдаёт.

2024-07-28 10:30 UTC, kspshnik commented on src/core/users/users.service.ts
>        {}
А как же `{ new: true }`? Мангуст же старую запись так отдаёт.

2024-07-28 12:59 UTC, IvannaBalanyuk commented on src/core/users/users.service.ts
>        {}
Добавлю) Так-то в таске не стояло задачи отрефакторить старые методы)))

2024-07-28 15:45 UTC, IvannaBalanyuk commented on src/core/users/users.service.ts
>        {}
Готово=)

2024-07-28 15:45 UTC, IvannaBalanyuk commented on src/core/users/users.service.ts
>        {}
Готово=)

2024-07-28 18:21 UTC, kspshnik approved these changes

2024-07-28 19:03 UTC, INextYP approved these changes
Отлично!

2024-07-28 19:29 UTC, merged