Fix/root admin blog
ya-pomogau/backend pull request #139
Opened 2024-07-28 19:07 UTC by TerSV86

В методе createAdmin класса UserService изменил поле isRoot на true.
В BlogService деструктурировал объект user.
В AccessContorolGuard исключил проверку на наличие поля accessControl.isRoot, т.к. данного поля в accessControl не существует и перенес проверку на наличие прав суперпользователя сразу после получения пользователя из контекста запроса.

2024-07-28 19:26 UTC, kspshnik requested changes
Для решения задачи достаточно **только** _отрефакторить_ гарду. Изменения в сервис пользователей запрещены.

2024-07-28 19:26 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +  @Public() //
УДАЛИТЬ. Недопустимо делать эту ручку публичной.

2024-07-28 19:26 UTC, kspshnik commented on src/common/guards/access-control.guard.ts
> -    if (accessControl.isRoot) {
Нет, это всё должно остаться. Мы проверяем, не суперпользователь ли у нас, если да - можно больше ничего не проверять :)

2024-07-28 19:26 UTC, kspshnik commented on src/core/users/users.service.ts
> +      isRoot: true,
НЕТ. В системе **не должно быть технической возможности** создания суперпользователя.

2024-07-28 19:26 UTC, kspshnik commented on src/datalake/users/users-testcontroller.controller.ts
Этот файл **НЕ ИМЕЕТ ПРАВА НА ЖИЗНЬ И НЕ МОЖЕТ БЫТЬ ИСПОЛЬЗОВАН**

2024-07-30 18:00 UTC, kspshnik submitted a review, later dismissed
Вот теперь супер :)

2024-07-30 18:21 UTC, INextYP requested changes

2024-07-30 18:21 UTC, INextYP commented on src/common/guards/access-control.guard.ts
> +    if (user.role === UserRole.ADMIN && user.isRoot) return true;
А удали плз строчку 37-39 строки, так как они дублируют эту строку

2024-07-31 13:24 UTC, INextYP approved these changes
Всё хорошо. @kspshnik %)

2024-07-31 13:29 UTC, kspshnik approved these changes
Вот теперь точно ОК :)

2024-07-31 13:31 UTC, merged