Feat/change points in active tasks
ya-pomogau/backend pull request #142
Opened 2024-07-29 15:55 UTC by EgorEzhkov

Написал в функции updateCategoryById сервиса categories.service код, добавляющий обновления points для репозитория tasks по id category и активному статусу

2024-07-29 16:38 UTC, INextYP requested changes
Из того, что выявил при тестировании:
1. Необходима Пайпа для валидации @Param-декоратора, иначе всё это добро доходит до БД и крашит запрос, как пример:
![image](https://github.com/user-attachments/assets/2b7edeae-04d8-48ca-8384-7c760d74230f)
2. DTO должен быть классом с декораторами из class-validator библиотеки, иначе никакой валидации мы не получим и можем слать в метод что угодно...
3. DTO должен содержать только поинты, ничего другого нам не нужно изменять...
4. Если у нас запрос на обновление категории пройдет, а на обновление тасок нет, то...?
5. В твоей реализации мы меняем одну категорию, но у нас есть ещё ручка для массового изменения категорий. Было бы здорово и в неё внедрить этот функционал :)

2024-07-29 16:38 UTC, INextYP commented on src/core/categories/categories.service.ts
> +      res = await this.categoriesRepo.findOneAndUpdate({ _id: id }, updateData, { new: false });
Думаю, что `if (!res) throw new NotFoundException(exceptions.category.notFound);` нужно поместить после этой строки чтобы в случае, если категория не найдена - выбрасывалась ошибка, а не выполнялся метод `this.tasksRepo.updateMany`. В таком случае из блока `try` мы вернем `category` и не нужно будет заранее создавать переменную `res`.

Чем вызвано то, что ты указал { new: false }? Нам же нужно вернуть обновленную категорию

2024-07-29 16:38 UTC, INextYP commented on src/core/categories/categories.service.ts
>        throw new InternalServerErrorException(exceptions.category.internalError, {
Эта ошибка возвращает вот что:
![image](https://github.com/user-attachments/assets/3070f6ad-d566-46bb-a69a-0720c7a0f1b5)
Текста из cause в ответе не содержится...

2024-07-29 17:52 UTC, kspshnik commented on src/core/categories/categories.service.ts
>        throw new InternalServerErrorException(exceptions.category.internalError, {
>  Текста из cause в ответе не содержится...

Текст из `cause` не для юзверя, а для _логгера_ жи?
 Он и **не должен** возвращаться, это не бага а фича кмк.

2024-07-29 17:57 UTC, kspshnik requested changes
А попробуй вообще заинжектить `commandBus` и написать команду, которая будет дёргать `TasksService` для обновления поинтов.
Если надо - добавь метод в `TasksService`.

Пример использования посмотри в `AuthApi`/`AuthService`, его уже перевели на CQRS.

2024-07-29 17:57 UTC, kspshnik commented on src/core/categories/categories.module.ts
> +import { TasksRepositoryModule } from 'src/datalake/task/tasks-repository.module';
Нет. Работаем через **сервис**.

2024-08-07 06:44 UTC, kspshnik requested changes
Почти всё супер! Осталось один моментик исправить тут :)

И классно было бы проверить работоспособность, хотя бы в Postman/Insomnia, если вдруг не тестировал пока :)

2024-08-07 06:44 UTC, kspshnik commented on src/core/tasks/tasks.service.ts
> +      { 'category._id': id, status: { $in: [TaskStatus.ACCEPTED, TaskStatus.CREATED] } },
А конфликтные? Они **не закрыты**.

2024-09-02 10:58 UTC, Sapodsoblyaeva commented
В постмане протестировала

2024-09-03 17:20 UTC, INextYP commented
Привет, исправь пожалуйста конфликты

2024-09-04 07:22 UTC, Sapodsoblyaeva commented
Вроде исправила.

2024-09-14 17:29 UTC, INextYP approved these changes

2024-09-14 20:20 UTC, kspshnik requested changes
Избавиться от чужого репозитория в зависимостях/конструкторе, пишем _запрос/команду_, в запросе/команде работаем **с сервисом**.

2024-09-14 20:20 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +    private readonly tasksRepo: TasksRepository
Мы **НЕ ИМПОРТИРУЕМ ЧУЖИЕ РЕПОЗИТОРИИ!!!!!**

2024-09-17 11:23 UTC, Sapodsoblyaeva commented on src/core/categories/categories.service.ts
> +    private readonly tasksRepo: TasksRepository
Я честно не вижу, где этот код, там же на команд бас все заменено?   
  constructor(
    private readonly categoriesRepo: CategoryRepository,
    // private readonly tasksService: TasksService,
    private readonly commandBus: CommandBus
  ) {}

2024-09-18 16:14 UTC, kspshnik approved these changes
Oooop, это моя дефектура.

2024-09-18 17:27 UTC, INextYP approved these changes
@kspshnik мёржим!? %)

2024-09-19 09:40 UTC, merged