Correct updates of discriminated collection
ya-pomogau/backend pull request #147
Opened 2024-08-02 12:19 UTC by TerSV86

2024-08-02 14:07 UTC, kspshnik requested changes
Всё хорошо, только одно замечание в шести местах :)

2024-08-02 14:07 UTC, kspshnik commented on src/core/users/users.service.ts
>              {}
Имеет смысл добавить `new: true` в объект опций, сейчас будет возвращать _старую_ запись.

2024-08-02 14:07 UTC, kspshnik commented on src/core/users/users.service.ts
> +        return this.usersRepo.findOneAndUpdate({ _id, role }, { status: status + 1 }, {});
Имеет смысл добавить `new: true` в объект опций, сейчас будет возвращать _старую_ запись.

2024-08-02 14:07 UTC, kspshnik commented on src/core/users/users.service.ts
> +        return this.usersRepo.findOneAndUpdate({ _id, role }, { status: status - 1 }, {});
Имеет смысл добавить `new: true` в объект опций, сейчас будет возвращать _старую_ запись.

2024-08-02 14:07 UTC, kspshnik commented on src/core/users/users.service.ts
> +      return this.usersRepo.findOneAndUpdate({ _id, role }, { keys: true }, {});
Имеет смысл добавить `new: true` в объект опций, сейчас будет возвращать _старую_ запись.

2024-08-02 14:07 UTC, kspshnik commented on src/core/users/users.service.ts
> +      return this.usersRepo.findOneAndUpdate({ _id, role }, { keys: false }, {});
Имеет смысл добавить `new: true` в объект опций, сейчас будет возвращать _старую_ запись.

2024-08-02 14:07 UTC, kspshnik commented on src/core/users/users.service.ts
> +      return this.usersRepo.findOneAndUpdate({ _id, role }, { status: UserStatus.BLOCKED }, {});
Имеет смысл добавить `new: true` в объект опций, сейчас будет возвращать _старую_ запись.

2024-08-03 07:12 UTC, kspshnik approved these changes
Теперь ОК по коду.

2024-08-04 19:26 UTC, INextYP approved these changes

2024-08-04 20:04 UTC, merged