Создание ручки получения всех задач произвольного пользователя для AdminApi (задача 155)
ya-pomogau/backend pull request #159
Opened 2024-08-13 17:03 UTC by IvannaBalanyuk

Создала ручку получения всех задач произвольного пользователя (`GET /users/:id/tasks`) в фасаде администраторов (`AdminApiController`).
Использовала метод сервиса пользователей (`UsersService.getProfile(...)`) для получения пользователя по id и метод сервиса задач (`TasksService.getOwnTasks(...)`) для получения задач пользователя по статусу задачи. 
Для декоратора контроля доступа (`@AccessControlList()`) указала требование роли: `role: UserRole.ADMIN`.

- [x] Указан декоратор HTTP-метода с корректным путём.
- [x] Указан декоратор контроля доступа, установлено требование роли администратора.
- [x] В аргументы (параметры) метода - обработчика ручки получен параметр url.
- [x] Возвращается результат вызова соответствующего метода сервиса пользователей.

2024-08-15 12:38 UTC, kspshnik requested changes
Хорошо, но лучше не последовательно, а параллельно.

И @INextYP - нам тут нужны _закрытые_ задачи или таки нет?

2024-08-15 12:38 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +    return Promise.resolve([...created, ...accepted, ...completed, ...conflicted]);
А зачем так сложно и поочерёдно?
Воспользуйся `Promise.all()`.

2024-08-16 09:08 UTC, INextYP commented
> Хорошо, но лучше не последовательно, а параллельно.
> 
> И @INextYP - нам тут нужны _закрытые_ задачи или таки нет?

В дизайне это не отражено, но как фичу я бы оставил. Раз заказчик хочет мониторить переписки даже в закрытых тасках

2024-08-16 10:11 UTC, IvannaBalanyuk commented on src/api/admin-api/admin-api.controller.ts
> +    return Promise.resolve([...created, ...accepted, ...completed, ...conflicted]);
Готово

2024-08-16 10:36 UTC, kspshnik requested changes
Ошибки почти так :)
Ну и зачем усложнять?

2024-08-16 10:36 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +    const user = await this.usersService.getProfile(_id).catch((err) => {
А если другая ошибка?? Может, `.orFail(new NotFoundException(`Пользователь с _id '${_id}' не найден: ${err.message}`, { cause: ... });` ?

Проверь по `BaseRepositoryService`, _что_ _именно_ возвращается. Если там всякие `POJO<...>` с `toObject()` - убери нафик, но проверь что нигде не отвалится больше  :)

2024-08-16 10:36 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +      throw new InternalServerErrorException(err.message);
Неплохо бы `cause` написать с `err`, а на клиента просто `'Внутренняя ошибка сервера'` отдать, не надо ему голову деталями морочить :)

2024-08-16 10:36 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +    results.forEach((arr) => {
А просто `return Promise.all(...).reduce(...)`, не? :)

2024-08-16 10:37 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +    const user = await this.usersService.getProfile(_id).catch((err) => {
Работу с `BaseRepositoryService` лучше отдельным issue и отдельным же PR, кстати.

2024-08-16 10:38 UTC, gvozdenkov reviewed
Оптимизацию предложил

2024-08-16 10:38 UTC, gvozdenkov commented on src/api/admin-api/admin-api.controller.ts
> +    return Promise.resolve(tasks);
@IvannaBalanyuk Кажется, так проще сделать плоский массив из многомерного %)

```js
return Promise.resolve(results.flat());
```

2024-08-16 10:39 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +    return Promise.resolve(tasks);
Я бы тупо через `return Promise.all().reduce()` подумал, чтобы не разводить мешки чебурашек :)

2024-08-16 11:15 UTC, IvannaBalanyuk commented on src/api/admin-api/admin-api.controller.ts
> +    const user = await this.usersService.getProfile(_id).catch((err) => {
Согласна, погорячилась) Забыла, что это метод контроллера и лучше на уровне сервиса решать.
В `usersService.getProfile(...)` сейчас никакой обработки ошибок нет:
![image](https://github.com/user-attachments/assets/8ec25789-009a-4ddb-a006-4a9723373612)

Т.е. если БД ругнулась, то в постман приходит стандартная пятисотая ошибка. Фронту сложновато будет понять в чем проблема и куда копать.

Посмотрела `BaseRepositoryService`. На мой взгляд тут всё нормально:
![image](https://github.com/user-attachments/assets/3f0088e9-f95b-4e86-b6fc-7ed0b2626f6c)

2024-08-16 11:18 UTC, IvannaBalanyuk commented on src/api/admin-api/admin-api.controller.ts
> +      throw new InternalServerErrorException(err.message);
Согласна, но кмк это лучше в сервисе реализовать. Пожалуй, тоже лучше отдельным issue и отдельным же PR?

2024-08-16 11:21 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +    const user = await this.usersService.getProfile(_id).catch((err) => {
> Согласна, погорячилась) Забыла, что это метод контроллера и лучше на уровне сервиса решать. В `usersService.getProfile(...)` сейчас никакой обработки ошибок нет: 

Да, лучше тут `orFail()` добавлять.

> Т.е. если БД ругнулась, то в постман приходит стандартная пятисотая ошибка. Фронту сложновато будет понять в чем проблема и куда копать.

Это делается по-другому в Nest.js - надо интерсепторы писать.


> 
> Посмотрела `BaseRepositoryService`. На мой взгляд тут всё нормально: 

Ага, похоже.

2024-08-16 11:22 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +      throw new InternalServerErrorException(err.message);
> Согласна, но кмк это лучше в сервисе реализовать. Пожалуй, тоже лучше отдельным issue и отдельным же PR?

💯 Да, ты права. Создавай и самоназначайся :)

А тут пока на паузу поставим.

2024-08-16 11:51 UTC, IvannaBalanyuk commented on src/api/admin-api/admin-api.controller.ts
> +    results.forEach((arr) => {
Прям в таком виде не выходит, применила reduce к results)

2024-08-16 11:52 UTC, IvannaBalanyuk commented on src/api/admin-api/admin-api.controller.ts
> +    return Promise.resolve(tasks);
Благодарствую, применила)

2024-08-16 11:53 UTC, IvannaBalanyuk commented on src/api/admin-api/admin-api.controller.ts
> +      throw new InternalServerErrorException(err.message);
Ок, пошла ваять issues =)

2024-08-19 10:29 UTC, gvozdenkov commented on src/api/admin-api/admin-api.controller.ts
> +    return Promise.resolve(results.reduce((arr, resArr) => [...arr, ...resArr], []));
@IvannaBalanyuk @kspshnik А зачем редьсер то заводить, чтобы схлопнуть массив? функция `results.flat()` чем не? %)

2024-08-19 11:30 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +    return Promise.resolve(results.reduce((arr, resArr) => [...arr, ...resArr], []));
Да, можно так :)

2024-08-19 11:31 UTC, kspshnik submitted a review, later dismissed
Вполне себе. Оттестировать бы?

2024-08-19 12:01 UTC, IvannaBalanyuk commented
В этой же ветке или отдельной задачкой?🙂

2024-08-19 12:02 UTC, IvannaBalanyuk commented
> Вполне себе. Оттестировать бы?

В этой же ветке или отдельную задачу сформировать?🙂

2024-08-19 13:52 UTC, kspshnik commented
> Вполне себе. Оттестировать бы?
> 
> В этой же ветке или отдельную задачу сформировать?🙂
> 

Думаю, можно прямо тут :)

2024-08-29 12:53 UTC, kspshnik approved these changes
Отлично!

2024-08-29 18:29 UTC, INextYP approved these changes
Всё хорошо. 
Единственное, в качестве TODO я бы переписал момент с получением тасок из БД. Вместо 5 запросов, которые мы делаем можно написать одну агрегацию, которая вернёт таски пользователя сгруппированные по статусам

2024-08-29 19:18 UTC, merged