Реализация отправки токена по сокету
ya-pomogau/backend pull request #162
Opened 2024-08-21 13:01 UTC by IvannaBalanyuk

В рамках задачи реализовала отправку токена на клиент через сокет в случае, если в профиль пользователя внесены изменения:

- [x] В `SystemApiGateway` добавила хэндлер  `sendToken(user: Recipient | Admin | Volunteer | Record<string, unknown>, token: string) {...}` для отправки токена пользователя на клиент. Отправку необходимо осуществлять только в случае, если пользователь подключен (проверить есть ли пользователь в `connectedUsers`).
- [x] Написала команду `SendTokenCommand` и хэндлер `SendTokenHandler`.
- [x] В сервис `UsersService` внедрила `СommandBus` из `nestjs/cqrs`.
- [x] Во все методы сервиса `UsersService`, меняющие статус пользователя, добавила вызов команд из `СommandBus`:
- `this.commandBus.execute(new AuthenticateCommand(user))` - для получения нового токена;
- `this.commandBus.execute(new SendTokenCommand(user, token))` - для отправки нового токена по сокету.
- [x] Проверила через постман все методы, в которые внесены изменения.

![image](https://github.com/user-attachments/assets/1f19a769-06a2-4ca7-8b14-152d92a45c8c)

2024-08-21 13:18 UTC, INextYP requested changes

2024-08-21 13:18 UTC, INextYP commented on src/api/system-api/system-api.gateway.ts
> +  sendToken(user: Recipient | Admin | Volunteer | Record<string, unknown>, token: string) {
`Recipient | Admin | Volunteer | Record<string, unknown>` - давайте что-то с этим ужасом сделаем. Повторяется повсеместно

2024-08-21 13:23 UTC, INextYP requested changes

2024-08-21 13:23 UTC, INextYP commented on src/api/system-api/system-api.gateway.ts
> +    this.connectedUsers.forEach((value, key, map) => {
this.connectedUsers - это МАПА, т.е. объект. Нет смысла проъодить по всему объекту. Есть у map метод .has

```
const client = this.connectedUsers.has(user._id)

if(client) { отправляем токен }
```

2024-08-21 13:25 UTC, INextYP requested changes

2024-08-21 13:25 UTC, INextYP commented on src/api/system-api/system-api.gateway.ts
> +  sendToken(user: Recipient | Admin | Volunteer | Record<string, unknown>, token: string) {
Или 2-й момент - а есть ли смысл всего юзера передавать, если нам нужен его айдишник?

2024-08-21 13:27 UTC, INextYP requested changes

2024-08-21 13:27 UTC, INextYP commented on src/core/users/users.service.ts
> +          if (updatedUser) {
Мб эту контрукцию вынесем в приватный метод? Уж очень часто она тут повторяется

2024-08-21 13:32 UTC, IvannaBalanyuk commented on src/api/system-api/system-api.gateway.ts
> +    this.connectedUsers.forEach((value, key, map) => {
@INextYP Да, но `has()` ищет по ключу, а в качестве ключа у нас как раз искомый `client.id`. Хотела перекроить Map: вынести, к примеру, `user._id` в ключ. Но тогда будет неудобно в тех случаях, когда у нас есть client.id и нужно что-либо сделать с соответствующим элементом коллекции. Поэтому пока оставила так.

2024-08-21 13:34 UTC, IvannaBalanyuk commented on src/api/system-api/system-api.gateway.ts
> +  sendToken(user: Recipient | Admin | Volunteer | Record<string, unknown>, token: string) {
Заменить на AnyUserInterface?)

2024-08-21 13:36 UTC, IvannaBalanyuk commented on src/api/system-api/system-api.gateway.ts
> +  sendToken(user: Recipient | Admin | Volunteer | Record<string, unknown>, token: string) {
Пожалуй, нет) Тут я слепо пошла по инструкции, не обдумала

2024-08-21 13:39 UTC, IvannaBalanyuk commented on src/core/users/users.service.ts
> +          if (updatedUser) {
`refreshAndSendToken(user)` - норм название для метода или ещё подумать? :)

2024-08-21 13:55 UTC, kspshnik requested changes
Отличная и очень важная работа!
Думаю, к QA точно будет бегать/прыгать :)

2024-08-21 13:55 UTC, kspshnik commented on src/api/system-api/system-api.gateway.ts
> +  sendToken(user: Recipient | Admin | Volunteer | Record<string, unknown>, token: string) {
> Заменить на AnyUserInterface?)

Хотел это написать :)

2024-08-21 13:55 UTC, kspshnik commented on src/api/system-api/system-api.gateway.ts
> +  sendToken(user: Recipient | Admin | Volunteer | Record<string, unknown>, token: string) {
> Пожалуй, нет) Тут я слепо пошла по инструкции, не обдумала

Если в мапе подключённых пользуется `_id`, то можно целиком не гонять.

2024-08-21 13:55 UTC, kspshnik commented on src/api/system-api/system-api.gateway.ts
> +    this.connectedUsers.forEach((value, key, map) => {
А в каких случаях нам надо искать по `client.id`? Чтобы что сделать?

2024-08-21 13:55 UTC, kspshnik commented on src/api/system-api/system-api.gateway.ts
> +          message: `The user's status has changed. The token must be replaced.`,
Стоп. Нинада тут человекочитаемости. 
`data` должен быть типа 
```ts
export type wsMessage = {
  kind: wsMessageKind;
  payload: wsPayloadType;
};
```

(см. [`src/common/types/websockets.types.ts`](https://github.com/ya-pomogau/backend/blob/development/src/common/types/websockets.types.ts))

2024-08-21 13:55 UTC, kspshnik commented on src/core/users/users.module.ts
> +  providers: [...COMMANDS, UsersService, HashService, AuthService, SystemApiGateway],
Подскажи, а гейтвей здесь Nest требует?

2024-08-21 13:57 UTC, IvannaBalanyuk commented on src/api/system-api/system-api.gateway.ts
> +    this.connectedUsers.forEach((value, key, map) => {
Пока только в случае удаления элемента из коллекции при дисконнекте. Когда комнаты будем организовывать, то там скорее user.id везде нужен будет.

2024-08-21 13:59 UTC, kspshnik commented on src/api/system-api/system-api.gateway.ts
> +    this.connectedUsers.forEach((value, key, map) => {
> Пока только в случае удаления элемента из коллекции при дисконнекте.

А что будет чаще: убрать по дисконнекту или найти по `_id`, как ты думаешь? 
@INextYP а ты что скажешь?

2024-08-21 14:01 UTC, IvannaBalanyuk commented on src/core/users/users.module.ts
> +  providers: [...COMMANDS, UsersService, HashService, AuthService, SystemApiGateway],
Требует. Я его сначала в импорты добавила, но линтер ругается на циклическую зависимость (можно, конечно, отключить для строки). Перенесла в провайдеры. Несу обратно в импорты?)

2024-08-21 14:04 UTC, kspshnik commented on src/core/users/users.module.ts
> +  providers: [...COMMANDS, UsersService, HashService, AuthService, SystemApiGateway],
Нененене. Нинада.
А если аще убрать - ругаться что не разрешить зависимость?

2024-08-21 14:32 UTC, IvannaBalanyuk commented on src/api/system-api/system-api.gateway.ts
> +    this.connectedUsers.forEach((value, key, map) => {
Пока у нас в планах на этот гейтвей:
- коннект: `_id` если отправка `participants` останется, если нет - то, вроде, всё равно;
- мета-данные: без разницы, там у нас `client` будет, так как место действия - обработчик коннекта;
- токен: `_id`;
- дисконнект: `client`.id.
Пока лидирует `_id` )

2024-08-21 14:38 UTC, IvannaBalanyuk commented on src/core/users/users.module.ts
> +  providers: [...COMMANDS, UsersService, HashService, AuthService, SystemApiGateway],
Аха) Ругается и не заводится

2024-08-21 15:31 UTC, IvannaBalanyuk commented on src/api/system-api/system-api.gateway.ts
> +    this.connectedUsers.forEach((value, key, map) => {
Хм... хотя мета-данные мы же тоже будем отправлять по мере их изменения? В этом методе тоже будет удобнее с `_id`

2024-08-21 20:46 UTC, IvannaBalanyuk commented
@INextYP @kspshnik Внесла правки:

- Перекроила мапу, отредактировала и дополнила её использование. Думаю, что раз пользователь может зайти одновременно с разных устройств, то для каждого пользователя нужно сохранять массив сокетов, чтобы можно было сделать отправку на все устройства.
- Добавила в `.env.example`  и, соответственно, в `.env` порт для ws, указала его в gateway.
- В `UsersService` вынесла повторяющийся фрагмент в приватный метод + скорректировала типизацию, применив `AnyUserInterface`. Также заменила на `AnyUserInterface` типизацию в `AuthenticateCommand`.

2024-08-21 20:55 UTC, kspshnik requested changes
Отлично! Осталось несколько штрихов буквально :)

2024-08-21 20:55 UTC, kspshnik commented on src/api/system-api/system-api.gateway.ts
> +          data: message,
Мне кажется, тут можно просто `data: { userId, token }`.

Но, кстати, вот **именно тут** лучше _всего_ пользователя заслать, чтобы на фронте изменились статус/полномочия, и можно было бы использовать логику логина :)

2024-08-21 20:55 UTC, kspshnik commented on src/api/system-api/system-api.gateway.ts
> +      data: { message: 'Hello!', participants: Array.from(this.connectedUsers.keys()) },
Наверное, на текущем этапе можно ни это ни стр.93 не рассылать уже, достаточно просто консолей :)

2024-08-21 20:55 UTC, kspshnik commented on src/api/system-api/system-api.gateway.ts
> +        message: `Hello, world! ${user?.name || client.id} has dropped connection recently!`,
И для этого лучше свой тип сообщения завести.

2024-08-21 20:55 UTC, kspshnik commented on src/api/system-api/system-api.gateway.ts
>    sendToken(userId: string, token: string) {
И всё-таки нужен _полный_ юзверь. Заодно и в мапе его обновить :)

2024-08-22 08:32 UTC, IvannaBalanyuk commented on src/api/system-api/system-api.gateway.ts
> +          data: message,
- [x] поправила интерфейс, включая отправку всего пользователя

2024-08-22 08:33 UTC, IvannaBalanyuk commented on src/api/system-api/system-api.gateway.ts
> +      data: { message: 'Hello!', participants: Array.from(this.connectedUsers.keys()) },
- [x] убрала неактуальные рассылки

2024-08-22 08:35 UTC, IvannaBalanyuk commented on src/api/system-api/system-api.gateway.ts
> +        message: `Hello, world! ${user?.name || client.id} has dropped connection recently!`,
- [x] завела отдельный тип, включила туда пока только айдишник юзера.

2024-08-22 08:37 UTC, IvannaBalanyuk commented on src/api/system-api/system-api.gateway.ts
>    sendToken(userId: string, token: string) {
- [x] заменила пропс на полного юзера)
- [x] добавила обновление объекта пользователя в мапе и отправку его на клиент.

2024-08-22 09:20 UTC, kspshnik commented on src/api/auth-api/auth-api.controller.ts
> +        new AuthenticateCommand(req.user as AnyUserInterface)
Это место протестировано? Я помню, что там типизация ломалась по дороге где-то :(

2024-08-22 09:28 UTC, kspshnik submitted a review, later dismissed
Во, супер :)

Кстати, мысль дурацкая: а может не слать это всё в пейлоаде, а тупо на стороне фронта по получению команды выполнять стандартный логин?

2024-08-22 09:28 UTC, kspshnik commented on src/core/users/users.service.ts
>            UsersService.requireLogin(_id);
Когда заработает в комплексе (на обновление будет уходить сообщение по сокету), все эти `requireLogin()` и прочую обвязку можно и нужно грохнуть :)

2024-08-22 09:42 UTC, IvannaBalanyuk commented on src/api/auth-api/auth-api.controller.ts
> +        new AuthenticateCommand(req.user as AnyUserInterface)
Прям прицельно и с разными кейсами - нет. Но при проверке методов `UsersService` я каждый раз предварительно логинилась под рутом (как раз через эту ручку) - всякий раз успешно. Отмечу себе, протестирую. Не помнишь в каком именно случае ломалось?

2024-08-22 09:45 UTC, IvannaBalanyuk commented on src/core/users/users.service.ts
>            UsersService.requireLogin(_id);
Аха, это я держу в уме) Но уже уяснила, что раньше времени (без явно выраженной команды) ничего сносить не стоит :)))

2024-08-22 10:02 UTC, IvannaBalanyuk commented
> Во, супер :)
> 
> Кстати, мысль дурацкая: а может не слать это всё в пейлоаде, а тупо на стороне фронта по получению команды выполнять стандартный логин?

Вот не знаю. Пока, после беглой оценки, мне видится, что проще задиспатчить соответствующий action:
![image](https://github.com/user-attachments/assets/ae966fbf-40aa-4039-906b-4e01687cb015)

По образу и подобию этого:
![image](https://github.com/user-attachments/assets/66f962fc-5e9a-4806-bf07-255210d3a68a)

А с инициацией стандартного логина - надо ещё выбрать метод в зависимости от роли, каким-то образом dto-шки для них сформировать:
![image](https://github.com/user-attachments/assets/68025064-248b-46d8-a108-cd3fc1367db8)
![image](https://github.com/user-attachments/assets/edb1a475-99fc-4156-bc98-fa14af880374)
Сложновато)

2024-08-23 11:10 UTC, IvannaBalanyuk commented
@INextYP  @kspshnik 
Нашла из-за чего не проходила авторизация с токеном, засланным по сокету :dizzy_face:

Вызов метода `requireLogin(_id)` в тех методах, что меняют статус пользователя, приводил к тому, что метод  `validate` в `JwtStrategy` выбрасывал `null`:

![image](https://github.com/user-attachments/assets/026e0873-02bf-4ccb-88a8-0531cb62a3d4)

Убрала во всех методах, в которые ранее добавила отправку по сокету.

2024-08-25 14:37 UTC, INextYP approved these changes

2024-08-25 14:56 UTC, kspshnik approved these changes
Супер!

2024-08-27 17:34 UTC, merged