добавляет описание ручек auth в swagger
ya-pomogau/backend pull request #172
Opened 2024-09-10 06:58 UTC by AlexeyEfimov85

2024-09-10 11:47 UTC, kspshnik requested changes
Супер, очень хорошо.
Единственное - тип тела запроса для авторизации админа указан некорректно. Там обрабатывается логин с помощью `AdminLoginAuthGuard()`, это стандартный 'LocalAuthGuard' - поля не перенастраивались, вспомни какой был `dto` для авторизации по паролю в "КупиПодариДай!", здесь абсолютно такой же.

2024-09-10 11:47 UTC, kspshnik commented on src/api/auth-api/auth-api.controller.ts
> +  @ApiBody({ type: MockLoginDto })
А точно здесь _Mock_ ?

2024-09-10 17:20 UTC, AlexeyEfimov85 commented on src/api/auth-api/auth-api.controller.ts
> +  @ApiBody({ type: MockLoginDto })
сделал коммит с исправлением, но пришлось и код контроллера изменить

2024-09-10 17:27 UTC, kspshnik requested changes
Не нужно менять метод `administrative()`, после гарды там уже в объекте запроса есть пользователь. А если логин/пароль не соответствуют - до сюда запрос тупо не дойдёт.

Возможно, здесь вообще не нужна валидация? @INextYP, что скажешь?

2024-09-10 17:27 UTC, kspshnik commented on src/api/auth-api/auth-api.controller.ts
> +  async administrative(@Body() dto: AdminLoginDto) {
Откатываем назад. Это делает `AdminLoginAuthGuard()`, и добавляет объект пользователя в запрос.

2024-09-10 19:04 UTC, AlexeyEfimov85 commented on src/api/auth-api/auth-api.controller.ts
> +  async administrative(@Body() dto: AdminLoginDto) {
Откатил изменения в контроллере, но декоратор Apibody оставил - чтобы в swagger светился формат Request body

2024-09-10 19:57 UTC, kspshnik submitted a review, later dismissed
Вот теперь всё ОК :)

Ждём ревью @INextYP

2024-09-12 06:58 UTC, INextYP requested changes

2024-09-12 06:58 UTC, INextYP commented on src/api/auth-api/auth-api.controller.ts
>  @Controller('auth')
Перед контроллером нужно поставить ещё один декоратор `@ApiTags('Auth')` для того, чтобы у группы ручек было сгруппированное название:

![image](https://github.com/user-attachments/assets/55eaa8d7-f638-4427-b93c-da5e84004319)

2024-09-12 06:58 UTC, INextYP commented on src/api/auth-api/auth-api.controller.ts
> +}; */
Убираем комментарии сразу

2024-09-12 06:58 UTC, INextYP commented on src/api/auth-api/auth-api.controller.ts
> +  @ApiUnauthorizedResponse({ description: 'Неверное имя пользователя или пароль' })
Разве у нас при ошибке возвращается строка? @kspshnik

2024-09-12 06:58 UTC, INextYP commented on src/api/auth-api/auth-api.controller.ts
>    @HttpCode(HTTP_STATUS_OK)
Явно не хватает `ApiBadRequestResponse`, ведь у нас же может случиться ошибка валидации?

2024-09-12 06:58 UTC, INextYP commented on src/api/auth-api/auth-api.controller.ts
> +    type: AnswerOkDto,
На текущий момент эта DTO не отображается в полном виде в сваггере. Мы должны видеть: вложенные объекты, Enum перечисления

2024-09-12 06:58 UTC, INextYP commented on src/api/auth-api/auth-api.controller.ts
> +  @ApiBody({ type: VKNewUserDto })
Аналогично комментариям выше, про вложенные сущности

2024-09-12 06:58 UTC, INextYP commented on src/api/auth-api/auth-api.controller.ts
> +  @ApiBadRequestResponse({ description: 'Произошла ошибка' })
Возможно даже стоит (если ещё нету) создать типизацию для ошибки @kspshnik и использовать как type возвращаемого значения

2024-09-13 11:57 UTC, kspshnik commented on src/api/auth-api/auth-api.controller.ts
> +  @ApiBadRequestResponse({ description: 'Произошла ошибка' })
Ошибку вернёт стандартный Validation Pipe от Nest-а. 
Где-то в нём уже должна быть типизация :)

2024-09-13 12:00 UTC, kspshnik requested changes
Как-то дублирование схемы Swagger напрягает. Хорошо бы её вынести :)

2024-09-13 12:00 UTC, kspshnik commented on src/api/auth-api/auth-api.controller.ts
> +    schema: {
А эту схему никак нельзя вынести?

2024-11-14 07:40 UTC, kspshnik requested changes
`AdminDto` для Swagger не совсем корректно описана, остальное ОК.

2024-11-14 07:40 UTC, kspshnik commented on src/common/dto/api.dto.ts
> +    example: 'CONFIRM_USER',
Это **массив** со _всеми_ правами конкретного администратора.

2024-11-14 07:40 UTC, kspshnik commented on src/common/dto/api.dto.ts
> +    enum: ['Admin', 'Recipient', 'Volunteer', 'GeneralUser'],
Это админское dto, тут может быть **только** `enum: ['Admin']` ;o)

2024-11-15 17:28 UTC, kspshnik approved these changes
ОК. Спасибо!
@INextYP, твоя очередь :))

2024-11-16 12:26 UTC, INextYP approved these changes
@AlexeyEfimov85 Отличная работа.

Важно помнить, что когда ты описываешь документацию, ты описываешь её не для себя, а для других разработчиков, которые чаще всего не понимают в бэкенд части. И чем подробнее ты всё опишешь, тем меньше к тебе будет потом вопросов :)

2024-11-16 12:38 UTC, merged