feat: add getProfile processing errors
ya-pomogau/backend pull request #173
Opened 2024-09-10 10:35 UTC by anna-vetyugova

Добавить обработку ошибок в метод обновления профиля getProfile (UsersService)

сделала через try-catch, с orFail возникли трудности из-за ошибки Свойство "orFail" не существует в типе "Promise<User>", не разобралась, как это можно обойти

2024-09-10 11:52 UTC, kspshnik submitted a review, later dismissed
ОК :)

2024-09-12 07:02 UTC, INextYP requested changes

2024-09-12 07:02 UTC, INextYP commented on docker-compose.dev.yml
Зачем менять этот файл?

2024-09-19 14:37 UTC, INextYP requested changes

2024-09-19 14:37 UTC, INextYP commented on docker-compose.dev.yml
@anna-vetyugova  верни файл в исходное положение :(

2024-09-20 12:06 UTC, anna-vetyugova commented
@INextYP готово

2024-09-20 17:24 UTC, kspshnik approved these changes
ОК :)

2024-09-21 19:36 UTC, INextYP approved these changes

2024-09-21 19:56 UTC, merged