refactor added aggregate method
ya-pomogau/backend pull request #176
Opened 2024-09-10 14:44 UTC by Sapodsoblyaeva

Добавила метод aggregate

2024-09-10 14:46 UTC, kspshnik submitted a review, later dismissed
Отл. :)

2024-09-12 06:29 UTC, INextYP requested changes
Хорошо, но типизацию нужно добить)

2024-09-12 06:29 UTC, INextYP commented on src/datalake/base-repository/base-repository.service.ts
> +    options?: Record<string, unknown>
`Options` типизируются как `AggregateOptions`

2024-09-12 06:29 UTC, INextYP commented on src/datalake/base-repository/base-repository.service.ts
> +  ): Promise<Array<Record<string, unknown>>> {
Так будет непонятно, что возвращает этот метод. Посмотри в декларациях типа, что возвращает этот метод и обёрни это в `Promise<>`. Букву `T` из дженериков `BaseRepositoryService`  можно также передать  в этот метод

2024-09-12 09:34 UTC, IvannaBalanyuk approved these changes

2024-09-12 10:55 UTC, kspshnik approved these changes
Теперь вообще прекрасно :)

2024-09-12 11:07 UTC, INextYP approved these changes
Отлично!)

2024-09-12 11:18 UTC, merged