Create mock ChatService
ya-pomogau/backend pull request #177
Opened 2024-09-10 20:36 UTC by zoomkolol

2024-09-10 21:02 UTC, kspshnik requested changes
В общем, типы возврата не соответствуют. Надо отдавать то, что отдал бы реальный сервис :)

2024-09-10 21:02 UTC, kspshnik commented on src/core/chat/chats.service.ts
> +    _id: mockObjectId as any,
Пачиму `any`? По-другому не типизируется никак? :)

2024-09-10 21:02 UTC, kspshnik commented on src/core/chat/chats.service.ts
> +    return mockResponseMessage;
Тут надо метаданные возвращать

2024-09-10 21:02 UTC, kspshnik commented on src/core/chat/chats.service.ts
> +    return mockResponseMessage;
Аналогично метаданные

2024-09-10 21:02 UTC, kspshnik commented on src/core/chat/chats.service.ts
> +  async addMessage(chatId: ObjectId, message: MessageInterface): Promise<wsMessageData> {
Аналогично метаданные

2024-09-10 21:27 UTC, zoomkolol commented on src/core/chat/chats.service.ts
> +    _id: mockObjectId as any,
Если сделать просто через new ObjectId(), то он ругается, что тип-то тот, но ему кучи параметров не хватает из него.

В целом, он создаёт ObjectId, но без any придётся ещё городить кучу всего в Моке (+ подсмотрел как в тесте Энтити были сделаны моки MessageInterface — аналогично кастуется as any).

2024-09-10 21:36 UTC, zoomkolol commented on src/core/chat/chats.service.ts
> +    _id: mockObjectId as any,
Отбой, я не знаю почему, но оно заработало 😅

2024-09-10 23:11 UTC, zoomkolol commented on src/core/chat/chats.service.ts
> +    _id: mockObjectId as any,
В общем, я порылся по документации и понять не могу, правильно ли у нас в ChatTypes экспортирован ObjectId?

Если заменить экспорт в ChatTypes из mongodb, то я могу в сервисе сделать моки через  `new mongoose.Types.ObjectId`, как и советуют в подсказке: `The Mongoose ObjectId SchemaType. Used for declaring paths in your schema that should be MongoDB ObjectIds. Do not use this to create a new ObjectId instance, use mongoose.Types.ObjectId instead.`

2024-09-13 12:42 UTC, kspshnik submitted a review, later dismissed
Highly likely, на первой же итерации надо будет поменять в аргументах методов `ObjectId` на `string` (или затипизировать строже через регулярку), но для старта норм :)

2024-09-13 16:01 UTC, IvannaBalanyuk reviewed
По реализованным мокам - вопросов нет)
Присоединяюсь к комментарию про ObjectId.

@kspshnik Могу я сейчас попросить добавить пару методов? Понимаю, что не совсем корректно сформулировала задачу, но исходила из того, что сначала в работу пойдет задача на написание интерфейса (в ней я эти методы добавила).
Для сокета сейчас в первую очередь нужны эти методы:
-  getUserChatsMeta(userId: string | ObjectId) {...}
-  getMessages(chatId: string | ObjectId, skip: number, limit?: number) {...}

2024-09-18 16:03 UTC, kspshnik commented on src/core/chat/chats.service.ts
> +    attaches: ['Hi there!', 'Hi there!'],
Аттачи - это _файлы_ :)

2024-09-18 16:05 UTC, kspshnik requested changes
Мелкие замечания поправь, так всё ОК :)

2024-09-18 16:05 UTC, kspshnik commented on src/core/chat/chats.service.ts
> +  watermark: 'volunteerWatermark',
А watermark должен быть  `mongoobjectId`, это ссылка на последнее прочитанное сообщение в чатике :)

2024-09-20 05:28 UTC, kspshnik approved these changes

2024-09-21 17:55 UTC, INextYP approved these changes

2024-09-21 18:24 UTC, IvannaBalanyuk approved these changes

2024-09-21 18:48 UTC, merged