Feat/swagger recipient api
ya-pomogau/backend pull request #180
Opened 2024-09-12 20:00 UTC by AlexeyEfimov85

2024-09-13 12:02 UTC, kspshnik requested changes
Хорошо, но попробуй вынести схему ошибки.

2024-09-13 12:02 UTC, kspshnik commented on src/api/recipient-api/recipient-api.controller.ts
> +  @ApiBadRequestResponse({
Аналогично другому PR вопрос про вынесение схемы ошибки.

2024-09-18 16:00 UTC, kspshnik requested changes
Очень хорошо, но 403 непонятно: какой другой статус?

2024-09-18 16:00 UTC, kspshnik commented on src/api/recipient-api/recipient-api.controller.ts
> +    schema: schema(['string'], 'Bad Request', 400),
Здорово бы рассказать, что именно не так

2024-09-18 16:00 UTC, kspshnik commented on src/api/recipient-api/recipient-api.controller.ts
> +    description: 'Требуется другой статус',
Хорошо бы указать, чего именно не хватает.

2024-09-18 16:00 UTC, kspshnik commented on src/api/recipient-api/recipient-api.controller.ts
> +    description: 'Требуется другой статус',
Опять же, лучше подробнее.

2024-09-18 16:00 UTC, kspshnik commented on src/api/recipient-api/recipient-api.controller.ts
> +    description: 'Требуется другой статус',
С ходу непонятно, что не так :)

2024-09-24 06:10 UTC, AlexxxDevv commented on src/api/recipient-api/recipient-api.controller.ts
> +    schema: schema(['string'], 'Bad Request', 400),
Что именно не так приходит в ответе, сейчас помечу просто - "переданы не верные данные"

2024-10-03 18:18 UTC, INextYP requested changes

2024-10-03 18:18 UTC, INextYP commented on src/api/recipient-api/recipient-api.controller.ts
> +  @ApiBody({ type: ApiCreateTaskDto })
В поле location нужно указать, что именно он принимает, а не просто массив со строкой
![image](https://github.com/user-attachments/assets/49130275-224c-4861-9126-c472c65abab8)


Сваггер должен быть максимально понятным

2024-10-03 18:18 UTC, INextYP commented on src/api/recipient-api/recipient-api.controller.ts
> +  @ApiQuery({ type: GetTasksSearchDto })
Что-то не так
![image](https://github.com/user-attachments/assets/508dbc40-1b58-43d4-975f-5d7d792334a4)

2024-10-03 18:18 UTC, INextYP commented on src/api/recipient-api/recipient-api.controller.ts
> +    description: 'Для совершения этой операции нужен статус CONFIRMED, VERIFIED, ACTIVATED',
У нас статусы в формате цифр

2024-10-03 18:18 UTC, INextYP commented on src/api/recipient-api/recipient-api.controller.ts
> +  @ApiCreatedResponse({
Проверь на ВСЕХ ручках, какой статус код возвращается и какой ответ

2024-10-03 18:18 UTC, INextYP commented on src/api/recipient-api/recipient-api.controller.ts
> +  @ApiQuery({ type: GetTasksSearchDto })
Что-то не так
![image](https://github.com/user-attachments/assets/6f1a73cb-55f8-4a82-adfc-103e91eba1dd)

2024-10-03 18:18 UTC, INextYP commented on src/api/recipient-api/recipient-api.controller.ts
> +  @ApiBody({ type: ApiCreateTaskDto })
При Патч запросе не должно быть обязательных полей

![image](https://github.com/user-attachments/assets/a82077e6-a206-41f8-abcd-bba2a1201aa9)

2024-10-03 18:18 UTC, INextYP commented on src/api/recipient-api/recipient-api.controller.ts
> +  @ApiCreatedResponse({
Максимально странно, если мы на запрос на удаление будем статус CREATED возвращать ^)

2024-10-03 18:18 UTC, INextYP commented on src/api/recipient-api/dto/created-task.dto.ts
> +export class CreatedTaskDto {
Зачем у уже созданной сущности проводить валидацию?

2024-10-03 18:18 UTC, INextYP commented on src/api/recipient-api/dto/created-task.dto.ts
> +export class CreatedTaskDto {
+ в качестве улучшения можно добавить examples дабы оживить сваггер

2024-10-12 17:24 UTC, AlexeyEfimov85 commented on src/api/recipient-api/dto/created-task.dto.ts
> +export class CreatedTaskDto {
А как мне тогда передать в swagger информацию о теле ответа?

2024-10-13 09:30 UTC, AlexeyEfimov85 commented on src/api/recipient-api/dto/created-task.dto.ts
> +export class CreatedTaskDto {
Я использую это DTO чтобы в теле ответа в Swagger отобразить информацию, как по другому это сделать?

2024-10-21 18:07 UTC, kspshnik requested changes
Опиши, пожалуйста, свойства dto-шек )

2024-10-21 18:07 UTC, kspshnik commented on src/api/recipient-api/dto/created-task.dto.ts
> +import { ApiProperty } from '@nestjs/swagger';
А таки что не велит добавить ко всем полям
```ts
ApiProperty({
  example: '...',
  description: '...'
 });
```
? %)

2024-10-21 18:07 UTC, kspshnik commented on src/api/recipient-api/dto/deleted-task.dto.ts
Аналогично `created-task.dto.ts`

2024-10-21 18:07 UTC, kspshnik commented on src/api/recipient-api/recipient-api.controller.ts
> +    description: 'Для совершения этой операции нужен статус 1, 2, 3',
"1,2,3" это как-то слишком не очень понятно :)
Укажи, пожалуйста, хотя бы константы из перечисления.

2024-10-21 18:07 UTC, kspshnik commented on src/common/dto/api.dto.ts
>  export class PointGeoJSONDto implements PointGeoJSONInterface {
Было бы здорово добавить
```ts
ApiProperty({
  example: '...',
  description: '...',
// прочие свойства
 });

2024-10-21 18:07 UTC, kspshnik commented on src/common/dto/category.dto.ts
Здесь тоже надо описать параметры:
```ts
ApiProperty({
  example: '...',
  description: '...'
 });
```

2024-10-30 21:52 UTC, kspshnik requested changes
Поправь везде `example`, пожалуйста :)

2024-10-30 21:52 UTC, kspshnik commented on src/api/recipient-api/dto/created-task.dto.ts
> +    example: 'virgin, pending, fulfilled, rejected или null',
Во всех `example` мы даём **один** пример заполнения.

2024-11-01 12:48 UTC, kspshnik requested changes
Если у тебя указан `enum`, то значение в `example` должно **точно соответствовать** одному из значений из `enum`.

Как минимум это не так в `TaskStatus`, но проверь везде пожалуйста и приведи в соответствие.

2024-11-01 12:48 UTC, kspshnik commented on src/api/recipient-api/dto/created-task.dto.ts
> +    example: 'virgin',
А почему значение не соответствует перечислению? :)

2024-11-01 12:57 UTC, AlexeyEfimov85 commented on src/api/recipient-api/dto/created-task.dto.ts
> +    example: 'virgin',
самое оперативное ревью в истории))

2024-11-01 13:03 UTC, AlexeyEfimov85 commented on src/api/recipient-api/dto/created-task.dto.ts
> +    example: 'virgin',
стоп, я запутался

2024-11-01 18:33 UTC, kspshnik requested changes
Надеюсь, последняя уже мелочёвка :)

2024-11-01 18:33 UTC, kspshnik commented on src/core/tasks/tasks.service.ts
> +    console.log(query, dto);
А он ещё нужен, этот отладочный вывод?

2024-11-01 18:33 UTC, kspshnik commented on src/api/recipient-api/dto/created-task.dto.ts
> +  @ApiProperty()
И тут пропустил поле :) Его бы тоже описать :)

2024-11-02 09:58 UTC, kspshnik requested changes
Замечания предыдущего ревью проигнорированы.

2024-11-02 18:13 UTC, kspshnik approved these changes
Всё, финал.
@INextYP "Ваше слово, товарищ маузер!" ©

2024-11-03 11:52 UTC, INextYP approved these changes

2024-11-03 12:24 UTC, merged