refactor moved websocket gateway
ya-pomogau/backend pull request #187
Opened 2024-09-17 11:06 UTC by Sapodsoblyaeva

PR по задаче [Вынос gateway сокета в отдельный Api](https://github.com/ya-pomogau/backend/issues/175)
#175

2024-09-18 16:09 UTC, kspshnik approved these changes
Оч. неплохо :)

2024-09-19 12:56 UTC, IvannaBalanyuk approved these changes, later dismissed
Мне всё нравится)

2024-09-19 14:39 UTC, INextYP submitted a review, later dismissed

2024-09-20 05:31 UTC, kspshnik requested changes
Реши, пожалуйста конфликты - к коду вопросов уже нет :)

2024-09-20 07:31 UTC, Sapodsoblyaeva commented
Всем, привет!
А я не могу разрешить этот конфликт, в ветке девелопмент в app.module запущен импорт логера import { LoggerMiddleware } from './common/middleware';
Что выдает мне ошибку - Cannot find module './common/middleware' or its corresponding type declarations.
При попытке коммита даже с этой ошибкой, не пропускает встроенный в коммит линт.

/Users/sveta/Documents/ya-pomogayu/backend/src/app.module.ts
  28:34  error  Missing file extension for "./common/middleware"        import/extensions
  28:34  error  Unable to resolve path to module './common/middleware'  import/no-unresolved

Когда же я дописываю путь import { LoggerMiddleware } from './common/middleware/loggerMiddleware' Он снова выдает конфликт.
Как это поправить?

2024-09-20 07:50 UTC, kspshnik commented
> Всем, привет! А я не могу разрешить этот конфликт, в ветке девелопмент в app.module запущен импорт логера import { LoggerMiddleware } from './common/middleware'; Что выдает мне ошибку - Cannot find module './common/middleware' or its corresponding type declarations. 
Привет! А ты после вмёрживания `development` сделала `npm ci`?
Сам файл этот, './common/middleware.ts' - физически присутствует?

2024-09-20 08:39 UTC, Sapodsoblyaeva commented
Привет!

"А ты после вмёрживания development сделала npm ci?"
Не делала:( но сделал сейчас и ничего не помогло.

"Сам файл этот, './common/middleware.ts' - физически присутствует?"

В том-то и проблема, файл есть, но называется он loggerMiddleware.ts и лежит он в директории "./common/middleware", то есть импорт должен быть в идеале import { LoggerMiddleware } from './common/middleware/loggerMiddleware', а на деле он import { LoggerMiddleware } from './common/middleware' из-за чего у меня и ругается предкомитный линт.

2024-09-20 10:38 UTC, kspshnik approved these changes
Всё ОК :)

2024-09-20 10:39 UTC, merged