feat: add swagger-admin-api updated
ya-pomogau/backend pull request #188
Opened 2024-09-18 09:30 UTC by anna-vetyugova

2024-09-18 16:21 UTC, kspshnik requested changes
Всё отлично, но отключать гарды - это простите ни в какие ворота не лезет :))

2024-09-18 16:21 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +//@UseGuards(JwtAuthGuard)
Типа гарды нинужны????

2024-09-18 16:21 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +//@UseGuards(AccessControlGuard)
Это как же, вашу мать, извиняюсь, понимать? ©
Нененене, Дэвид Блейн, так не покатит.

2024-09-19 09:41 UTC, anna-vetyugova commented
Ой, да, поторопилась. Обновила

2024-09-19 09:47 UTC, kspshnik requested changes
Очень хорошо. Единственное - там где ручка строго для главного администратора (root only) - это надо написать прям в описании ручки :)

2024-09-19 09:47 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +  // @ApiTags('Create an administrative user. Root only.')
Там, где была пометка root only, неплохо бы этот факт явно артикулировать в описании :)

2024-09-19 11:00 UTC, anna-vetyugova commented on src/api/admin-api/admin-api.controller.ts
> +  // @ApiTags('Create an administrative user. Root only.')
добавила

2024-09-19 21:54 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +  // @ApiTags('Create an administrative user. Root only.')
А где добавила? :) Пока не вижу приписки "Только для главного администратора" или аналогичной.

2024-09-20 05:15 UTC, INextYP requested changes

2024-09-20 05:15 UTC, INextYP commented on docker-compose.dev.yml
Менять этот файл в условия задачи не входило. Верни его в исходное состояние

2024-09-20 05:15 UTC, INextYP commented on src/api/admin-api/dto/administrator.dto.ts
> +export class AdministratorDto {
Откуда эта ДТО берется? Нужен интерфейс от которого она наследуется.

+ зачем в DTO передавать 

```
@ApiProperty({
    example: 0,
    description: 'Версия документа',
  })
  __v: number;
```

2024-09-20 09:39 UTC, anna-vetyugova commented
@kspshnik , @INextYP 
добавила новый коммит

2024-09-20 17:21 UTC, kspshnik approved these changes, later dismissed
Вот теперь совсем хорошо :)
Можно ещё для всех limited access расписать, какие нужны полномочия - но это будет уже оверкилл кмк.

2024-09-20 17:21 UTC, kspshnik commented
Не забывай перезапрашивать ревью :))

2024-09-20 17:22 UTC, kspshnik commented
И вспомни подтянуть свежий `development`,  и решить конфликты :)

2024-09-26 07:33 UTC, anna-vetyugova commented
@kspshnik ,
Добрый день! прощу прощения, я немного запуталась) я сейчас жду проверку от @INextYP, правильно?

2024-09-26 12:22 UTC, kspshnik commented
> @kspshnik , Добрый день! прощу прощения, я немного запуталась) я сейчас жду проверку от @INextYP, правильно?


Ага :)

2024-09-29 18:55 UTC, INextYP requested changes
Есть определенные доработки.

Плюсом ко всему - на всех запросах абсолютно непонятно, как выглядит объект с ошибкой

2024-09-29 18:55 UTC, INextYP commented on src/api/admin-api/admin-api.controller.ts
> +    type: CreatedAdministratorDto,
В ответе созданного админа НЕ должно быть пароля. Убери его из DTO

![image](https://github.com/user-attachments/assets/88fd6915-2b9c-4f05-ae9a-46d8517b9945)

2024-09-29 18:55 UTC, INextYP commented on src/api/admin-api/admin-api.controller.ts
> +    type: CreatedAdministratorDto,
Аналогично комментарию про пароль

2024-09-29 18:55 UTC, INextYP commented on src/api/admin-api/admin-api.controller.ts
> +  @ApiResponse({
У сваггера есть набор уже готовых декораторов под различные статус-коды

2024-09-29 18:55 UTC, INextYP commented on src/api/admin-api/admin-api.controller.ts
> +  @ApiBody({ type: ApiPrivilegesDto })
Хочется видеть всё-таки `enum`, а не это
![image](https://github.com/user-attachments/assets/5f83d14c-7d6f-45ec-9aaa-7b7e3c8c62a4)

2024-09-29 18:55 UTC, INextYP commented on src/api/admin-api/admin-api.controller.ts
> +    type: CreatedAdministratorDto,
![image](https://github.com/user-attachments/assets/deddda89-c189-433e-826b-0ca2403a133b)

2024-09-29 18:55 UTC, INextYP commented on src/api/admin-api/admin-api.controller.ts
> +    description: 'Возвращает объект администратора с обновленным значением permissions (массив с перечислением полномочий)',
Аналогично комментарию выше

![image](https://github.com/user-attachments/assets/f372a499-4676-4d58-b303-1a8ac329d47c)

2024-09-29 18:55 UTC, INextYP commented on src/api/admin-api/admin-api.controller.ts
> +  @ApiOperation({ description: 'Подтверждает пользователя' })
Зачем дублировать?

2024-09-29 18:55 UTC, INextYP commented on src/api/admin-api/admin-api.controller.ts
>    @Patch('contacts')
Нет описания тела запроса в сваггере
![image](https://github.com/user-attachments/assets/a0f188b9-ad0b-40c2-9c0f-6f8e1a42eccd)

2024-09-29 18:55 UTC, INextYP commented on src/api/admin-api/admin-api.controller.ts
> +  @ApiOperation({ description: 'Получает список задач на модерации' })
Нужно описать, кто может выполнить этот запрос (админ с полномочиями...)

2024-10-03 17:24 UTC, INextYP requested changes

2024-10-03 17:24 UTC, INextYP commented on src/core/users/users.service.ts
> +      isRoot: true,
Ох, а за такое поругаем с @kspshnik

2024-10-03 17:48 UTC, anna-vetyugova commented on src/core/users/users.service.ts
> +      isRoot: true,
@kspshnik , @INextYP  простите ((((

2024-10-30 14:01 UTC, INextYP approved these changes, later dismissed
@kspshnik можно мёржить. Доработки будет добивать отдельными задачами

2024-10-30 21:58 UTC, kspshnik approved these changes
Поехали :)

2024-10-30 21:59 UTC, kspshnik requested changes
А нет, не поехали.
Реши конфликты, пожалуйста.

@INextYP а ты закрой свои замечания :)

2024-11-03 12:34 UTC, kspshnik approved these changes
Хорошая работа, спасибо!

В принципе, есть минорные улучшения, но если у @INextYP не будет замечаний, они непринципиальны. А если вдруг будут - приду и допишу :)

Ваше слово, товарищ маузер :))

2024-11-03 12:53 UTC, INextYP approved these changes

2024-11-03 12:56 UTC, merged