change chat.types ObjectId to import from mongoose
ya-pomogau/backend pull request #193
Opened 2024-09-24 19:41 UTC by zoomkolol

Эта проблема вылезла как раз из-за того, когда я делал моковый сервис чата. Сейчас верну обратно здесь mongoose, но @kspshnik нужно делать новый issue на фикс мокового сервиса чатов (у него будут ошибки опять, буду сидеть думать как исправить).

2024-09-25 17:21 UTC, kspshnik requested changes
Получение `chatId` в аргументы - это всегда `string`, оно же приходит с фронта. А вот `userId` уже берём из объекта пользователя, он - `ObjectId`, всё правильно :)

2024-09-25 17:21 UTC, kspshnik commented on src/core/chat/chats.service.ts
> +  async addMessage(chatId: ObjectId, message: MessageInterface) {
Здесь мы получаем `chatId` из WS, оно тоже будет `string`

2024-09-25 17:26 UTC, zoomkolol commented
> И самое главное - конфликт-то со схемами решён?

Да, решён. В типах чатов обратно вернул импорт из mongoose (как и было ранее), оно все конфликты фиксит.

chatId тоже поменял

2024-09-25 18:16 UTC, kspshnik submitted a review, later dismissed
Теперь всё :)
Ждём @IvannaBalanyuk как главную по чат-тарелочкам :), и @INextYP как вообще самого главного по проекту :)

2024-09-26 13:46 UTC, IvannaBalanyuk submitted a review, later dismissed

2024-09-26 14:00 UTC, IvannaBalanyuk reviewed
В целом всё хорошо)
У меня вопрос только по строке 112:
![image](https://github.com/user-attachments/assets/1cb42b11-6b69-422e-989c-f3f1cb2e8fff)
Не надо ли и тут поправить на значение `new mongoose.Types.ObjectId().toHexString()`?

2024-09-26 14:15 UTC, kspshnik commented
> В целом всё хорошо) У меня вопрос только по строке 112: ![image](https://private-user-images.githubusercontent.com/124444858/371175723-1cb42b11-6b69-422e-989c-f3f1cb2e8fff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjAzNDYsIm5iZiI6MTcyNzM2MDA0NiwicGF0aCI6Ii8xMjQ0NDQ4NTgvMzcxMTc1NzIzLTFjYjQyYjExLTZiNjktNDIyZS05ODljLWYzZjFjYjJlOGZmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQxNDE0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWUwMTM4ZWNhOTU3MDgyZjA3NjEzMzE0NTVmZjI0YjRlYzRhYWZiMTM1YTljNGZhYTAwMWYxNmU2OTNiMzAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Rpq3vwAcu55ZaXKXqRvccfFoJqJL7ztbDNCVsKwbkys) Не надо ли и тут поправить на значение `new mongoose.Types.ObjectId().toHexString()`?


Да. @zoomkolol поправь пожалуйста, чтобы не затевать переревью.

2024-09-26 14:40 UTC, IvannaBalanyuk approved these changes

2024-09-27 18:03 UTC, kspshnik approved these changes

2024-09-27 18:04 UTC, INextYP approved these changes

2024-09-27 20:33 UTC, merged