Feature/send new chat message by socket
ya-pomogau/backend pull request #206
Opened 2024-10-06 18:53 UTC by AlexeyEfimov85

2024-10-06 19:34 UTC, kspshnik requested changes
Очень хорошо :)
Перебросить только логику отправки, и вообще отл. %)
Ну и странности с типами разъяснить %)

2024-10-06 19:34 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +    @MessageBody('NewMessage') NewMessage: WSNewMsgCommandPayload
А почему не lower camel case? Это же переменная, `newMessageDto` по хорошему надо её звать :)

2024-10-06 19:34 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +    const message = { title, body, attaches, author };
Это можно в одну строку: `const { title, body, attaches, author, ...rest } = NewMessage;`

2024-10-06 19:34 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +  sendNewMessage(message, chatId: string) {
`chatId` по идее есть в `message`, см. `MessageInterface`, тут уже пойдёт сообщение _после_ записи в БД, со всеми нужными полями.

2024-10-06 19:34 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +    const userIds: string[] = [userId];
Всем вот этим надо заниматься уже в `sendNewMessage()`:
1. Получить по `chatId` активных (онлайн) пользователей в этой комнате (они должны добавляться по _открытию_ чата на клиенте, удаляться по закрытию).
2. Если нет онлайн никого (нет `chatId` в `openedChats`), выходим (но так быть по идее не должно, хоть один будет).
3. Для каждого пользователя из `connectedUsers` дёргаем все его сокеты.
4. И каждому из этих сокетов отправляем это сообщение :)
5. Et voila ;o)

2024-10-06 19:34 UTC, kspshnik commented on src/api/websocket-api/websocket-api.module.ts
> +  providers: [WebsocketApiGateway, AuthService, JwtService, AddChatMessageHandler, ChatService],
Лучше добавлять команды, а не обработчики: так не надо их регистрировать :)

2024-10-06 19:34 UTC, kspshnik commented on src/common/commands/add-chat-message.command.ts
> +    public readonly message: Omit<NewMessageInterface, 'chatId'>
А зачем здесь убирать `chatId`??

2024-10-06 19:34 UTC, kspshnik commented on src/core/chat/chats.service.ts
> +  async addMessage(chatId: string, message: Omit<NewMessageInterface, 'chatId'>) {
Опять вопрос: зачем это подавлять-то? Может, лучше убрать `chatId`?

2024-10-08 08:23 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +    const userIds: string[] = [userId];
Вот эту всю красоту надо бы прокомментировать было как "Временное до появления открытия чатов"

2024-10-08 08:29 UTC, kspshnik requested changes
Уже практически отлично.
И хочется услышать мнение ~~начальника транспортного цеха~~ @INextYP, чтобы потом дважды не чинить :)

2024-10-08 08:29 UTC, kspshnik commented on src/api/websocket-api/websocket-api.module.ts
> +  providers: [WebsocketApiGateway, AuthService, JwtService, AddChatMessageHandler, ChatService],
Попробуй добавить `WebsocketApiModule` в `imports` вместо этого, и разрешить циклическую зависимость через `.forwardRef()` - таким образом мы плодим инстансы gateway.
Посмотри в чатике general - я про это именно писал.

2024-10-08 08:29 UTC, kspshnik commented on src/common/commands/add-chat-message.command.ts
> +  constructor(public readonly message: Omit<MessageInterface, '_id' | 'createdAt'>) {}
Смотри, эта штука встречается уже второй раз. Давай вынесем интерфейс в `websockets.types.ts` ?

2024-10-09 08:33 UTC, kspshnik requested changes
Уже супер, последний остаётся штрих :)
И ждём мнения @INextYP

2024-10-09 08:33 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +    const usersInChat = this.openedChats.get(chatId);
Я бы это `Set` сделал - избавимся от дублирований, при открытии одного и того же чата с нескольких устройств в массив будут попадать нсколько одинаковых id-шек. А нам это не надо - в `connectedUsers` и так все сокеты есть.

2024-10-11 06:13 UTC, INextYP approved these changes, later dismissed
Мои комментарии вариативные. Сейчас можно не исправлять.

А так всё хорошо :)

2024-10-11 06:13 UTC, INextYP commented on src/api/websocket-api/dto/new-message.dto.ts
> +export class newMessageDto implements WsNewMessage {
Пока некритичное замечание, но классы с большой буквы называются

2024-10-11 06:13 UTC, INextYP commented on src/api/websocket-api/websocket-api.gateway.ts
> +    const { ...message } = savedMessage;
В чём смысл копировать объект, если ты его никак не модифицируешь?

2024-10-11 06:13 UTC, INextYP commented on src/api/websocket-api/websocket-api.gateway.ts
> +    const connectedUsers: wsConnectedUserData[] = [];
Обычно так не делают, но до полной реализации оставим как есть.

Можно указать тут "TODO: переписать на механизм комнат"

2024-10-12 17:45 UTC, AlexeyEfimov85 commented on src/api/websocket-api/websocket-api.gateway.ts
> +    const usersInChat = this.openedChats.get(chatId);
не совсем понял - заменить Map на Set (Set - нам такое не подойдет ведь у него нет ключей) или заменить второй аргумент Map вместо string[] 
на Set?

2024-10-12 17:53 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +    const usersInChat = this.openedChats.get(chatId);
> или заменить второй аргумент Map вместо string[] на Set?

Второе, конечно :) 
Нам здесь не важно, со скольки устройств одновременно открыл юзверь чатик, важно - что он таки открыл. 
А потом мы в `connectedUsers` найдём этого юзверя по `_id`, и отправим на все его sockets сообщение :)

2024-10-15 16:22 UTC, INextYP approved these changes

2024-10-15 17:27 UTC, kspshnik approved these changes
Ура! И спасибо, отличная работа :)

2024-10-15 17:28 UTC, merged