Feature/send chat messages by socket
ya-pomogau/backend pull request #207
Opened 2024-10-07 17:47 UTC by AlexeyKrutyakov

add sending chat messages by socket

2024-10-07 18:21 UTC, kspshnik requested changes
Большая работа, отлично.
Поправим мелочь, и чуть изменить логику отправки.

Ну и до кучи надо отрефакторить сервис чатов: логичнее, когда он возвращает чистые данные, он же не знает, для кого :))

2024-10-07 18:21 UTC, kspshnik commented on src/api/websocket-api/websocket-api.module.ts
> +    WebsocketApiGateway,
Попробуй вместо этого импортировать `WebsocketApiModule` выше, в `imports`

2024-10-07 18:21 UTC, kspshnik commented on src/api/websocket-api/websocket-api.module.ts
> +  constructor(private readonly commandBus: CommandBus, private readonly queryBus: QueryBus) {}
Не надо так. Добавляй в провайдеры **запросы**, а не их обработчики. Посмотри аналог в `AuthApi` с командами.

2024-10-07 18:21 UTC, kspshnik commented on src/api/websocket-api/websocket-api.module.ts
> +    ...QUERIES_HANDLERS,
Запросы, а не обработчики.

2024-10-07 18:21 UTC, kspshnik commented on src/common/queries/index.ts
> +export const QUERIES_HANDLERS: Type<IQueryHandler>[] = [GetChatMessagesQueryHandler];
ЗАпросы, а не обработчики.

2024-10-07 18:21 UTC, kspshnik commented on src/core/get-chat-messages-query.handler.ts
> +    return this.chatService.getMessages(chatId, skip, limit);
Мне кажется, `ChatService.getMessages()` должен возвращать _массив_ *сообщений*, а оборачивать его будем уже в gateway.

2024-10-07 18:21 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +    const request = await this.queryBus.execute(
Отрефакторь `ChatService`, чтобы он возвращал `Array<MessageInterface>`, а уже тут оберни в `wsMessageData`.

2024-10-08 14:07 UTC, ivanjsx commented on src/api/websocket-api/websocket-api.module.ts
> +  constructor(private readonly commandBus: CommandBus, private readonly queryBus: QueryBus) {}
@kspshnik привет! но ведь в `AuthApi` как раз добавлены обработчики..? 🧐 хоть переменная и многозначительно называется `COMMANDS`, в ней лежит список обработчиков, а не самих команд.

помоги пожалуйста разобраться 🙏

2024-10-08 14:20 UTC, ivanjsx commented on src/api/websocket-api/websocket-api.module.ts
> +  constructor(private readonly commandBus: CommandBus, private readonly queryBus: QueryBus) {}
точно так же описано и в документации (Саша присылал скрин из неё [вот тут](https://app.pachca.com/chats?thread_message_id=349187890&sidebar_message=349238547))

2024-10-10 15:08 UTC, kspshnik commented on src/api/websocket-api/websocket-api.module.ts
> +    WebsocketApiGateway,
Это я спросонья, так надо в других сервисах. Забей на это замечание :)

2024-10-10 15:08 UTC, kspshnik commented on src/api/websocket-api/websocket-api.module.ts
> +  constructor(private readonly commandBus: CommandBus, private readonly queryBus: QueryBus) {}
Да, ты прав тут.

2024-10-15 09:14 UTC, kspshnik requested changes
Всё отлично, последние штрихи остались :)

2024-10-15 09:14 UTC, kspshnik commented on src/api/websocket-api/websocket-api.module.ts
> +export class WebsocketApiModule implements OnModuleInit {
А это точно надо?? `AuthApiController` работает без таких бубнов, например.

2024-10-15 09:14 UTC, kspshnik commented on src/api/websocket-api/websocket-api.module.ts
> +    CommandBus,
А попробуй вместо добавления в `providers` и `CommandBus` и `QueryBus`, добавить в `imports` `CqrsModule` ??

2024-10-15 12:05 UTC, AlexeyKrutyakov commented on src/api/websocket-api/websocket-api.module.ts
> +    CommandBus,
поправил, спасибо за замечания

2024-10-15 13:54 UTC, INextYP requested changes

2024-10-15 13:54 UTC, INextYP commented on src/api/websocket-api/websocket-api.module.ts
> +  onModuleInit() {
Вот это тоде нужно вычистить. Должен остаться

`export class WebsocketApiModule {}`

2024-10-15 20:06 UTC, kspshnik requested changes
Сейчас слияние заблокировано: надо подтянуть последние изменения из development и решить все конфликты.

2024-10-16 05:50 UTC, AlexeyKrutyakov commented
всё поправил

2024-10-16 06:33 UTC, INextYP approved these changes

2024-10-16 07:15 UTC, kspshnik approved these changes
Отличная работа, спасибо!

2024-10-16 07:17 UTC, merged