Feature/open close chat handlers
ya-pomogau/backend pull request #208
Opened 2024-10-08 14:37 UTC by anna-vetyugova

2024-10-08 16:45 UTC, kspshnik requested changes
Спасибо, очень хорошая работа.
Единственное - чуть другая логика при открытии/закрытии чата. И ещё хорошо бы при открытии сразу делать запрос за последними сообщениями и отправлять их на клиента в ответ. Поставь, пожалуйста, пока тудушку (`// TODO: ...`), когда появится запрос данных - добавим :)

2024-10-08 16:45 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
Мапы подключённых пользователей и открытых чатов - разные вещи. Наверное, нинада в мапе чатов сокетов - только юзверей, точнее айдишник.
При отправке сообщений будем брать айдишники онлайн-участников, и по `connectedUsers` находить все активные сокеты участника.

2024-10-15 16:22 UTC, INextYP submitted a review, later dismissed

2024-10-15 17:39 UTC, kspshnik commented
@anna-vetyugova необходимо разрешить конфликты.

2024-10-15 19:57 UTC, kspshnik requested changes
Сейчас слияние заблокировано: надо подтянуть последние изменения из development и решить все конфликты.

Плюс надо переписать логику под `Set`, и убрать всё, что связано с обработкой _соединения_ - это scope других методов нашего gateway.

2024-10-15 19:57 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
Здесь надо будет чуть-чуть отрефакторить: во влитых изменениях мапа открытых чатов поменялась на `Map<string, Set<string>>`.  Логика останется практически такая же, только формат хранения меняется (ключ - `chatId`, значение - `Set<dtring>` с `userId` пользователей, у которых открыт данный чат).

2024-10-15 19:57 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +    if (!openedChat.users.includes(user._id)) {
Здесь можно будет не проверять, есть ли уже этот пользователь или нет за счёт того, что `Set` автоматически обеспечивает уникальность своих элементов. Просто добавляем и не думаем, есть или нет :)

2024-10-15 19:57 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +    const connectedUser = this.connectedUsers.get(user._id);
Эта логика из `this.handleConnection()`, зачем она тут?

2024-10-15 19:57 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +    const connectedUser = this.connectedUsers.get(user._id);
Аналогично, это должно быть не тут, а в `this.handleDisconnect()` или как его там :) - отключение от WS происходит при закрытии **приложения**, а не отдельно взятого чата.

2024-10-16 18:10 UTC, INextYP approved these changes
@kspshnik %)

2024-10-16 18:48 UTC, kspshnik requested changes
Наверное, финальный штрих

2024-10-16 18:48 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +      this.openedChats.set(chatId, newarr.add(userId));
А если по этому ключу **уже есть** значение? Затираем информацию об открытии чата нашим визави?

2024-10-16 18:48 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +    const { ...message } = savedMessage;
А зачем этот спред в **ТАКОЙ ЖЕ** объект?

2024-10-16 18:48 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +    const connectedUsers: wsConnectedUserData[] = [];
А почему название аналогично мапе `this.connectedUsers`? Это бы переименовать...

2024-10-16 18:48 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +    const openedChat = this.openedChats.get(chatId);
А зачем не в одну строку? :)

2024-10-16 19:38 UTC, anna-vetyugova commented on src/api/websocket-api/websocket-api.gateway.ts
> +      this.openedChats.set(chatId, newarr.add(userId));
я уже немного запутулась)) со 191 по 221 это после мержа с веткой development 
если честно, то я сильно не смотрела эту часть, правила только хендлеры открытия и закрытия, что по задаче было
нужно получается проверить?

2024-10-16 19:51 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +      this.openedChats.set(chatId, newarr.add(userId));
А, тогда отставить.
Заресолвь, если не твои и перезапрашивай ревью :)

2024-10-16 20:22 UTC, anna-vetyugova commented on src/api/websocket-api/websocket-api.gateway.ts
> +    const openedChat = this.openedChats.get(chatId);
у меня, видимо, из-за работы голова кругом)) так, я нахожу чат, удаляю пользователя и, если, в чате больше никого нет, то удаляю сам чат, или я что-то упускаю?

2024-10-16 20:41 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +    const openedChat = this.openedChats.get(chatId);
`this.openedChats.get(chatId).delete(userId);`
;o)

2024-10-16 20:42 UTC, kspshnik approved these changes
ОК :) Если вдруг что вылезет - потом поправим.

2024-10-16 20:43 UTC, merged