create sendUserChatsMeta method for usage from within the handleConnection method
ya-pomogau/backend pull request #212
Opened 2024-10-14 02:50 UTC by ivanjsx

2024-10-15 20:04 UTC, kspshnik requested changes
Очень хорошо! Одно место только измени, пожалуйста (да, я вижу, что в таске так, но это наверное неоптимально).
И ещё одна проблема: сейчас слияние заблокировано - надо подтянуть последние изменения из development и решить все конфликты.

2024-10-15 20:04 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +  async sendUserChatsMeta(userId: string, clientIds: string[] = null): Promise<void> {
Наверное, лучше брать клиентов сразу через `this.getConnectedUser()`, не передавая параметром.

2024-10-16 08:31 UTC, INextYP requested changes

2024-10-16 08:31 UTC, INextYP commented on src/api/websocket-api/websocket-api.gateway.ts
> +      this.server.sockets.sockets.get(clientId).emit(wsMessageKind.REFRESH_CHATS_META_COMMAND, {
@kspshnik мы тут разве `REFRESH_CHATS_META_COMMAND` отправляем?

2024-10-16 08:41 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +      this.server.sockets.sockets.get(clientId).emit(wsMessageKind.REFRESH_CHATS_META_COMMAND, {
@INextYP Да. Это не CQRS-команда же, а тип сообщения по WS.

2024-10-16 10:16 UTC, INextYP commented on src/api/websocket-api/websocket-api.gateway.ts
> +      this.server.sockets.sockets.get(clientId).emit(wsMessageKind.REFRESH_CHATS_META_COMMAND, {
Я имею ввиду, что зачем мы при подключении к сокету отправляем эвент на обновление меты.

Какой эвент мы будем тогда отправлять, если нужно будет отправить на клиент как раз обновления по мете?

2024-10-16 10:18 UTC, kspshnik commented on src/api/websocket-api/websocket-api.gateway.ts
> +      this.server.sockets.sockets.get(clientId).emit(wsMessageKind.REFRESH_CHATS_META_COMMAND, {
Тот же :)
Просто в первом случае старая мета на фронте равна пустому множеству, а в последующих - нет :)

2024-10-16 18:11 UTC, INextYP approved these changes

2024-10-16 18:57 UTC, kspshnik approved these changes
Всё отлично :)

2024-10-16 18:57 UTC, merged