refactor/patch-profile-to-cqrs
ya-pomogau/backend pull request #213
Opened 2024-10-17 09:16 UTC by Sapodsoblyaeva

2024-10-17 18:04 UTC, kspshnik reviewed
Классная работа, супер!
Но у нас есть одна проблема: мы будем _дважды_ создавать токен. Это потенциальная дыра и/или бага.

Мне кажется логичным сделать так, чтобы **все** изменяющие пользователя методы класса `UsersService` возвращали не просто  пользователя, а объект `{ user, token }` с обновлённым объектом пользователя и новым, перевыпущенным токеном. Это можно сделать, если они будут возвращать `return this.refreshAndSendToken(...);`, но надо пройти по всем вызовам и отрефакторить там, чтобы не менять сигнатуры возвратов на клиента.

@INextYP, что скажешь?

2024-10-17 18:13 UTC, kspshnik commented
@Sapodsoblyaeva смотри, главной целью было убрать жесткую связь сервиса аутентификации и контроллера системного API, и с ней ты справилась блестяще :)
Но выплывает проблема повторной генерации токена. Это не самый лучший подход, как минимум потому, что шифрование довольно ресурсоёмкий процесс. Да и дыра потенциальная.
Чтобы его решить, надо отрефакторить немножко `UsersSetvice`, да и все контроллеры пройти/проверить на предмет использования мутирующих пользователя в базе методов сервиса пользователей.

Эти PR и issue мы скорее всего закроем как выполненные, не вмёрживая код, и сделаем новую задачку в той же самой ветке. Предлагаю её сразу тебе и забрать :)

2024-10-19 08:04 UTC, INextYP commented
> Классная работа, супер! Но у нас есть одна проблема: мы будем _дважды_ создавать токен. Это потенциальная дыра и/или бага.
> 
> Мне кажется логичным сделать так, чтобы **все** изменяющие пользователя методы класса `UsersService` возвращали не просто пользователя, а объект `{ user, token }` с обновлённым объектом пользователя и новым, перевыпущенным токеном. Это можно сделать, если они будут возвращать `return this.refreshAndSendToken(...);`, но надо пройти по всем вызовам и отрефакторить там, чтобы не менять сигнатуры возвратов на клиента.
> 
> @INextYP, что скажешь?

Да, хорошо

2024-10-19 08:05 UTC, INextYP commented on src/api/system-api/system-api.module.ts
> +  providers: [...COMMANDS, AuthService, JwtService, WebsocketApiGateway],
`WebsocketApiGateway` тут создаст проблему, а именно: будет создан доп. инстанс гейтвея.

Чтобы это исправить нужно отсюда убрать `WebsocketApiGateway`, а в массив `imports` добавить `WebsocketApiModule`

2024-10-19 08:05 UTC, INextYP commented on src/api/system-api/system-api.controller.ts
>      return Promise.resolve({ ...profile, token });
Зачем? Если метод асинхронный и итак возвращает результат промиса

2024-10-27 13:40 UTC, Sapodsoblyaeva commented
PR за задаче: [Рефакторинг мутирующих пользователя методов сервиса пользователя, и использующих их API, c переводом на CQRS.](https://github.com/ya-pomogau/backend/issues/215)
#215

Прошу прощения за задержку, задача вышла объемная. 

Не по теме, случайно заметила походу выполнения, проверьте плиз. В datalake  в таск = 2 разных таск модуля, так и должно быть? 

Перед этим всем, прошу обратить внимание, пришлось обновлять тест по admin-api.controller.ts, потому что в провайдере появились COMMANDS, а в тесте не было их, и как итог, он падал при коммите. 

Перечень выполненных действий:

Определено место вызова метода .confirm(): сервис admin-api.controller.ts, метод confirm().
Создана команда ConfirmUserCommand
Создан обработчик ConfirmUserHandler
Обработчик ConfirmUserHandler отправляет команду SendTokenCommand перед возвратом результата, возвращает объект { user: AnyUserInterface, token: string }.
Метод UsersService.confirm() возвращает обновлённый объект пользователя.
Работа через постман проверена

Определено место вызова метода .activate(): сервис admin-api.controller.ts, метод activate().
Создана команда ActivateUserCommand
Создан обработчик ActivateUserHandler
Обработчик ActivateUserHandler отправляет команду SendTokenCommand перед возвратом результата, возвращает объект { user: AnyUserInterface, token: string }.
Метод UsersService.activate() возвращает обновлённый объект пользователя.
Работа через постман проверена

Определено место вызова метода .upgrade(): сервис admin-api.controller.ts, метод activate().
Создана команда UpgradeUserCommand
Создан обработчик UpgradeUserHandler
Обработчик UpgradeUserHandler отправляет команду SendTokenCommand перед возвратом результата, возвращает объект { user: AnyUserInterface, token: string }.
Метод UsersService.upgrade() возвращает обновлённый объект пользователя.
Работа через постман проверена


Метод .downgrade() переделала, команду и хэндлер создала, однако на текущий момент она нигде не используется. В admin-api.controller.ts стоит на нее запрет. Работа через постман проверена

Определено место вызова метода .grantKeys(): сервис admin-api.controller.ts, метод grantKeys().
Создана команда GrantVolunteerKeysCommand
Создан обработчик GrantVolunteerKeysHandler
Обработчик GrantVolunteerKeysHandler отправляет команду SendTokenCommand перед возвратом результата, возвращает объект { user: AnyUserInterface, token: string }.
Метод UsersService. grantKeys () возвращает обновлённый объект пользователя.
Работа через постман проверена

Метод .revokeKeys() переделала, команду и хэндлер создала, однако на текущий момент она нигде не используется. В admin-api.controller.ts стоит на нее запрет. Работа через постман проверена.

Определено место вызова метода .grantPrivileges(): сервис admin-api.controller.ts, метод grantPrivileges ().
Создана команда GrantAdminPrivilegesCommand
Создан обработчик GrantAdminPrivilegesHandler
Обработчик GrantAdminPrivilegesHandler отправляет команду SendTokenCommand перед возвратом результата, возвращает объект { user: AnyUserInterface, token: string }.
Метод UsersService.grantPrivileges () возвращает обновлённый объект пользователя.
Работа через постман проверена
Определено место вызова метода .revokePrivileges(): сервис admin-api.controller.ts, метод revokePrivileges ().
Создана команда RevokeAdminPrivilegesCommand
Создан обработчик RevokeAdminPrivilegesHandler
Обработчик RevokeAdminPrivilegesHandler отправляет команду SendTokenCommand перед возвратом результата, возвращает объект { user: AnyUserInterface, token: string }.
Метод UsersService.revokePrivileges () возвращает обновлённый объект пользователя.
Работа через постман проверена


Определено место вызова метода .updatePrivileges(): сервис admin-api.controller.ts, метод updatePrivileges ().
Создана команда UpdateAdminPrivilegesCommand
Создан обработчик UpdateAdminPrivilegesHandler
Обработчик UpdateAdminPrivilegesHandler отправляет команду SendTokenCommand перед возвратом результата, возвращает объект { user: AnyUserInterface, token: string }.
Метод UsersService.updatePrivileges () возвращает обновлённый объект пользователя.
Работа через постман проверена


Определено место вызова метода .updateProfile(): сервис system-api.controller.ts, метод updateProfile().
Создана команда UpdateUserProfileCommand
Создан обработчик UpdateUserProfileHandler
Обработчик UpdateUserProfileHandler отправляет команду SendTokenCommand перед возвратом результата, возвращает объект { user: AnyUserInterface, token: string }.
Метод UsersService.updateProfile () возвращает обновлённый объект пользователя.
Работа через постман проверена

Определено место вызова метода .updateVolunteerProfile(): сервис system-api.controller.ts, метод updateVolunteerProfile ().
Создана команда UpdateVolunteerProfileCommand
Создан обработчик UpdateVolunteerProfileHandler
Обработчик UpdateVolunteerProfileHandler отправляет команду SendTokenCommand перед возвратом результата, возвращает объект { user: AnyUserInterface, token: string }.
Метод UsersService.updateVolunteerProfile () возвращает обновлённый объект пользователя.
Работа через постман проверена


UsersService.refreshAndSendToken() удален


И еще вопрос касательно остальных методов userservice, в которых не было refreshToken их на команды/квериес надо менять?

2024-10-28 06:28 UTC, kspshnik commented
> И еще вопрос касательно остальных методов userservice, в которых не было refreshToken их на команды/квериес надо менять?

Для этого будет _новое_ issue.

2024-10-28 06:44 UTC, kspshnik requested changes
Супер!!! Просто мегаработа!!

Осталось только добавить два забытых метода, и мелочь очепяточную поправить :)
Очень хорошая работа.

2024-10-28 06:44 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
`UsersService.deactivate(_id)` и `UsersService.block(_id)` тоже мутируют пользователя, их бы на CQRS аналогично активации и подтверждению.

2024-10-28 06:44 UTC, kspshnik commented on src/core/grant-volunteer-kyes.handler.ts
Тут опечатка просто в имени файла. Переименуй аккуратно, пожалуйста.

2024-10-28 06:44 UTC, kspshnik commented on src/core/users/users.service.ts
>    private static requireLogin(userId: string) {
И вот это тоже можно удалять, я думаю. Проверь, что нигде больше не используется, и убери, если так, пожалуйста.

2024-10-28 07:47 UTC, Sapodsoblyaeva commented
Всем, привет! 

Замечания поправила, методы добавила, единственный нюанс, я их в первых раз не делала, так как они не использовали this.refreshToken(), как следствие сейчас сделала хэндлеры без вызова SendTokenCommand, вместо этого они просто user возвращают, как в изначальных методах в User.service.ts. 

Определено место вызова метода .deactivate(): сервис admin-api.controller.ts, метод deactivate ().
Создана команда DeactivateAdminCommand
Создан обработчик DeactivateAdminHandler
Метод UsersService. deactivate() возвращает обновлённый объект пользователя.
Работа через постман проверена

Определено место вызова метода .block(): сервис admin-api.controller.ts, метод block ().
Создана команда BlockUserommand
Создан обработчик BlockUserHandler
Метод UsersService.block () возвращает обновлённый объект пользователя.
Работа через постман проверена

2024-10-28 07:49 UTC, Sapodsoblyaeva commented on src/core/users/users.service.ts
>    private static requireLogin(userId: string) {
вот это не нашла, у меня users.service.ts заканчивается на 500 строке, плюс поиск по SendTokenCommand тоже ничего не дал.

2024-10-28 08:12 UTC, kspshnik requested changes
Уже последнее чуть-чуть :)

2024-10-28 08:12 UTC, kspshnik commented on src/common/commands/revoke-volunteer-kyes.command.ts
И снова очепяток :)

2024-10-28 08:12 UTC, kspshnik commented on src/core/block-user.handler.ts
А почему не `{ user, token }`?

2024-10-28 08:12 UTC, kspshnik commented on src/core/deactivate-admin.handler.ts
А почему не { user, token }?

2024-10-28 08:12 UTC, kspshnik commented on src/core/users/users.service.ts
>    private static requireLogin(userId: string) {
оч. странно. Ну да это не принципиальный момент.

2024-10-28 11:45 UTC, Sapodsoblyaeva commented on src/common/commands/revoke-volunteer-kyes.command.ts
это видимо я уже исправила, так как тэг outdated стоит.

2024-10-28 11:47 UTC, Sapodsoblyaeva commented on src/core/deactivate-admin.handler.ts
потому что изначально в методах в users.service.ts в них не было рефреша токена. Может он и должен был быть, но я об этом точно не знаю. Если надо я добавлю.

2024-10-28 11:47 UTC, Sapodsoblyaeva commented on src/core/block-user.handler.ts
потому что изначально в методах в users.service.ts в них не было рефреша токена. Может он и должен был быть, но я об этом точно не знаю. Если надо я добавлю.

2024-10-28 12:04 UTC, kspshnik commented on src/core/deactivate-admin.handler.ts
Думаю, что да: ведь нам надо отправлять новый токен по каждому изменению юзверя - ведь потом гарды будут именно из расшифрованного токена в запросе доставать юзверя и принимать решения о (не)допуске к той или иной ручке :)

2024-10-28 12:05 UTC, kspshnik commented on src/core/block-user.handler.ts
Да, надо :) Подробнее в другом комменте :)

2024-10-29 11:31 UTC, Sapodsoblyaeva commented
Готово, все поправила)

2024-10-29 12:15 UTC, kspshnik approved these changes
Супер, отличная работа!
Спасибо!

@INextYP "Ваше слово, товарищ маузер!" © %)

2024-10-30 14:06 UTC, INextYP approved these changes

2024-10-30 21:16 UTC, merged