Рефакторинг ручек возврата списков активных, заблокированных (деактивированных) и всех администраторов #209
ya-pomogau/backend pull request #214
Opened 2024-10-19 00:35 UTC by im-Arn

add methods to get a list of act/inact administrators (getActivatedAdmitistrators, getDeactivatedAdmitistrators)
ref getAdministrators

2024-10-19 10:57 UTC, kspshnik requested changes
Отлично!
Только переусложнённый момент с получением вообще всех администраторов поправь/упрости - и порядок :)

2024-10-19 10:57 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +    ]).then(([activeAdmins, inactiveAdmins]) => [...activeAdmins, ...inactiveAdmins].flat());
А зачем и `await` и `then()` ?
Сначала получаем массив массивов, а потом возвращаем его "уплощённым":
```ts
const adminsArray = await Promise.all([
       this.usersService.getAdministrators(true),
       this.usersService.getAdministrators(false),
     ]);
return adminsArray.flat();`
```

2024-10-24 14:03 UTC, im-Arn commented on src/api/admin-api/admin-api.controller.ts
> +    ]).then(([activeAdmins, inactiveAdmins]) => [...activeAdmins, ...inactiveAdmins].flat());
Monkey see, monkey do Т_Т

2024-10-30 13:59 UTC, INextYP approved these changes
Всё отлично!

2024-10-30 21:54 UTC, kspshnik approved these changes
Атлична!

2024-10-30 21:54 UTC, kspshnik approved these changes
Супер :)

2024-10-30 21:57 UTC, merged