bugfix/update-task-location #190
ya-pomogau/backend pull request #216
Opened 2024-10-19 13:02 UTC by VeraDgt

2024-10-20 11:37 UTC, VeraDgt commented
На фронте нужна ветка fix/edit-task или ее копия bugfix/update-task-location

2024-10-20 12:02 UTC, kspshnik commented
> На фронте нужна ветка fix/edit-task или ее копия bugfix/update-task-location


А _зачем_? Нужен адаптер на бэкенде, вызываемый из команды.

2024-10-21 06:08 UTC, VeraDgt commented
Возможно. А такое уже реализовано? Можно где-то посмотреть подробно?
В любом случае бэкенд принимает стандартный payload (один на добавление и обновление) и не падает с ошибкой, таска корректно обновляется.

2024-10-30 13:49 UTC, INextYP requested changes

2024-10-30 13:49 UTC, INextYP commented on src/core/tasks/tasks.service.ts
> -    await this.commandBus.execute(new CreateTaskChatCommand({ taskId, updatedTask }));
Почему была убран этот код? Это требовалось в рамках задачи? Если нет, то нужно вернуть в исходное состояние

2024-10-31 16:45 UTC, VeraDgt commented on src/core/tasks/tasks.service.ts
> -    await this.commandBus.execute(new CreateTaskChatCommand({ taskId, updatedTask }));
Вернула на место.

2024-10-31 17:41 UTC, kspshnik approved these changes
Похоже, всё нормально.

@INextYP  твоё слово :)

2024-11-03 13:08 UTC, INextYP approved these changes
Всё ок

2024-11-03 13:17 UTC, merged