Feature/set admin password handle
ya-pomogau/backend pull request #217
Opened 2024-10-21 16:10 UTC by TerSV86

Создал ручку для изменения пароля администратора по задаче https://github.com/ya-pomogau/backend/issues/210

2024-10-21 20:14 UTC, kspshnik requested changes
Очень хорошо.
Надо поправить мелкие недочёты, откатить изменения в слое данных (его не трогаем) и скоординироваться со Светланой, дабы вы друг с другом не боролись в PR %)

2024-10-21 20:14 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +    await this.commandBus.execute(new SetAdminPasswordCommand(userId, body.password));
Любой изменяющий пользователя метод должен перелогинить пользователя и вернуть ему объект `{ user, token }`, причём вернуть ещё и по WebSockets. Смотри issues #211 (закрыто), продолжающее его #215 и PR #213 - там в комментариях/описаниях полная информация.

2024-10-21 20:14 UTC, kspshnik commented on src/api/admin-api/dto/set-admin-password.dto.ts
> +  @ApiProperty()
Я бы добавил декоратору `@ApiProperty()` аргумент:
```ts
@ApiProperty({
  description: 'Новый пароль администратора',
  example: 'Dksc7w2349n0-=uhswfc877d$',
 });
```

2024-10-21 20:14 UTC, kspshnik commented on src/core/set-admin-password.handler.ts
> +    await this.userService.setAdminPassword(userId, password);
Надо _возвращать_ значение: 
```ts
return this.userService.setAdminPassword(userId, password);
```

2024-10-21 20:14 UTC, kspshnik commented on src/core/users/users.service.ts
> +      throw new NotFoundException(`Изменение пароля Главного администратора недоступно`);
Это разве "не найдено" ? :))) `ForbiddenException()` тут кмк будет лучше смотреться.

2024-10-21 20:14 UTC, kspshnik commented on src/core/users/users.service.ts
> +    return adminUpdatePassword;
Возвращаем всегда **обновлённый** *объект пользователя*.

2024-10-21 20:14 UTC, kspshnik commented on src/datalake/users/schemas/user.schema.ts
НЕ МЕНЯЕМ ТУТ НИЧЕГО.

Откати, пожалуйста.

2024-10-21 20:14 UTC, kspshnik commented on src/core/users/users.service.ts
> +      this.refreshAndSendToken(adminUpdatePassword);
Смотри, это будет заменено и удалено в процессе работы над #215 .
Свяжись, пожалуйста, с @Sapodsoblyaeva и скоординируйтесь, кто будет первым, а кто потом поправит это место.

2024-10-22 10:37 UTC, INextYP requested changes

2024-10-22 10:37 UTC, INextYP commented on src/api/admin-api/dto/set-admin-password.dto.ts
> +  password: string;
У пароля есть минимальная длина - 6 символов. Нужно добавить этот пункт в валидацию с помощью декоратора

2024-10-22 10:37 UTC, INextYP commented on src/common/types/api.types.ts
> +export interface UpdatePasswordDto {
Некорректное название. В данном случае описывается ТИП для объекта запроса, т.е. название должно быть примерно такое: `UpdatePasswordRequestInterface`

2024-10-22 10:37 UTC, INextYP commented on src/core/users/users.service.ts
> +  private async hashPassword(password: string): Promise<string> {
Не вижу смысла в этом методе

2024-10-22 10:37 UTC, INextYP commented on src/core/users/users.service.ts
> +      throw new NotFoundException(`Пользователь с _id '${admin}' не найден<`);
Тут не `admin` а `userId`

2024-10-22 10:37 UTC, INextYP commented on src/core/users/users.service.ts
> +    if (admin.role === UserRole.ADMIN && admin.isRoot === false) {
Смысл от этого условия?

В этом методе нужно:

- найти пользователя
- если пользователя нет, то выплюнуть ошибку
- если пользователь есть, то просто изменить пароль (чтобы не было ошибок можно сразу искать в монге только админов с таким `userId`)

слишком усложняется код этими условиями, да ещё и бесполезные переменные появляются

2024-10-22 10:40 UTC, kspshnik commented on src/common/types/api.types.ts
> +export interface UpdatePasswordDto {
Скорее `UpdatePasswordDtoInterface` ;o)

2024-10-22 10:43 UTC, kspshnik commented on src/core/users/users.service.ts
> +  private async hashPassword(password: string): Promise<string> {
Код повторяется тут и в `UsersService.createAdmin()`.

2024-10-22 10:44 UTC, kspshnik commented on src/core/users/users.service.ts
> +      throw new NotFoundException(`Пользователь с _id '${admin}' не найден<`);
> Тут не `admin` а `userId`


После выполнения `await this.usersRepo.findById(userId)`-то?

2024-10-22 11:13 UTC, INextYP commented on src/core/users/users.service.ts
> +      throw new NotFoundException(`Пользователь с _id '${admin}' не найден<`);
На текущий момент тут будет:

```ts
if (!admin) {
      throw new NotFoundException(`Пользователь с _id '${admin}' не найден<`); // в переменной admin будет лежать undefined
```

Поэтому нужно заменить `admin` на `userId`

2024-10-22 12:04 UTC, kspshnik commented on src/core/users/users.service.ts
> +      throw new NotFoundException(`Пользователь с _id '${admin}' не найден<`);
А-а-а, в интерполяции. Да, конечно, ты прав.

2024-10-30 22:00 UTC, kspshnik commented on src/core/users/users.service.ts
> +    if (admin.role === UserRole.ADMIN && admin.isRoot === false) {
@INextYP а мы точно хотим дать возможность менять пароль главнюка?

2024-10-30 22:01 UTC, kspshnik requested changes
Обнови у себя `development` и реши конфликты, пожалуйста.

2024-11-01 01:33 UTC, kspshnik approved these changes
По мне так всё хорошо.
Теперь очередь за @INextYP - снимать уже его замечания :)

2024-11-01 01:42 UTC, kspshnik requested changes
Последний штрих всё-таки остался.

2024-11-01 01:42 UTC, kspshnik commented on src/core/set-admin-password.handler.ts
> +    return { admin, token };
Мы вроде везде возвращаем `{ user, token }`.
Переименуй, пожалуйста: так фронту будет сильно проще обрабатывать эту команду.

2024-11-01 15:31 UTC, kspshnik approved these changes
Вот теперь точно всё ОК :)

2024-11-01 18:48 UTC, INextYP approved these changes

2024-11-01 18:53 UTC, merged