Рефакторинг схемы Мангуста BlogPost и метода BlogService.getAllPosts().
ya-pomogau/backend pull request #224
Opened 2024-11-21 07:58 UTC by NikolaJJMusatov

2024-11-21 10:07 UTC, kspshnik requested changes
Отличная работа!
Поправь две мелких ошибки, пожалуйста - и порядок :)

2024-11-21 10:07 UTC, kspshnik commented on src/core/blog/blog.service.ts
> +    if (!user.isRoot && author.userId !== user.id) {
`user` - это расшифрованная из токена запись пользователя в БД, а у нас Мангуст, и там будет `user._id`, **не** `user.id` ;o)

2024-11-21 10:07 UTC, kspshnik commented on src/core/blog/blog.service.ts
>        throw new BadRequestException('Вы не можете редактировать чужой пост');
А это точно ошибка запроса? Кажется, тут `ForbiddenException` с его 403 подходит несколько лучше.

2024-11-21 10:07 UTC, kspshnik commented on src/core/blog/blog.service.ts
>        throw new BadRequestException('Вы не можете удалить чужой пост');
Аналогично предыдущему :)

2024-11-21 10:07 UTC, kspshnik commented on src/core/blog/blog.service.ts
> +    if (!user.isRoot && author.userId !== user.id) {
А, так это здесь было. ОК, можно не трогать, если работает.

2024-11-21 10:08 UTC, kspshnik commented
И кстати, чеклист из issue можно тут в описание продублировать - ничего страшного от этого не произойдёт :)

2024-11-21 11:21 UTC, kspshnik approved these changes
Вот теперь всё супер!
Ваше слово, товарищ ~~маузер~~ @INextYP ;o)

2024-11-21 11:24 UTC, NikolaJJMusatov commented on src/core/blog/blog.service.ts
>        throw new BadRequestException('Вы не можете удалить чужой пост');
Исключения поменял. + Все-таки user._id нужен: (updatePost, deletePost) - не отрабатывали.

2024-11-21 12:03 UTC, kspshnik approved these changes
Ну вообще прекрасно!
@INextYP твоя очередь :)

2024-11-23 13:31 UTC, INextYP approved these changes

2024-11-23 15:53 UTC, merged