Feature/volunteer releases task
ya-pomogau/backend pull request #230
Opened 2024-12-15 15:35 UTC by AlexeyKrutyakov

- [ ] В TasksService добавлен метод TasksService.releaseTask(taskId: string, user: AnyUserInterface) для отказа от задачи волонтёром.

- [ ] В методе проверяется, что именно этот волонтёр взял эту задачу.

- [ ] В методе проверяется, что до начала исполнения осталось более 24 часов.

- [ ] В методе проверяется, что задача не является бессрочной.

- [ ] Если хотя бы из одно из условий не выполнено, метод бросает ForbiddenException из пакета @nestjs/common с соответствующим ситуации комментарием ('Нельзя отказаться от чужой задачи.', 'Нельзя отказаться менее чем за сутки от начала задачи.' или 'Нельзя отказаться от постоянной/бессрочной задачи.').

- [ ] Метод изменяет значение свойства (поля) volunteer задачи на null.

- [ ] В коде есть TODO-напоминание про закрытие чата.

- [ ] Метод возвращает обновлённую задачу.

- [ ] В src/common/commands (или в src/common/commands-and-queries/commands, если PR https://github.com/ya-pomogau/backend/pull/227 будет уже влит в development) создана команда отказа от задачи волонтёром.

- [ ] В src/core создан обработчик команды отказа от задачи волонтёром.

- [ ] В обработчик инжектирован сервис задач.

- [ ] Обработчик вызывает метод из сервиса задач.

- [ ] Обработчик возвращает task.volunteer === null.

- [ ] В VolunteerApi инжектирован CommandBus.

- [ ] CommandBus импортируется из пакета @nestjs/cqrs.

- [ ] В VolunteerApi создан метод - обработчик запроса DELETE /volunteer/tasks/:id.

- [ ] Метод отправляет команду отказа от задачи волонтёром.

- [ ] Метод проверяет возврат из команды.

- [ ] При успешном снятии задачи с волонтёра отправляется пустой ответ с кодом 204 No Content.

- [ ] При неуспешном снятии задачи с волонтёра отправляется ответ с кодом 500 и телом { message: 'Не удалось снять задачу с волонтёра, произошла внутренняя ошибка сервера' }.

- [ ] Новая ручка аннотирована для Swagger с помощью декораторов из @nestjs/swagger аналогично другим ручкам в этом контроллере.

- [ ] Работоспособность ручки DELETE /volunteer/tasks/:id проверена через Postman/Insomnia как для правильного, так и для ошибочных (не своя задача, постоянная задача, до начала менее суток) вариантов использования.

2024-12-16 00:30 UTC, kspshnik requested changes
Очень хорошая работа, спасибо.

Два минорных замечания, точнее - одно минорное замечание, и один скорее комментарий, не будь замечания, я бы его и писать не стал, а так до кучи :)

2024-12-16 00:30 UTC, kspshnik commented on src/core/tasks/tasks.service.ts
> +    // TODO реализовать закрытие чата при задаче
Оно `TODO:` должно быть ЕМНИП. И я бы дописал в конец "командой".

2024-12-16 00:30 UTC, kspshnik commented on src/api/volunteer-api/volunteer-api.controller.ts
> +      throw new HttpException(
Замени на `InternalServerErrorException()` из того же `@nestjs/common`, пожалуйста.

2024-12-16 00:32 UTC, kspshnik commented on src/core/tasks/tasks.service.ts
> +    const res = await this.tasksRepo.findOneAndUpdate(query, {
Можно кстати сразу `return this.tasksRepo....` $)

2024-12-16 17:23 UTC, AlexeyKrutyakov commented on src/api/volunteer-api/volunteer-api.controller.ts
> +      throw new HttpException(
поправил

2024-12-16 18:16 UTC, AlexeyKrutyakov commented on src/core/tasks/tasks.service.ts
> +    // TODO реализовать закрытие чата при задаче
поправил

2024-12-16 18:17 UTC, AlexeyKrutyakov commented on src/core/tasks/tasks.service.ts
> +    const res = await this.tasksRepo.findOneAndUpdate(query, {
Абсолютно согласен, спасибо

2024-12-16 18:17 UTC, AlexeyKrutyakov commented
всё поправил

2024-12-16 21:11 UTC, kspshnik approved these changes
Всё супер! Спасибо, отличная работа.
Теперь ждём галочки от @INextYP  - и вмёрживаю :)

2024-12-23 16:45 UTC, INextYP approved these changes

2024-12-24 12:17 UTC, merged