Сделал модуль Contacts
ya-pomogau/backend pull request #30
Opened 2023-10-17 13:36 UTC by AlexeyNewDeveloper

Поле createdAt представлено с помощью timestamp в декораторе Schema

2023-10-17 14:32 UTC, kspshnik requested changes

2023-10-17 14:32 UTC, kspshnik commented on src/common/types/ContactsDataDTO.ts
> +  expirationDate: Date | null;
Для единообразия лучше `expiredAt` ;o)

2023-10-17 14:32 UTC, kspshnik commented on src/datalake/contacts/contacts.service.spec.ts
Спецификация тестов не нужна.

2023-10-17 14:32 UTC, kspshnik commented on src/datalake/contacts/contacts.service.ts
> +  async create(createContactDto: CreateContactDto): Promise<Contact> {
Возвращаем же не схему, а dto-шку отдельную :)

2023-10-17 14:32 UTC, kspshnik commented on src/datalake/contacts/contacts.service.ts
> +  async remove(id: number): Promise<Contact> {
Мы ничего не удаляем :)

2023-10-17 14:32 UTC, kspshnik commented on src/datalake/contacts/contacts.service.ts
> +  async findAll(): Promise<Contact[]> {
Лучше бы переименовать :) Типа `getContactsHistory()` - этот метод вернёт всё подряд, включая устаревшее :)

2023-10-17 14:32 UTC, kspshnik commented on src/datalake/contacts/contacts.service.ts
> +    return this.ContactModel.findOne({ _id: id }).lean().exec();
Нет смысла так, есть метод модели Мангуста `findById()`, надо его использовать :)

2023-10-17 14:32 UTC, kspshnik commented on src/datalake/contacts/contacts.service.ts
> +  async findOne(id: number): Promise<Contact> {
Это по факту `findById()`. 
Типизация `_id` **неверная**. Ты не забыл, что у нас *Mongo*, а не Postgres? :o)

2023-10-17 14:32 UTC, kspshnik commented on src/datalake/contacts/dto/update-contact.dto.ts
Это dto нинужно

2023-10-17 14:32 UTC, kspshnik commented on src/datalake/contacts/entities/contact.entity.ts
Возможно, лучше создать отдельно интерфейс в `/common/types/` и отдельно сразу схему?

Это для обсуждения :)

2023-10-17 14:32 UTC, kspshnik commented on src/datalake/contacts/entities/contact.entity.ts
И ещё - это _не_ entity, это schema ;o)

2023-10-17 14:32 UTC, kspshnik commented on src/datalake/contacts/contacts.service.ts
Нужен ещё метод, возвращающий *действующие* контакты (АКА `findOne({ expiredAt: null })` ;o)

2023-10-18 12:48 UTC, kspshnik commented on .prettierrc
Это корректировка правила просто.

2023-10-18 12:52 UTC, kspshnik requested changes

2023-10-18 12:52 UTC, kspshnik commented on src/common/types/ContactsDataDTO.ts
> +export class ContactsDataDTO extends CreateContactDto {}
Они не равны и не совпадают.

2023-10-18 18:57 UTC, AlexeyNewDeveloper commented
Исправил ошибки

2023-10-20 17:42 UTC, marussia1996 commented on src/common/types/ContactsDataDTO.ts
> +  _id: mongoose.Types.ObjectId;
почему тут objectId? Мы же эту DTO будем использовать в слое уже не связанной с БД. Или я что-то не понимаю?

2023-10-20 18:14 UTC, kspshnik commented on src/common/types/ContactsDataDTO.ts
> +  _id: mongoose.Types.ObjectId;
Всё правильно, `Mongo.ObjectId` остаётся ~~на дне бутылки~~ **в глубине озера данных**, наружу выйдет уже POJO, у которого `string` на этом месте вырос :)

2023-10-26 08:19 UTC, kspshnik commented
@AlexeyNewDeveloper разреши конфликты, пожалуйста?

2023-11-02 11:08 UTC, marussia1996 approved these changes

2023-11-02 11:25 UTC, kspshnik approved these changes

2023-11-02 11:25 UTC, kspshnik commented on src/datalake/contacts/contacts.service.ts
> +  private async isContactsExist(): Promise<boolean> {
По уму надо бы это в собственные методы модели убрать, ну да ладно - не принципиально, можно потом отрефакторить по ходу пьесы :)

2023-11-02 11:25 UTC, merged