Сделал datalake BlogPost
ya-pomogau/backend pull request #31
Opened 2023-10-17 15:24 UTC by AlexeyNewDeveloper

2023-10-18 12:49 UTC, marussia1996 commented on src/datalake/blog-post/schema/blog-post.schema.ts
> +  @Prop({ type: mongoose.Schema.Types.ObjectId, ref: 'Author' })
скорей не Author, а User у нас же не будет модели Author

2023-10-18 12:49 UTC, marussia1996 commented on src/datalake/blog-post/blog-post.service.ts
мб id будет string? mongoose автоматически переопределит в ObjectId при запросе к БД.

2023-10-18 13:06 UTC, kspshnik requested changes

2023-10-18 13:06 UTC, kspshnik commented on src/datalake/blog-post/blog-post.service.ts
> +  async findOne(id: mongoose.Schema.Types.ObjectId): Promise<BlogPost> {
Это в базе он `mongoose.Schema.Types.ObjectId`, а в запросе на ручку приползёт (и будет протащен через средний слой досюда) банальный `string` ;o)

2023-10-18 13:06 UTC, kspshnik commented on src/datalake/blog-post/blog-post.service.ts
> +    id: mongoose.Schema.Types.ObjectId,
Это в базе он `mongoose.Schema.Types.ObjectId`, а в запросе на ручку приползёт (и будет протащен через средний слой досюда) банальный `string` ;o)

2023-10-18 13:06 UTC, kspshnik commented on src/datalake/blog-post/blog-post.service.ts
> +  async remove(id: mongoose.Schema.Types.ObjectId): Promise<BlogPost> {
Это в базе он `mongoose.Schema.Types.ObjectId`, а в запросе на ручку приползёт (и будет протащен через средний слой досюда) банальный `string` ;o)

2023-10-18 13:06 UTC, kspshnik commented on src/datalake/blog-post/blog-post.service.ts
> +    return this.BlogPostModel.findByIdAndDelete(id).lean().exec();
А что он вернёт, кстати?

2023-10-18 13:06 UTC, kspshnik commented on src/datalake/blog-post/dto/create-blog-post.dto.ts
> +  author: mongoose.Schema.Types.ObjectId;
Тут будет просто `string` ;o)

2023-10-18 13:06 UTC, kspshnik commented on src/datalake/blog-post/schema/blog-post.schema.ts
> +  @Prop({ type: mongoose.Schema.Types.ObjectId, ref: 'Author' })
Да, так и есть. Или вообще сюда профиль пихать с `_id` в обнимку?

2023-10-18 13:06 UTC, kspshnik commented on src/datalake/blog-post/schema/blog-post.schema.ts
Ещё даты создания/изменения в схеме забыл.
Ну и общий подход к типизации.

2023-10-18 19:18 UTC, AlexeyNewDeveloper commented on src/datalake/blog-post/blog-post.service.ts
> +    return this.BlogPostModel.findByIdAndDelete(id).lean().exec();
Вернёт удаленный документ

2023-10-18 19:21 UTC, AlexeyNewDeveloper commented on src/datalake/blog-post/schema/blog-post.schema.ts
> +  @Prop({ type: mongoose.Schema.Types.ObjectId, ref: 'Author' })
Зачем весь профиль? Достаточно _id

2023-10-18 19:22 UTC, AlexeyNewDeveloper commented on src/common/types/BlogPostDataDTO.ts
> +export class BlogPostDataDTO extends CreateBlogPostDto {}
Поясни попроще плиз

2023-10-20 17:33 UTC, marussia1996 approved these changes

2023-10-20 17:33 UTC, marussia1996 commented on src/common/types/BlogPostDataDTO.ts
> +import { CreateBlogPostDto } from '../../datalake/blog-post/dto/create-blog-post.dto';
этот импорт не нужен получается)

2023-10-26 08:09 UTC, kspshnik commented on src/common/types/BlogPostDataDTO.ts
> +export class BlogPostDataDTO extends CreateBlogPostDto {}
Пожалуйста, при ресолве оставляй комментарий со ссылкой на коммит :)

2023-10-26 08:16 UTC, kspshnik requested changes

2023-10-26 08:16 UTC, kspshnik commented on src/datalake/blog-post/blog-post.service.ts
> +      .orFail(new Error(exceptions.blogArticles.notFound))
Надо кидать сразу Nest-овое исключение

2023-10-26 08:16 UTC, kspshnik commented on src/datalake/blog-post/blog-post.service.ts
> +      .orFail(new Error(exceptions.blogArticles.notFound))
Надо кидать сразу Nest-овое исключение

2023-10-26 08:16 UTC, kspshnik commented on src/datalake/blog-post/blog-post.service.ts
> +      .orFail(new Error(exceptions.blogArticles.notFound))
Надо кидать сразу Nest-овое исключение

2023-10-26 08:16 UTC, kspshnik commented on src/datalake/blog-post/blog-post.service.ts
Когда сделаем модуль файлохранилища, надо будет отрефакторить `files[]` и их отдачу, но пока оставим так.

2023-11-16 13:51 UTC, kspshnik approved these changes

2023-11-16 13:51 UTC, merged