Feat/datalake user
ya-pomogau/backend pull request #34
Opened 2023-10-18 17:51 UTC by AlexeyNewDeveloper

2023-10-20 13:32 UTC, marussia1996 commented on src/datalake/users/schemas/user.schema.ts
> +  @Prop()
наверно стоит добавить дефолтное значение 0

2023-10-20 13:32 UTC, marussia1996 commented on src/datalake/users/dto/create-user.dto.ts
> +import { UserStatus, AdminPermission } from '../../../users/types';
у тебя тут разные пути импорта, они же в одном файле будут хранится (common/types/user.types)

2023-10-26 07:49 UTC, kspshnik requested changes

2023-10-26 07:49 UTC, kspshnik commented on src/common/schemas/PointGeoJSON.schema.ts
> +  coordinates: number[];
Здесь наверное лучше задать кортеж?

2023-10-26 07:49 UTC, kspshnik commented on src/datalake/contacts/dto/create-contact.dto.ts
> +  expirationDate: Date | null;
Мне представляется правильным использовать `expiredAt` для единообразия

2023-10-26 07:49 UTC, kspshnik commented on src/datalake/users/dto/create-user.dto.ts
А зачем он?

2023-10-26 07:49 UTC, kspshnik commented on src/datalake/users/dto/update-user.dto.ts
А зачем он?

2023-10-26 07:49 UTC, kspshnik commented on src/datalake/users/users.service.ts
> +type CreateUserDtoWithoutPassword = ChangeFields<
Это лучше вынести в другую dto-шку - оно же практически совпадёт с запросом на создание

2023-10-26 07:49 UTC, kspshnik commented on src/datalake/users/schemas/user.schema.ts
> +      password: String,
select: false ?

2023-10-26 07:49 UTC, kspshnik commented on src/datalake/users/users.service.ts
> +    delete savedUserObject.administrative.password;
В схеме можно задать свойство, и не надо будет тут ничего удалять :)

2023-10-26 07:49 UTC, kspshnik commented on src/datalake/users/users.service.ts
> +  async findOne(id: mongoose.Types.ObjectId): Promise<User> {
`_id` приходит **НЕ** `Mongo.ObjectId`, а простой `string`

2023-10-26 07:49 UTC, kspshnik commented on src/datalake/users/users.service.ts
> +  async update(id: mongoose.Types.ObjectId, updateUserDto: UpdateUserDto) {
Это не `findByIdAndUpdate()`, а `updateOne()`, сигнатура другая

2023-10-26 07:49 UTC, kspshnik commented on src/datalake/users/users.service.ts
> +    return this.UserModel.findByIdAndUpdate(id, updateUserDto)
`_id` приходит **НЕ** `Mongo.ObjectId`, а простой `string`

2023-10-26 07:49 UTC, kspshnik commented on src/datalake/users/users.service.ts
> +      .orFail(new Error(exceptions.users.notFound))
Надо кидать сразу Nest-овое исключение :)

2023-10-26 07:49 UTC, kspshnik commented on src/datalake/users/users.service.ts
> +  async remove(id: mongoose.Types.ObjectId) {
Тогда и называть надо `findByIdAndRemove()`

2023-10-26 07:49 UTC, kspshnik commented on src/datalake/users/users.service.ts
> +    const xCenter = center.coordinates[0];
Зачем разбираем кортеж, чтобы потом опять собирать? :)

2023-10-26 07:49 UTC, kspshnik commented on src/datalake/users/users.service.ts
> +    return null;
А здесь не проще сделать `return (!!admin && comparePassword) ? admin.toObject() : null` ? Чем ты видишь недостаток такого подхода?

2023-10-26 07:49 UTC, kspshnik commented on src/datalake/users/users.service.ts
> +    }).orFail(new Error(exceptions.users.notFound));
Ненене. Тут мы не должны кидать, надо **именно вернуть null**, это важно для логики входа в систему.

2023-10-28 10:37 UTC, AlexeyNewDeveloper commented on src/datalake/contacts/dto/create-contact.dto.ts
> +  expirationDate: Date | null;
это уже сделано в другом PR, где я делал модуль Contact

2023-10-28 16:51 UTC, AlexeyNewDeveloper commented on src/datalake/users/users.service.ts
> +    return null;
Мне так больше нравится)

2023-10-29 13:05 UTC, kspshnik requested changes

2023-10-29 13:05 UTC, kspshnik commented on src/datalake/users/schemas/user.schema.ts
> +} from '../../../common/types/user.types';
В PR и в текущем development нет `UserProfile`

2023-10-29 13:05 UTC, kspshnik commented on src/datalake/users/schemas/user.schema.ts
> +export interface IUser {
Этому самое место в `src/common/types`

2023-10-29 13:05 UTC, kspshnik commented on src/datalake/users/schemas/user.schema.ts
> +  @Prop()
А где `default: 0` ?

2023-11-04 14:47 UTC, kspshnik requested changes

2023-11-04 14:47 UTC, kspshnik commented on src/datalake/users/schemas/user.schema.ts
>    vkID: string;
А он точно не `number`?

2023-11-04 14:47 UTC, kspshnik commented on src/datalake/users/schemas/user.schema.ts
> -    default: { type: 'Point', coordinates: [0, 0] },
А зачем значение по умолчанию, если мы **требуем**  его наличия?

2023-11-04 14:47 UTC, kspshnik commented on src/datalake/users/users.module.ts
> +          { name: UserRole.MASTER, schema: MasterUserSchema },
Схемы рута не будет - он _ОДИН_ такой, и создаваться будет только вручную.

2023-11-04 14:47 UTC, kspshnik commented on src/datalake/users/users.module.ts
> +          { name: UserRole.VISITOR, schema: VisitorUserSchema },
А это пока не подтвердили его?
Вроде тоже от этого отказались.

2023-11-04 14:47 UTC, kspshnik commented on src/datalake/users/users.service.ts
> -  async findVolunteerWithin(
Его (и пр. `check...Credentials()`) наверное лучше в собственные методы убрать?

2023-11-04 14:47 UTC, kspshnik commented on src/datalake/users/users.service.ts
> +  async create(createUserDto: AdminDataDTO): Promise<AdminDataDTOWithoutPassword> {
Мы создаём не только админов.

2023-11-04 14:47 UTC, kspshnik commented on src/datalake/users/schemas/visitor.schema.ts
В итоге нет такой роли - Посетитель.

2023-11-04 14:47 UTC, kspshnik commented on src/datalake/users/schemas/master.schema.ts
Нинада схемы для рута - он один и создаётся исключительно ручками.
Тут скорее надо хук написать, который будет принудительно убирать признак рута

2023-11-04 14:47 UTC, kspshnik commented on src/datalake/users/schemas/admin.schema.ts
> +  vkID: string;
Это здесь лишнее, админ создаётся отдельно вне зависимости от какого-то там ВК

2023-11-05 13:22 UTC, AlexeyNewDeveloper commented on src/datalake/users/schemas/admin.schema.ts
> +  vkID: string;
Я переопределил это поле, что бы там можно было указывать null. Потому что в Ноушене в карточке у админов есть vkID

2023-11-05 14:24 UTC, AlexeyNewDeveloper commented on src/datalake/users/schemas/user.schema.ts
>    vkID: string;
Мне кажется string все же

2023-11-08 15:32 UTC, AlexeyNewDeveloper commented on src/datalake/users/users.service.ts
> -  async findVolunteerWithin(
checkVKCredentials я думаю не стоит выносить в собственные. vkId у нас у любого юзера может быть

2023-11-08 15:48 UTC, kspshnik commented on src/datalake/users/users.service.ts
> -  async findVolunteerWithin(
Нет, у собственного метода _другой_ прикол - он вызывается **на модели**, а не на отдельном документе

2023-11-08 15:48 UTC, kspshnik commented on src/datalake/users/users.service.ts
> -  async findVolunteerWithin(
И у админа легко может не быть

2023-11-08 15:51 UTC, kspshnik requested changes

2023-11-08 15:51 UTC, kspshnik commented on src/datalake/users/schemas/admin.schema.ts
Этому товарищу надо добавить поле `isRoot: boolean`, и сделать хук, при записи проверяющий, был ли он установлен, и запрещающий его _модифицировать_.

2023-11-08 16:10 UTC, AlexeyNewDeveloper commented on src/datalake/users/schemas/admin.schema.ts
> +interface AdminModelStatics extends Model<AdminRole> {
Я не понял как использовать саму модель в этом свойстве. Сам класс модели определяется позже и TS ругается.

2023-11-08 19:52 UTC, AlexeyNewDeveloper commented on src/datalake/users/schemas/admin.schema.ts
Я сделал хук для админ-схемы, но я до конца не уверен, будет ли он срабатывать, если updateOne будет срабатывать на общей схеме. Тут либо это так, либо нужно будет переписывать хук для UserSchema, либо менять логику поиска, делать ее отдельно по ролям

2023-11-19 11:40 UTC, kspshnik requested changes
Для UserProfile надо сделать `virtual` `fullname` - он нужен на фронте, ну или прямо там собирать.
И **вопрос** - может быть, таки админа вынести в отдельную коллекцию? Он получается совсем отдельный гражданин - ему не нужны адреса/локации, и куча прочего из юзерской модели.

2023-11-19 11:40 UTC, kspshnik commented on src/datalake/users/users.service.ts
А попробуй упростить с использованием BaseRepository ?

2023-11-19 11:40 UTC, kspshnik commented on src/datalake/users/schemas/volunteer.schema.ts
> +  @Prop({ required: true })
Это бы тоже сделать через enum

2023-11-19 11:40 UTC, kspshnik commented on src/datalake/users/schemas/volunteer.schema.ts
> +  role: string;
Это бы тоже сделать через enum

2023-11-19 11:40 UTC, kspshnik commented on src/datalake/users/schemas/volunteer.schema.ts
> +  profile: UserProfile;
Надо декорировать с помощью `@Prop`

2023-11-19 11:40 UTC, kspshnik commented on src/datalake/users/schemas/volunteer.schema.ts
> +  vkID: string;
Надо декорировать с помощью `@Prop`

2023-11-19 11:40 UTC, kspshnik commented on src/datalake/users/schemas/user.schema.ts
> +  @Prop({ required: true })
Хорошо бы сделать тип через схему

2023-11-19 11:40 UTC, kspshnik commented on src/datalake/users/schemas/recipient.schema.ts
> +  role: string;
Надо декорировать с помощью `@Prop`

2023-11-19 11:40 UTC, kspshnik commented on src/datalake/users/schemas/recipient.schema.ts
> +  profile: UserProfile;
Надо декорировать с помощью `@Prop` и сделать тип через схему

2023-11-19 11:40 UTC, kspshnik commented on src/datalake/users/schemas/recipient.schema.ts
> +  vkID: string;
Надо декорировать с помощью `@Prop`

2023-11-19 11:40 UTC, kspshnik commented on src/datalake/users/schemas/recipient.schema.ts
> +  @Prop({ required: true })
Хорошо бы сделать тип через `enum`

2023-11-19 11:41 UTC, kspshnik commented
@AlexeyNewDeveloper  И реши, пожалуйста конфликты с базовой веткой `development` - надо втянуть её и под неё поправить файлы из списка, ну и свою ветку адаптировать :)

2023-11-21 07:46 UTC, merged