[Feature] Created Task Entity
ya-pomogau/backend pull request #39
Opened 2023-11-16 17:24 UTC by kspshnik

2023-11-16 18:11 UTC, INextYP requested changes

2023-11-16 18:11 UTC, INextYP commented on src/datalake/task/task.service.ts
Обычно такие файлы называются <moduleName>.repository.ts, а в сервисе мы уже будем внедрять этот репозиторий

2023-11-16 18:11 UTC, INextYP commented on src/datalake/task/task.module.ts
> +  providers: [TaskService],
TaskSchema и TaskService у тебя отсутсвуют  в указанных файлах.

p.s. если воспользуешься советом ниже, то тебе нужно будет расшарить в качестве провайдера и репозиторий и сервис, т.е. providers: [TaskService, TaskRepository]
или, если этот слой предназначен для работы с репозиториями, то тогда providers: [TaskRepository]

2023-11-16 18:29 UTC, kspshnik commented on src/common/types/user.types.ts
> +import { ObjectId } from 'mongoose';
Fixed

2023-11-16 18:52 UTC, kspshnik commented on src/datalake/task/task.service.ts
Fixed

2023-11-16 18:52 UTC, kspshnik commented on src/datalake/base-repository/base-repository/base-repository.ts
> +@Injectable()
Это устаревшее протекло, посмотри на пути и возвращаемые значения. Удалил :)

2023-11-17 12:58 UTC, INextYP approved these changes

2023-11-17 12:58 UTC, INextYP commented on src/datalake/task/schemas/task.schema.ts
> +import mongoose, { Document, ObjectId } from 'mongoose';
аналогично комментарию выше

2023-11-17 12:58 UTC, INextYP commented on src/datalake/blog-post/schema/blog-post.schema.ts
>  import mongoose, { HydratedDocument } from 'mongoose';
Данное замечание можно исправить по желанию .Не совсем понятно, зачем тянуть весь mongoose, если можем воспользоваться деструктуризацией. Прибавки в производительности ты конечно не заметишь, но размер финального бандла будет на пару копеек меньше

2023-11-17 13:24 UTC, merged