[Refactor] Adopt BaseRepository
ya-pomogau/backend pull request #40
Opened 2023-11-17 13:36 UTC by kspshnik

2023-11-17 13:54 UTC, INextYP requested changes

2023-11-17 13:54 UTC, INextYP commented on src/datalake/category/schemas/category.shema.ts
Ошибка в названии файла .schema.ts
И зачем вообще эта схема нужна, если выше точно такой же файл, но с новыми полями?

2023-11-17 16:21 UTC, marussia1996 reviewed
выглядит не плохо. Вопрос такой же как у Саши, зачем два файла со схемой

2023-11-17 16:36 UTC, marussia1996 approved these changes

2023-11-17 16:37 UTC, kspshnik commented
@marussia1996 @INextYP поправлено :)

2023-11-18 07:38 UTC, INextYP approved these changes

2023-11-18 07:39 UTC, merged