[Refactor] Added statict to check VK ID
ya-pomogau/backend pull request #50
Opened 2023-11-29 15:01 UTC by kspshnik

2023-12-02 15:01 UTC, INextYP requested changes

2023-12-02 15:01 UTC, INextYP commented on src/datalake/users/schemas/user.schema.ts
> +      return this.findOne({ vkID: vkId });
Не скажу, что мне нравится подход, когда методы entity расположены непосредственно в нет. По мне, лучше, когда все методы, относящиеся к получению данных из репозитория, находятся в файле *.repository.ts. Так и поддерживать код лучше, он становится полностью модульно разделенным.

p.s. твоё решение - не ошибка, можно оставить и этот вариант)

2023-12-06 14:23 UTC, kspshnik commented on src/datalake/users/schemas/recipient.schema.ts
> +    enum: [0, 1, 2, 3],
Там есть `enum`, но натолкнулся на то, что `Object.values(enum)` не обновляет содержимое после обновления `enum` :(

2023-12-06 14:25 UTC, kspshnik commented on src/datalake/users/schemas/user.schema.ts
> +      return this.findOne({ vkID: vkId });
Ну это можно убрать из собственных методов модели. Возможно, так прозрачнее будет.

Попробую сейчас :)

2023-12-06 23:42 UTC, kspshnik commented
Изменения включены в следующий PR

2023-12-06 23:42 UTC, closed without merging