Feature/categories core
ya-pomogau/backend pull request #62
Opened 2024-02-01 13:07 UTC by ulbee

2024-02-01 13:10 UTC, ulbee commented
@kspshnik Посмотри, плиз. Здесь только core часть. Увидела, что в схеме модельки название категории сделали иммутабельным, не меняла это (хотя кажется, говорили про то, что рут может изменять). Поправь меня, если нужно это поведение изменить.

Ну и контроллер пока закомментирован, просто для проверки накидала ручек. Удалю перед мерджем в ветку фичи

2024-02-01 13:28 UTC, kspshnik requested changes
И вмёржь, пожалуйста, `develop` в **фичеветку**. У тебя через это (отставание фичеветки) из 45 файлов только пять-шесть твоих - остальные тупо _обновление_ `develop`.

2024-02-01 13:28 UTC, kspshnik commented on src/api/categories-api/categories-api.controller.ts
`categories-api` не будет в природе. Работа с категориями будет в `AdminApi`, `VolunteerApi` и `RecipientApi`. 
Это можно смело удалять :)

2024-02-01 13:28 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +      category = await this.categoriesRepo.findOne({_id: id});
Для этого есть метод `findById()`

2024-02-01 13:28 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +      throw new InternalServerErrorException(exceptions.category.internalError)
Когда бросаешь 500, здорово бы добавлять объект с `{ cause: 'string decribing problem'` третьим параметром - это останется в логах и будет проще поднять что случилось. Посмотри как это сделано в `UsersService`, например:

```ts
throw new InternalServerErrorException('Internal Server Error', {
         cause: 'createUser() не создаёт администратора',
       });
     }

```

2024-02-01 17:57 UTC, ulbee commented
Обновила ПР, чтобы удобнее смотреть. Пятисотки еще поправлю

2024-02-02 18:36 UTC, ulbee commented
@kspshnik Посмотри, плиз

2024-02-06 13:47 UTC, INextYP approved these changes
По начальной функциональности всё ок. Всю красоту будем после MVP наводить

2024-02-08 09:02 UTC, kspshnik requested changes

2024-02-08 16:30 UTC, ulbee commented on src/core/categories/categories.service.ts
> +  private logger: Logger;
Я на самом деле не знаю, стоит ли добавлять логгер сейчас вообще. Я добавила пока для ситуации, когда категории записываем балком, но не все записались. 

А что должно быть в LoggerService?

2024-02-08 16:31 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +  private logger: Logger;
Там должен быть логгер :))
Пока убери?

2024-02-08 16:41 UTC, INextYP commented on src/core/categories/categories.service.ts
> +  private logger: Logger;
> Я на самом деле не знаю, стоит ли добавлять логгер сейчас вообще. Я добавила пока для ситуации, когда категории записываем балком, но не все записались.
> 
> А что должно быть в LoggerService?

Логгер сервис в любом случае потребуется, но на текущий момент для просмотра базовых ответов можно пользоваться твоей вариацией. Единственное, да, не забывай перед созданием PR сносить логгер, если он не требуется для какого-то важного дебага, который будет происходить в данном сервисе в рамках других задач..

2024-02-08 16:45 UTC, ulbee commented on src/core/categories/categories.service.ts
> +  private logger: Logger;
ок

2024-02-09 11:50 UTC, kspshnik approved these changes
Это просто вмёрж изменений из develop

2024-02-09 12:55 UTC, ulbee commented on src/datalake/base-repository/base-repository.service.ts
> +    return await this.entityModel.bulkWrite(docs, options);
Там при записи возвращается объект {insertedCount: 1, modifiedCount: 1, deletedCount: 0 }. Мне как лучше это переделать? Вернуть те категории, которые изменили, я не могу, потому что передаю в bulkWrite на самом деле не query, а массив вот таких операций 
updateOne: { filter: {_id: el}, update: {points: data[el]} }

Ну то есть наверное как-то можно вычленить из этого параметра все айдишники и потом новым запросом их вернуть из базы. Так делать?

А если там будет балковый метод на удаление, я не смогу эти же категории вернуть...

2024-02-09 13:21 UTC, ulbee commented
@kspshnik У меня там вопрос про правку, которую ты просил. Посмотри, плиз

2024-02-09 13:35 UTC, kspshnik commented on src/datalake/base-repository/base-repository.service.ts
> +    return await this.entityModel.bulkWrite(docs, options);
В принципе, я пока не вижу группового изменения в логике модели.
А `.findByIdAndUpdate()`, если ему дать `{ new: true }` в составе опций, вернёт изменённую запись

2024-02-09 13:35 UTC, kspshnik commented on src/datalake/base-repository/base-repository.service.ts
> +    return await this.entityModel.bulkWrite(docs, options);
@INextYP @vladko-89 @FenixDeveloper  что скажете?

2024-02-09 15:24 UTC, merged