Controller and service for Blog API
ya-pomogau/backend pull request #65
Opened 2024-02-12 13:05 UTC by margo-yunanova

@kspshnik , сервис создала в `src/core`, а все контроллеры пока в `AdminApi`.

2024-02-12 13:23 UTC, kspshnik requested changes
Будем потихоньку реорганизовывать :)

2024-02-12 13:23 UTC, kspshnik commented on src/api/admin-api/blog-api.controller.ts
Нененене. Ручки создания/редактирования - прямо в `AdminApiController`, создание - `@Post('/blog')`, редактирование - `@Patch('/blog/:id')`. Перенеси, пожалуйста.

2024-02-12 13:23 UTC, kspshnik commented on src/api/admin-api/blog-api.controller.ts
> +  @Get()
Все получения закомментируй пока, пожалуйста. Классно, что ты их написала, но надо будет перетащить потом.

2024-02-12 13:23 UTC, kspshnik commented on src/api/admin-api/blog-api.controller.ts
> +  @Delete(':id')
О, супер, я про удаление-то забыл.
Его тоже в `AdminApiController`, под `@Delete('/blog/:id')`

2024-02-12 13:23 UTC, kspshnik commented on src/api/admin-api/blog-api.module.ts
Это не нужно.

2024-02-12 13:23 UTC, kspshnik commented on src/api/admin-api/dto/new-post.dto.ts
> +  author: UserProfile;
Это тоже можно валидировать внутри. Посмотри на `@ValidateNested()` из `class-validator`

2024-02-12 13:23 UTC, kspshnik commented on src/app.module.ts
> +import { BlogApiModule } from './api/admin-api/blog-api.module';
Тут тоже удаляем :)

2024-02-12 13:23 UTC, kspshnik commented on src/app.module.ts
> +    BlogApiModule,
И тут :) Никакого `BlogApiModule` нет, т.к. нет отдельного `BlogApi`

2024-02-12 13:23 UTC, kspshnik commented on src/common/types/access-rights.types.ts
> +  createPost = 'CREATE_POST',
В принципе, это `contentEditor` ;o)
Но ОК, пусть будут - вдруг потом понадобится разделять эти права :)

2024-02-12 13:23 UTC, kspshnik commented on src/core/blog/blog.service.ts
> +    const { name, phone, avatar, address, _id } = await this.userRepo.findById(user.id);
Подожди. Если у тебя уже есть `user`, зачем ты его переполучаешь?

2024-02-12 13:23 UTC, kspshnik commented on src/core/blog/blog.service.ts
> +    return newPost;
А почему не напрямую `return this.blogRepo.create(...);` ?

2024-02-12 13:23 UTC, kspshnik commented on src/core/blog/blog.service.ts
> +  async find() {
Это скорее `getAllPosts()`, не?

2024-02-12 13:23 UTC, kspshnik commented on src/core/blog/blog.service.ts
> +  async findByIdAndUpdate(postId: string, updateDto: Partial<PostDTO>, user) {
А это - `updatePost()` ;o)

2024-02-12 13:23 UTC, kspshnik commented on src/core/blog/blog.service.ts
> +  async findByIdAndDelete(postId: string, user) {
И `deletePost()` соответственно :)

2024-02-12 13:23 UTC, kspshnik commented on src/app.module.ts
А переименование репозитория тут учтено? :)

2024-02-12 15:25 UTC, margo-yunanova commented on src/core/blog/blog.service.ts
> +  async find() {
В примерах в теории Яндекса и доки было, что они называют сервисы и методы просто стандартным глаголом указывающим суть. Переименую.

2024-02-12 17:56 UTC, margo-yunanova commented on src/api/admin-api/blog-api.controller.ts
done

2024-02-12 17:57 UTC, margo-yunanova commented on src/api/admin-api/blog-api.controller.ts
> +  @Get()
done

2024-02-12 17:57 UTC, margo-yunanova commented on src/api/admin-api/blog-api.controller.ts
> +  @Delete(':id')
done

2024-02-12 17:57 UTC, margo-yunanova commented on src/api/admin-api/blog-api.module.ts
done

2024-02-12 17:57 UTC, margo-yunanova commented on src/api/admin-api/dto/new-post.dto.ts
> +  author: UserProfile;
Я удалила автора из PostDto, т.к. мне данные залогиненного автора уже отдаёт Nest из request.

2024-02-12 17:57 UTC, margo-yunanova commented on src/app.module.ts
> +import { BlogApiModule } from './api/admin-api/blog-api.module';
done

2024-02-12 17:57 UTC, margo-yunanova commented on src/app.module.ts
> +    BlogApiModule,
done

2024-02-12 17:57 UTC, margo-yunanova commented on src/core/blog/blog.service.ts
> +    const { name, phone, avatar, address, _id } = await this.userRepo.findById(user.id);
В `user` нет нужной информации, через `request` приходит только:
```javascript
{
  _id: '65c4e7c022d395ab93c9f2c1',
  permissions: [ 'CREATE_POST', 'UPDATE_POST', 'DELETE_POST' ],
  login: 'test-2admin',
  password: '$2b$10$d.cTcDTFbDz17FyVj3zWc.y7c6o/7eEmExQqNziYFgzm92VWVL.6u',
  isRoot: false,
  vkId: '948378ssdd324sdf3dfg',
  role: 'Admin',
  id: '65c4e7c022d395ab93c9f2c1',
  iat: 1707740007,
  exp: 1708344807
}
```

2024-02-12 17:58 UTC, margo-yunanova commented on src/core/blog/blog.service.ts
> +    return newPost;
Мне просто так больше нравится, ок убрала
done

2024-02-12 17:58 UTC, margo-yunanova commented on src/core/blog/blog.service.ts
> +  async findByIdAndDelete(postId: string, user) {
done

2024-02-12 17:58 UTC, margo-yunanova commented on src/app.module.ts
да, всё работает

2024-02-12 18:14 UTC, kspshnik requested changes

2024-02-12 18:14 UTC, kspshnik commented on src/core/blog/blog.service.ts
> +    const { name, phone, avatar, address, _id } = await this.userRepo.findById(user.id);
А, понял. Профиль убили, а в проверке админа я поля не добавил. Исправлю.
Пока поставь `// TODO: Заменить на использование пользователя из запроса позже`, пожалуйста.

2024-02-12 18:23 UTC, kspshnik requested changes
Уже почти :)

2024-02-12 18:23 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +import { Public } from '../../common/decorators/public.decorator';
В этом Api **не может быть** публичных методов.

2024-02-12 18:23 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +  @AccessControlList({ role: UserRole.ADMIN, rights: [AccessRights.createPost] })
Добавь ещё `AccessRights.contentEditor` - это про то же самое :)

2024-02-12 18:23 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +  // TODO: перенести в SystemApi
Закомментируй эту ручку полностью, пожалуйста.
А потом поставим сюда 405 в ответ.

2024-02-12 18:23 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +  @AccessControlList({ role: UserRole.ADMIN, rights: [AccessRights.updatePost] })
Добавь ещё `AccessRights.contentEditor` - это про то же самое :)

2024-02-12 18:23 UTC, kspshnik commented on src/api/admin-api/admin-api.controller.ts
> +  @AccessControlList({ role: UserRole.ADMIN, rights: [AccessRights.deletePost] })
Добавь ещё `AccessRights.contentEditor` - это про то же самое :)

2024-02-12 18:23 UTC, kspshnik commented on src/api/admin-api/admin-api.module.ts
>    providers: [UsersService, JwtStrategy, LocalStrategy],
А здесь _точно_ не нужен `BlogService`? (это - *вопрос*, а не утверждение)

2024-02-12 19:47 UTC, margo-yunanova commented on src/api/admin-api/admin-api.controller.ts
> +  @AccessControlList({ role: UserRole.ADMIN, rights: [AccessRights.deletePost] })
done

2024-02-12 20:10 UTC, margo-yunanova commented on src/core/blog/blog.service.ts
> +    const { name, phone, avatar, address, _id } = await this.userRepo.findById(user.id);
done

2024-02-12 20:11 UTC, margo-yunanova commented on src/api/admin-api/admin-api.controller.ts
> +import { Public } from '../../common/decorators/public.decorator';
done

2024-02-12 20:11 UTC, margo-yunanova commented on src/api/admin-api/admin-api.controller.ts
> +  @AccessControlList({ role: UserRole.ADMIN, rights: [AccessRights.createPost] })
done

2024-02-12 20:11 UTC, margo-yunanova commented on src/api/admin-api/admin-api.controller.ts
> +  // TODO: перенести в SystemApi
done

2024-02-12 20:11 UTC, margo-yunanova commented on src/api/admin-api/admin-api.controller.ts
> +  @AccessControlList({ role: UserRole.ADMIN, rights: [AccessRights.updatePost] })
done

2024-02-12 20:12 UTC, margo-yunanova commented on src/api/admin-api/admin-api.controller.ts
> +  @AccessControlList({ role: UserRole.ADMIN, rights: [AccessRights.deletePost] })
done

2024-02-12 20:13 UTC, kspshnik commented on src/api/admin-api/admin-api.module.ts
>    providers: [UsersService, JwtStrategy, LocalStrategy],
ОК. Если нормально запускается и всё ресолвит - то не добавляем :)

2024-02-12 20:31 UTC, kspshnik approved these changes
Отлично! Спасибо, прекрасная работа.

2024-02-12 20:35 UTC, kspshnik approved these changes

2024-02-12 20:36 UTC, kspshnik commented
Подождём ещё аппрува @INextYP или @vladko-89  перед мёржем :)

2024-02-13 05:59 UTC, INextYP approved these changes
🥇

2024-02-13 06:57 UTC, merged