bulkWrite переделан на Promise.all
ya-pomogau/backend pull request #70
Opened 2024-02-13 11:12 UTC by ulbee

2024-02-13 11:50 UTC, kspshnik approved these changes
И для этих действий практически всех, кроме получения категории(ий) - подходит только админ, лучше использовать не `AnyUserInterface`, а `AdminInterface`

2024-02-13 11:50 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +      (user.role === UserRole.ADMIN && user.permissions.includes(AdminPermission.CATEGORIES))
Наверное, `!user.permissions.includes(...)` ?

2024-02-13 11:50 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +      res = await this.categoriesRepo.findOneAndUpdate({ _id: id }, updateData, options);
А откуда здесь `options` ?

2024-02-13 11:50 UTC, kspshnik commented on src/core/categories/categories.service.ts
>    async updateCategories(data: Record<string, number>, user: AnyUserInterface) {
Тут надо переназвать в виде `updatePoints()` или как-то так.

2024-02-13 11:50 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +    return Promise.all(
И я бы собрал сначала массив промисов, а потом бы его зафигачил в `Promise.all()` ;o)

2024-02-13 11:52 UTC, kspshnik requested changes
Извините, промахнулся кнопой.

2024-02-13 11:56 UTC, ulbee commented on src/core/categories/categories.service.ts
> +      (user.role === UserRole.ADMIN && user.permissions.includes(AdminPermission.CATEGORIES))
Точно

2024-02-13 12:03 UTC, ulbee commented
> И для этих действий практически всех, кроме получения категории(ий) - подходит только админ, лучше использовать не `AnyUserInterface`, а `AdminInterface`

done

2024-02-13 12:03 UTC, ulbee commented on src/core/categories/categories.service.ts
>    async updateCategories(data: Record<string, number>, user: AnyUserInterface) {
done

2024-02-13 12:03 UTC, ulbee commented on src/core/categories/categories.service.ts
> +      (user.role === UserRole.ADMIN && user.permissions.includes(AdminPermission.CATEGORIES))
done

2024-02-13 12:10 UTC, kspshnik requested changes
Почти готово :)

2024-02-13 12:10 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +      res = await this.categoriesRepo.findOneAndUpdate({ _id: id }, updateData, options);
Конечно. Там важно `new: true` дать, и это же не `projection`.

2024-02-13 12:10 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +      res = await this.categoriesRepo.findOneAndUpdate({ _id: id }, updateData, options);
И **где** ты определяешь эти `options`?

2024-02-13 12:10 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +      .then((res) => res)
А чего не через `async`/`await`? Лучше выдерживать единый подход.

2024-02-13 12:25 UTC, ulbee commented on src/core/categories/categories.service.ts
> +      res = await this.categoriesRepo.findOneAndUpdate({ _id: id }, updateData, options);
done

2024-02-13 12:35 UTC, ulbee commented on src/core/categories/categories.service.ts
> +      .then((res) => res)
done

2024-02-13 15:57 UTC, INextYP submitted a review, later dismissed
Всё хорошо. От меня 2 необязательных исправления)

2024-02-13 15:57 UTC, INextYP commented on src/core/categories/categories.service.ts
> +            return new InternalServerErrorException(err.message);
Почему не так:

```
 const res = await Promise.all(
    Object.keys(data).map(async (id) => await repo.findByIdAndUpdate(id, { points: data[id] }, {}))
  );
```

У нас же если в промисе возникнет ошибка, то она итак try ... catch (e) { тут обработается }

2024-02-13 15:57 UTC, INextYP commented on src/core/categories/categories.service.ts
>      const repo = this.categoriesRepo;
В чём смысл этого присваивания? Просто чтобы покороче переменная была? :)

2024-02-14 09:26 UTC, ulbee commented on src/core/categories/categories.service.ts
> +            return new InternalServerErrorException(err.message);
Я хотела обработать ситуацию, когда какой-то промис уже успел выполниться, а другой зареджектился. В этом случае я возвращаю массив результатов измененных промисов + ошибку. Например:
`[
    {
        "_id": "65bb4cd8619f6d577a74c55b",
        "title": "Cat 1",
        "points": 3000,
        "accessLevel": 2,
        "createdAt": "2024-02-01T07:48:40.707Z",
        "updatedAt": "2024-02-14T09:26:04.705Z"
    },
    {
        "response": {
            "message": "Cannot read properties of null (reading 'toObject')",
            "error": "Internal Server Error",
            "statusCode": 500
        },
        "status": 500,
        "options": {},
        "message": "Cannot read properties of null (reading 'toObject')",
        "name": "InternalServerErrorException"
    }
]`

2024-02-14 09:29 UTC, ulbee commented on src/core/categories/categories.service.ts
>      const repo = this.categoriesRepo;
Без этой константы в map другой this и к методу findByIdAndUpdate не обратиться

2024-02-14 09:58 UTC, kspshnik commented on src/core/categories/categories.service.ts
>      const repo = this.categoriesRepo;
[`Array.prorotype.map(function callback(currentValue[, index[, array]]){ ... }, [, thisArg])`](https://doka.guide/js/array-map/#peredacha-konteksta-v-kolbek-funkciyu)

Обрати внимание на **второй** (*необязательный*) аргумент: это и есть `this`, который надо прокинуть внутрь. Но также обрати внимание, что в этом случае в `.map()` **нельзя** передать лямбду ([анонимную] стрелочную функцию), так как у её ~родовая травма~ особенность - она **не имеет** `this`.

2024-02-14 10:05 UTC, kspshnik requested changes

2024-02-14 10:05 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +            return new InternalServerErrorException(err.message);
А фактически тут `Promise.all()` не работает - ты _не_ параллелишь.

Я бы не заморачивался: установка абсолютного значения суть операция _индемпонентая_ - можно повторить 318 раз, результат такой же как при однократном или пятикратном исполнении.
Проще решить, что если ошибка - то повторяем.

2024-02-14 11:20 UTC, ulbee commented on src/core/categories/categories.service.ts
> +            return new InternalServerErrorException(err.message);
Но если мы повторяем и результат одного промиса такой же (если вдруг неправильные данные, например), с ошибкой, то мы на фронте не будем показывать актуальную информацию. Часть сохранилась, часть - нет и неизвестно, какие это части. 

Если это не критично, я оставлю только один catch. Как все-таки сделать?

2024-02-14 11:45 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +            return new InternalServerErrorException(err.message);
Смотри, мы можем, если произошла ошибка, установить локальный флажок, и по нему запросить актуальные категории, вернув их и признак ошибки.

2024-02-14 13:18 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +            return new InternalServerErrorException(err.message);
Просто используй [`Promise.allSetled()`](https://learn.javascript.ru/promise-api#promise-allsettled) вместо `Promise.all()` и не надо городить всю эту поэтажную чебурашку :)

2024-02-19 12:13 UTC, ulbee commented
> Имеет смысл поправить оба момента: и this прокидывается, и Promise.allSettled() таки решает проблему :)

done

2024-02-26 11:36 UTC, kspshnik requested changes
Два небольших замечания :)

2024-02-26 11:36 UTC, kspshnik commented on src/core/categories/categories.service.ts
>        user.role !== UserRole.ADMIN ||
Это можно упростить до !(Усл.1 && Усл.2)

2024-02-26 11:36 UTC, kspshnik commented on src/core/categories/categories.service.ts
> +        (id) => this.categoriesRepo.findByIdAndUpdate(id, { points: data[id] }, {}),
`{ new: true }`, не?

2024-02-27 07:12 UTC, ulbee commented on src/core/categories/categories.service.ts
> +        (id) => this.categoriesRepo.findByIdAndUpdate(id, { points: data[id] }, {}),
Эта опция добавляется в baseRepository по умолчанию
<img width="362" alt="Screenshot 2024-02-27 at 10 10 43" src="https://github.com/ya-pomogau/backend/assets/3265187/89022c2a-40d4-425a-bd23-5b7fa2ddc282">

2024-02-27 07:16 UTC, ulbee commented on src/core/categories/categories.service.ts
>        user.role !== UserRole.ADMIN ||
done

2024-03-07 06:41 UTC, INextYP approved these changes
👍

2024-03-07 06:50 UTC, merged