[Feature]  Task handlers for Recipient & Volunteer
ya-pomogau/backend pull request #72
Opened 2024-02-13 13:15 UTC by kspshnik

Recipient is able to create and volunteer - see created non-accepted tasks,  both are able to get their tasks eithe accepted or completed, report fullfillment or rejection. Also recipient is able to edit non-accepted task and volunteer can accept.

2024-02-13 19:14 UTC, vladko-89 approved these changes

2024-02-14 21:43 UTC, INextYP submitted a review, later dismissed
Отлично!

2024-02-15 07:56 UTC, INextYP requested changes

2024-02-15 07:56 UTC, INextYP commented on src/api/admin-api/dto/new-category.dro.ts
Ошибка в названии. Не dro, а dto

2024-02-15 07:56 UTC, INextYP commented on src/api/recipient-api/dto/get-tasks-query.dto.ts
> +  longitude: number;
`GetTasksSearchDto` - это у нас query объект, а query придет с фронта строкой, соответственно, всё это дело нужно будет сначала преобразовать с помощью (как вариант) `@Type(() => Number)` или `@Transform(({ value }) => toNumber(value))` после `@ApiProperty` т.к. декораторы считываются по порядку сверху вниз

2024-02-15 07:56 UTC, INextYP commented on src/api/recipient-api/dto/get-tasks-query.dto.ts
> +  @ValidateIf((obj) => obj.location !== undefined)
Вот это же теперь не надо?

2024-02-15 07:56 UTC, INextYP commented on src/api/recipient-api/dto/get-tasks-query.dto.ts
>    end: Date;
Тут скорее всего возникнет ошибка и нужно поменять декоратор на @IsDateString()

2024-02-15 08:15 UTC, kspshnik commented on src/api/admin-api/dto/new-category.dro.ts
Fixed

2024-02-15 08:29 UTC, kspshnik commented on src/api/recipient-api/dto/get-tasks-query.dto.ts
> +  longitude: number;
Для проверки я это закостылил в контроллере, но сейчас поправил.
Fixed.

2024-02-15 08:31 UTC, kspshnik commented on src/api/recipient-api/dto/get-tasks-query.dto.ts
> +  @ValidateIf((obj) => obj.location !== undefined)
Надо, но обширнее :) Смысл - мы валидируем что есть и `distance`, и `longitude`, и `latitude`. Если хоть одной нет - они летят в форточку, свистнув дырочкой в боку :)

Fixed.

2024-02-15 08:32 UTC, kspshnik commented on src/api/recipient-api/dto/get-tasks-query.dto.ts
>    end: Date;
Fixed.

2024-02-15 09:00 UTC, INextYP requested changes

2024-02-15 10:46 UTC, INextYP requested changes

2024-02-15 10:46 UTC, INextYP commented on src/api/admin-api/dto/new-category.dto.ts
> +  @IsNotEmpty()
Порядок декораторов:
```
@ApiProperty()
@IsNotEmpty() // Проверим, что значение, которое пришло не пустое, если не пустое, то продолжаем проверку
@IsNumber() // Проверим, что значение, которое пришло является числом, если да, то продолжаем проверку
и др.
```

2024-02-15 10:46 UTC, INextYP commented on src/api/recipient-api/dto/get-tasks-query.dto.ts
>  export class GetTasksQueryDto implements Partial<GetTasksDto> {
А для чего это, если есть `GetTasksSearchDto`

2024-02-15 11:18 UTC, kspshnik commented on src/api/recipient-api/dto/get-tasks-query.dto.ts
>  export class GetTasksQueryDto implements Partial<GetTasksDto> {
У них разные декораторы из `class-validator` :)

В `GetTasksQueryDto` без геокоординат даже до контроллера не доедет, сразу полетит 400

2024-02-15 11:24 UTC, kspshnik commented on src/api/admin-api/dto/new-category.dto.ts
> +  @IsNotEmpty()
fixed

2024-02-15 11:26 UTC, kspshnik commented on src/api/recipient-api/dto/get-tasks-query.dto.ts
> +  @IsOptional()
Не уверен :)
Я же правильно понимаю, что после `@ValidateIf()`, если туда влетело `false`, дальше уже не валидирует ничего и никак?

2024-02-15 14:46 UTC, INextYP commented on src/api/recipient-api/dto/get-tasks-query.dto.ts
> +  @IsOptional()
> Не уверен :)
> Я же правильно понимаю, что после `@ValidateIf()`, если туда влетело `false`, дальше уже не валидирует ничего и никак?

Да, пусть будет так, главное, чтобы правильный статус код выкидывал, если условие не выполняется.

2024-02-15 15:12 UTC, kspshnik commented on src/api/recipient-api/dto/get-tasks-query.dto.ts
> +  @IsOptional()
А не он выкидывает. Он просто пропускает :)
А если там что-то не так, то следующие декораторы заорут как не в себя :)

2024-02-27 09:26 UTC, INextYP approved these changes

2024-02-27 11:10 UTC, merged